### ISSUE TITLE
AttributeError: 'builtin_function_or_method' object has no attribute '__xlfunc__'

### ISSUE THREAD

**Issue by spectereye** [ZoomerAnalytics/xlwings#1000]
#### i compiled my common_udfs.py to common_udfs.pyd by cython (compiler cl.exe from windows), when import the pyd file, get error below
```AttributeError: 'builtin_function_or_method' object has no attribute '__xlfunc__'```
it runs perfect when in .py, just problem to .pyd, any guide? thanks!

**Comment by fzumstein** [comment]
I personally haven't worked with cython yet. But what's the use case behind?

**Comment by fzumstein** [comment]
what about leaving the main function with the `func` decorators in a standard python file and only putting the body of the function into a cython compiled file? same issue?
