### ISSUE TITLE
Feature request: xlwings.apps to support Mapping protocol

### ISSUE THREAD

**Issue by wkschwartz** [ZoomerAnalytics/xlwings#1002]
#951 changed the `apps` API so that it functions a bit more like a mapping of PIDs to App instances. Looking up a wrong PID fails with a bare `Exception`:

```
Python 3.7.1 (default, Nov  6 2018, 18:45:35) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xlwings
>>> xlwings.__version__
'0.15.1'
>>> xlwings.apps
Apps([<Excel App 44825>])
>>> xlwings.apps[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...venv/lib/python3.7/site-packages/xlwings/main.py", line 150, in __getitem__
    return App(impl=self.impl[item])
  File "...venv/lib/python3.7/site-packages/xlwings/_xlmac.py", line 56, in __getitem__
    raise Exception('Could not find an Excel instance with this PID.')
Exception: Could not find an Excel instance with this PID.
>>> xlwings.apps[44825]
<Excel App 44825>
```
The Python language spec [says](https://docs.python.org/3/reference/datamodel.html#object.__getitem__) that `__getitem__` should raise a `KeyError` in this situation.

Since `Apps` already supports `__len__` and `__iter__`, once it raises a `KeyError` instead of `Exception`, it could subclass [`collections.abc.Mapping`](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes). Then it would automatically get the entire rest of the functionality of a Python mapping for free. Plus, it would pass tests like `isinstance(xlwings.apps, collections.abc.Mapping)`.

**Comment by fzumstein** [comment]
Fixed the Error but leaving collections.abc.Mapping for another day.
