### ISSUE TITLE
UDF with expanded return as table are called more than once on retry

### ISSUE THREAD

**Issue by Colin-b** [ZoomerAnalytics/xlwings#1007]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 7 64
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.15.1
Office 365
Python 3.6.5
#### Describe your issue (incl. Traceback!)

Not sure if this is related to the introduction of DelayedResizeDynamicArrayFormula as tasks, but it seems that the retry mechanism in case Excel is busy is now calling the UDF every time the task is retried.

According to my (very little) investigation the call seems to be originated from this line within the __call__ method of DelayedResizeDynamicArrayFormula class.

```python
formula = self.caller.FormulaArray
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
You should be able to reproduce quite easily with the sample provided in https://github.com/ZoomerAnalytics/xlwings/pull/872#issuecomment-430969126

**Comment by fzumstein** [comment]
quite possible that the refactor has something to do with it, yes

**Comment by fzumstein** [comment]
didn't actually manage to replicate this. Using the mentioned test book with this python code in debug mode:

```
import xlwings as xw
import logging

logging.basicConfig(level=logging.DEBUG)
log = logging.getLogger(__name__)

counter = 0

@xw.func
@xw.arg('nb_rows', numbers=int)
@xw.ret(expand='table')
def hello(nb_rows):
    global counter
    counter += 1
    print(counter)
    return ['value'] * nb_rows


if __name__ == '__main__':
    xw.serve()

```

Gets me this:

```
...
194
INFO:xlwings.server:Retrying TaskQueue '<xlwings.udfs.DelayedResizeDynamicArrayFormula object at 0x00000282525ED7F0>'.
195
INFO:xlwings.server:Retrying TaskQueue '<xlwings.udfs.DelayedResizeDynamicArrayFormula object at 0x00000282525ED7F0>'.
196
INFO:xlwings.server:Retrying TaskQueue '<xlwings.udfs.DelayedResizeDynamicArrayFormula object at 0x00000282525ED7F0>'.
197
INFO:xlwings.server:Retrying TaskQueue '<xlwings.udfs.DelayedResizeDynamicArrayFormula object at 0x00000282525ED7F0>'.
198
INFO:xlwings.server:Retrying TaskQueue '<xlwings.udfs.DelayedResizeDynamicArrayFormula object at 0x00000282525ED7F0>'.
199
INFO:xlwings.server:Retrying TaskQueue '<xlwings.udfs.DelayedResizeDynamicArrayFormula object at 0x00000282525ED7F0>'.
200
```

**Comment by Colin-b** [comment]
Well you did replicate, you should only see one print statement. The retry here is already supposed to contain the result. The call is not supposed to be performed again as the failure occurs when sending back the result to Microsoft Excel.

**Comment by fzumstein** [comment]
I think what you want is caching the function. Dynamic arrays don't do that automatically, you'd have to do something like this: https://github.com/ZoomerAnalytics/xlwings/issues/763#issuecomment-433982515

**Comment by Colin-b** [comment]
If I remember well, previous retry behavior on dynamic arrays was to retry sending an already computed result to Microsoft Excel.

Couldn't we foresee the same feature here? I can't think of a use case where current behavior would make sense, do you?

Maybe we could fix this issue using caching as you suggest, such as, while result is not sent back to excel we keep it in the cache and we do not ask for a recompute ?

**Comment by fzumstein** [comment]
The behaviour has not changed from before the refactor and has nothing to do with dynamic arrays. If you call a formula in 200 different cells, it has always called the formula 200 times. If you don't want that, then you'd need to cache the function itself, xlwings doesn't do that for you. As pointed out, you can do that with `lru_cache` or some third party packages like `cachetools` (that I believe you've already used). This allows you to use the caching rules that make sense for your particular use case. There are many use cases where you don't want a function to be cached, e.g. if your functions returns something like `datetime.now()`.

**Comment by Colin-b** [comment]
I think there is a slight misunderstanding of my proposal here. I am not talking about different cells.

The use case is the following:

1. User has a workbook with a single cell containing a UDF call.
2. User change the value of a parameter. He is expecting a single call to be performed.
3. But it is not the case, due to the retry mechanism, the number of calls that will be performed is unknown (might be one, might be 20 before returning result)

As you suggested, caching the result might be a workaround for this issue but I cannot assert that the result should be the same between 2 calls even if parameters do not change. I need to return the result of the user call, and not the result of any extra calls that may have been performed by the retry mechanism.

Also, there is no time limit for this retry mechanism and it can keep going for a long time. So it's hard to set a proper time limit to get rid of the cached results :/

Hope I clarified the issue here?

**Comment by fzumstein** [comment]
no, maybe i wasn't clear enough: retrying is not triggering a function to recalculate. If you think it does, please add a simple sample to replicate.

**Comment by Colin-b** [comment]
Ah yes I see were I was mistaken, I will try to provide a sample to replicate this week. Thanks again for your time.

**Comment by fzumstein** [comment]
cool thanks!

**Comment by fzumstein** [comment]
hey @Colin-b were you able to come up with an easier example to replicate the exact issue you're having here?

**Comment by Colin-b** [comment]
Apologies, hard to find some time to reproduce this issue. I will definitely try to reproduce this weekend. If not you can close it and I will reopen once I will find the time to do it :-)

**Comment by fzumstein** [comment]
ok cool, let's do that. I'll close and you reopen when you're ready. thanks.
