### ISSUE TITLE
xlwings - "import matplotlib.pyplot as plt" cause UDF "automation error the remote procedure call failed"

### ISSUE THREAD

**Issue by WeiDuan1985** [ZoomerAnalytics/xlwings#1011]
OS (Windows 10 )
Versions of xlwings, Excel and Python (0.15.0, Office 2016 32 - bit, Python 3.7 32 - bit)

#### Describe your issue (incl. Traceback!)
I have a few UDFs working properly in my Excel workbook. However, when I add this one line code "import matplotlib.pyplot as plt" to my .py file for a new UDF and click "import Functions" I receive the below error and the excel workbook stops working.

Error received: "automation error the remote procedure call failed"

```
#my code for a new UDF
import matplotlib.pyplot as plt
@xw.func
def myplot(n):
    sht = xw.Book.caller().sheets.active
    fig = plt.figure()
    plt.plot(range(int(n)))
    sht.pictures.add(fig, name='MyPlot', update=True)
    return 'Plotted with n={}'.format(n)
```

**Comment by fzumstein** [comment]
it might be this issue then: https://github.com/ZoomerAnalytics/xlwings/issues/954

**Comment by WeiDuan1985** [comment]
I have no problem of running numpy, pandas in my UDFs. However, it doesn't allow me to import matplotlib

**Comment by fzumstein** [comment]
hm ok, I'll try to reproduce in a bit

**Comment by WeiDuan1985** [comment]
close this issue, somehow it works after testing. Thanks very much @fzumstein for your help
