### ISSUE TITLE
Specifying UDF with folder

### ISSUE THREAD

**Issue by bishonen** [ZoomerAnalytics/xlwings#1014]
#### Describe your issue (incl. Traceback!)

Is it possible to define the UDF Modules to reside in different folder(s) than the excel workbook? When trying to simply add a relative path as the config parameter, loading UDFs fails with:

ypeError: the 'package' argument is required to perform a relative import for '..\\xlwings\\ xlwings_bridge'

**Comment by fzumstein** [comment]
You can set the absolute path under PYTHONPATH: http://docs.xlwings.org/en/stable/addin.html#global-settings
