### ISSUE TITLE
Syntax error RunPython, sys.path

### ISSUE THREAD

**Issue by benmsmith1221** [ZoomerAnalytics/xlwings#1015]
##### System info
OS = windows 10, xlwings - 0.11.5, excel - office 365, python 3.6.4 (Anaconda 3 using spyder IDE)

#### Sample Workbook:
[UDFs-GMAT.xlsx](https://github.com/ZoomerAnalytics/xlwings/files/2697311/UDFs-GMAT.xlsx)

#### Describe your issue: 
New issue I encountered after modeling my first xlwings project off the 'myproject' example. Myproject is working when I run it from VBA, which makes me think this is more of a python/directory issue. Hoping someone with more expertise can provide some clarity on the nature of my syntax error as I have a more limited scope with this tool.

```python
  File "<string>", line 1
    import sys, os; sys.path.extend(os.path.normcase(os.path.expandvars(r'C:\Users\benms\OneDrive\Documents\GMAT')).split(';')); import UDFs-GMAT;UDFs-GMAT.DistributionTwoDigit()                                                                                                                                
SyntaxError: invalid syntax

#### Here's the python code. RunAnswer is a function I defined in a separate file in the same 
directory as the rest of the code, as well as my UDFs-GMAT workbook:
```python
import random
import xlwings as xw
import sys, os, os.path
#import os, os.path
#import win32com.client
from .VBAInput import RunAnswer
    
def DistributionTwoDigit():
    wb = xw.Book.caller()
    x = random.randrange(10, 99, 1)
    y = random.randrange(10, 99, 1)
    i = 0

    i =+ 2
    wb.sheets[0].range("A1").value = "Distribution (Two-Digit)"
    wb.sheets[0].range(i+1,1).value = '{}*{}'.format(x, y)
        
    RunAnswer()
    wb.sheets[0].range(i+3,1).value = (x*y)
        
    wb.sheets[0].range(i+4,1).value = '-------------------------------'
    x = random.randrange(10, 90, 1)
    y = random.randrange(10, 90, 1)

```

**Comment by Pluckerpluck** [comment]
I'm about 95% sure you're not allowed dashes in module names.

Specifically `UDFs-GMAT` is not a valid module name. So you're going to have to rename it to not have a dash (underscores work)

**Comment by benmsmith1221** [comment]
@Pluckerpluck - thank you so much! This worked!! :) Just had to change the way I was importing my other module.
