### ISSUE TITLE
Add plt.show() inside a sheet

### ISSUE THREAD

**Issue by abhi3700** [ZoomerAnalytics/xlwings#1020]
#### OS (e.g. Windows 10 or macOS Sierra)
Window 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings - 0.15.1, Excel  2016, Python 3.6+
#### Describe your issue (incl. Traceback!)
I want to add hover feature on my plot, which gets activated with `plt.show()`, but not with standard xlwings method i.e. `sht.pictures.add(fig, name='MyPlot', update=True)`

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
I am using [this](https://stackoverflow.com/a/33733491/6774636), but getting error - doesn't exist.
```python
datacursor(lines, hover=True, point_labels=df_cp['Remarks'])
sht_cp_plot.activate()
plt.show('ASFE1_CP_Plot', left=xw.Range('A1').left, top=xw.Range('A1').top)
```

**Comment by abhi3700** [comment]
Didn't get any comment.
So, closing this issue :(

**Comment by fzumstein** [comment]
sorry about that. xlwings adds the plot as simple picture to Excel, so interactivity is not supported.
