### ISSUE TITLE
When copy value from range("a1:a100") to range("b1:b100") doesn't work correctly

### ISSUE THREAD

**Issue by madainigun14** [ZoomerAnalytics/xlwings#1023]
#### Describe your issue (incl. Traceback!)

```python
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
`
# -*- coding:utf-8 -*-
import xlwings

if __name__ == '__main__':
    filename =  "C:\\test.xlsx"
    app_current = xlwings.App(visible=True, add_book=False)
    book_current = app_current.books.open(filename)
    sheet_current = book_current.sheets[0]

    price = sheet_current.range("b2:b14").value
    sheet_current.range("d2:d14").value = price`

```
 before running ,what's in  test.xlsx ：
![image](https://user-images.githubusercontent.com/28619306/51540445-68de4880-1e91-11e9-980a-7f2eb79b7297.png)

run the code above , the outcome is as follow:
![image](https://user-images.githubusercontent.com/28619306/51540327-1d2b9f00-1e91-11e9-9a72-b6412da4a688.png)
obviously not corret,

 what I expect is:
![image](https://user-images.githubusercontent.com/28619306/51540381-41877b80-1e91-11e9-8715-891bbe1efbd1.png)

But,  if we copy a2:b14 to d2:e14,  the result is correct.  the code looks like

`price = sheet_current.range("a2:b14").value
    sheet_current.range("d2:e14").value = price`

the result is perfect and very fast
![image](https://user-images.githubusercontent.com/28619306/51540662-fa4dba80-1e91-11e9-8381-b3a77244352f.png)

so, here is the conclusion

when we try to copy the value using range(), if the range is in a same column, such as range("a1:a100").value ,  the result is not correct

**Comment by fzumstein** [comment]
1d arrays have a special and documented behaviour: http://docs.xlwings.org/en/stable/datastructures.html#lists

Use something like `sheet_current.range('A1:A5').options(ndim=2).value` to preserve the column orientation.
