### ISSUE TITLE
Is there any way to deploy xlwings udf to non-python-installed computer?

### ISSUE THREAD

**Issue by rightx2** [ZoomerAnalytics/xlwings#1027]
I've made up my own udfs and want to deploy to other people. What I want is that they can use them without installing python on their computer. Is it possible? If so, could you recommend issues or page dealing with it?

**Comment by fzumstein** [comment]
there's an issue for that: https://github.com/ZoomerAnalytics/xlwings/issues/481 please I am closing this issue. for anything else, please continue on the other issue, thanks.
