### ISSUE TITLE
Unrecoverable automation error when calling any UDF

### ISSUE THREAD

**Issue by patrickbivona** [ZoomerAnalytics/xlwings#1029]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10 Profressional

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.15.1 from Anaconda
Python 3.7
Excel for Office 365 16.0.11126.20234 32 bits

#### Describe your issue (incl. Traceback!)
After somehow modifying an xlwings-enabled workbook, the file seem to fail when calling any UDF. It was previously working but it does not anymore, without any configuration change to xlwings.
I have created a stripped-down version of the workbook mimicking the quickstart project with hello() UDF both attached).

```python
import xlwings as xw

@xw.func
def hello(name):
    return "hello {0}".format(name)
```

This fails as well, while all other files I have are working fine, including if I create a new quickstart project.
It would seem this file became invalid somehow in a way but I cannot say how nor what's wrong.

The only error I get is (in French) "Erreur Automation Défaillance Irrémédiable" which I would translate to Automation Error Unrecoverable Fault.

I would like to understand how to resolve it in case it happens again.

[UnrecoverableAutomationError.zip](https://github.com/ZoomerAnalytics/xlwings/files/2821697/UnrecoverableAutomationError.zip)

**Comment by fzumstein** [comment]
You seem to have a corrupted workbook according to this SO thread: https://stackoverflow.com/questions/18273071/excel-vba-project-has-generated-multiple-workbook-objects as you have multiple sheet/workbook objects in your VBA:

<img width="357" alt="screenshot 2019-02-04 at 20 00 06" src="https://user-images.githubusercontent.com/2265504/52243134-7f37cb80-28b7-11e9-904e-96bbecac33f4.png">

**Comment by patrickbivona** [comment]
Thanks Felix, that's probably what it is. No idea how it came to that though.
At least there's nothing to do on the xlwings side, unless I have steps to reproduce that proves otherwise.

**Comment by fzumstein** [comment]
sure, in that case please reopen.
