### ISSUE TITLE
how to unprotect a sheet?

### ISSUE THREAD

**Issue by trymelz** [ZoomerAnalytics/xlwings#1032]
Really need this feature.  I searched the pull requests, it was there, but still could not find it in the released version...

**Comment by abhi3700** [comment]
For this, you might have to write the function module in VBA and then fetch using Python code (in .py file).
VBA protect reference: https://www.excel-easy.com/vba/examples/protect-macro.html
Run VBA code using python: https://github.com/ZoomerAnalytics/xlwings/issues/134 

Try this.

**Comment by fzumstein** [comment]
In theory you should be able to use `.api` to fall back to pywin32 and do what is not covered natively in xlwings. Currently, however, the sheet object on windows is messed up by the retry wrapper, so you'd need to do the following until it is properly fixed `mysheet.api._inner.Unprotect()`

**Comment by trymelz** [comment]
Awesome! Thanks for your quick response. It works!

**Comment by fzumstein** [comment]
it was a bit late, when I wrote the answer, so please drop `_inner` (I've updated the solution now above).
