### ISSUE TITLE
BOOK_CALLER missing from xlwings/_xlmac.py

### ISSUE THREAD

**Issue by christiankissig** [ZoomerAnalytics/xlwings#1035]
#### OS (e.g. Windows 10 or macOS Sierra)

MacOS High Sierra 10.13.6

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

$ pip show xlwings
Name: xlwings
Version: 0.15.2

#### Describe your issue (incl. Traceback!)

```python
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/Users/kissig/myproject/myproject.py", line 5, in hello_xlwings

    wb = xw.Book.caller()

  File "/usr/local/lib/python3.7/site-packages/xlwings/main.py", line 567, in caller

    elif xlplatform.BOOK_CALLER:

AttributeError: module 'xlwings._xlmac' has no attribute 'BOOK_CALLER'
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```
xlwings quickstart myproject
```

BOOK_CALLER is missing from https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/_xlmac.py . It's present in https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/_xlwindows.py .

**Comment by fzumstein** [comment]
this is a regression with 0.15.2, thanks for reporting. I'll try to release a fix asap. in the meantime please downgrade to 0.15.1

**Comment by christiankissig** [comment]
Thanks Felix! Btw I'm seeing the same issue with all xlwings versions at least back to 0.14.0 - installed with pip.

**Comment by fzumstein** [comment]
that's unexpected though - you do have the addin version and python version aligned, do you? anyways, will look into it.

**Comment by fzumstein** [comment]
Just checked it out, it's definitely a regression in 0.15.2, my guess is that something went wrong when you downgraded to 0.15.1. I'll try to fix this weekend.
