### ISSUE TITLE
Unable to open xlsx file

### ISSUE THREAD

**Issue by martmists** [ZoomerAnalytics/xlwings#1038]
#### OS
Windows 10
#### Versions of xlwings, Excel and Python
xlwings: latest to date
Excel: Using latest LibreOffice Calc and saving as xlsx
Python: 3.7.2
#### Describe your issue
I am unable to import my xlsx file.

```python
>>> wb = xw.Book("bot.xlsx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "X:\Python\lib\site-packages\xlwings\main.py", line 487, in __init__
    app = App(add_book=False)
  File "X:\Python\lib\site-packages\xlwings\main.py", line 212, in __init__
    self.impl = xlplatform.App(spec=spec, add_book=add_book)
  File "X:\Python\lib\site-packages\xlwings\_xlwindows.py", line 296, in __init__
    self._xl = COMRetryObjectWrapper(DispatchEx('Excel.Application'))
  File "X:\Python\lib\site-packages\win32com\client\__init__.py", line 113, in DispatchEx
    dispatch = pythoncom.CoCreateInstanceEx(clsid, None, clsctx, serverInfo, (pythoncom.IID_IDispatch,))[0]
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)
```

Workbook:
[bot.xlsx](https://github.com/ZoomerAnalytics/xlwings/files/2894631/bot.xlsx)

**Comment by martmists** [comment]
Just did some testing, plain `xw.Book()` fails too with the same error.

**Comment by fzumstein** [comment]
what version of pywin32 are you running?

**Comment by martmists** [comment]
Version 224

**Comment by martmists** [comment]
Figured out I need Excel, where I have LibraOffice Calc. I thought this library was for parsing functions, as `formulas` is outdated, but it seems no such library currently exists.

**Comment by zhiming429438709** [comment]
why the issue is closed？

**Comment by metalbreeze** [comment]
> why the issue is closed？
because it said need Excel installed

**Comment by halt9k** [comment]
xlwings does not report properly that Excel is missing or installation is not detected. This is still an important issue.
