### ISSUE TITLE
addin ribbon > 0.11.4 doens't show up in Excel 2007

### ISSUE THREAD

**Issue by jekasi01** [ZoomerAnalytics/xlwings#1039]
#### 
Hi ZoomerAnalytics,
'conda install xlwings' worked and `xlwings.__version__` shows 0.15.2. But 'xlwings addin install' in the command prompt returns xlwings not recognized as an internal or external command. Therefore Quickstart won't work either.  Instead I tried to simply copy xlwings.xlam from the Anaconda3 folder into the XLSTART folder but then the xlwings menu tab doesn't appear. Weird thing is that the xlwings.xlam from version 0.11.4 does make the xlwings menu tab appear. I've been reading many many peoples comments on how to possibly make it work and tried, but I am giving up at this point. Would know how to overcome these issues starting with xlwings not recognized in the command prompt?
Thanks for your help

**Comment by fzumstein** [comment]
to get `xlwings` recognized, you need to make sure to add `C:\Path\to\python\Scripts` folder to your Path environment variable. If you have troubles installing the addin, you can also just point to it from `File > Options > Add-ins > Manage Excel Add-ins > Go`

**Comment by jekasi01** [comment]
Hi Felix,
Thanks for your quick reply :-) Adressing the second part first, I did go through the Excel manager to add the addin manually, but xlwings does not appear in the top menu for version 0.15.2. I presume that your first point refers to the PATH field under the xlwings menu tab that I did see when I used the version 0.11.4 xlwings.xlam addin. However, I don't get the xlwings menu tab using version 0.15.2. Also, using version 0.11.4 xlwings.xlam that did give me a xlwings menu tab, when I closed down Excel and started it up again the xlwings menu tab does not appear??? I have read that some other people have had the same issue. Would you know how to overcome this? 
Kind regards and thanks for your help.

**Comment by fzumstein** [comment]
With regards to the path environment variable: No, it is something on Windows level: https://www.computerhope.com/issues/ch000549.htm
When you type `Alt-F11`, does xlwings appear in the VBA editor under VBA projects?

**Comment by jekasi01** [comment]
Hi Felix,
Ah, I see. OK I added the path to where my Python script is and, hooray, it worked, as in now xlwings.xlam version 0.11.4 the xlwings menu appears every time I start Excel. But it still does not appear for xlwings.xlam version 0.15.2 (I haven't tried version 0.15.3 which I see that you made available a couple of hours ago). Also, xlwings is not recognised in the command prompt. I can confirm that xlwings appears under VBA Projects and also in VBA tools - references. I suppose I can work with version 0.11.4, but it would obviously be great if I could use the latest and future versions. Would you have any suggestions on why xlwings.xlam version 0.15.2 does not appear in the menu whereas xlwings.xlam version 0.11.4 does?
Thanks for your kind help again

**Comment by fzumstein** [comment]
The ribbon is only meant for a single version, i.e. you need to replace 0.11.4 with 0.15.2.

**Comment by jekasi01** [comment]
Hi Felix,
Yes, I only have either xlwings.xlam version 0.11.4 or xlwings.xlam version 0.15.2 in the XLSTART folder at any given time, not both. I presume that is what you mean that it is meant for a single version. When only xlwings.xlam version 0.11.4 is in the XLSTART folder the xlwings menu appears. When only xlwings.xlam version 0.15.2 is in the XLSTART folder the xlwings menu does not appear.
Kind regards

**Comment by abhi3700** [comment]
I think for MS Excel 2007, only xlwings- 0.11.4 would show up in the menu.

I myself use that in office, but 2016 at home.

But for latest xlwings' features access, Excel 2016+ has to be used.

**Comment by jekasi01** [comment]
Hi Abhijit and Felix,
Aaahhh I see. That would explain it. OK, it's no problem really as I it seems that 0.11.4 is already very good. Thanks for your attentive help and for creating an excellent product.
Kind regards

**Comment by fzumstein** [comment]
The xlwings ribbon is supposed to work in the latest version with all versions of Excel including 2007. If it doesn't, it's a bug. I'll try to get my hands on a 2007 version of Excel to replicate the issue.

**Comment by jekasi01** [comment]
Hi Felix,
I just checked if the menu appears in Excel 2007 SP1 using xlwings.xlam version 0.15.3 and I can confirm that it does not (on my PC).
Kind regards

**Comment by fzumstein** [comment]
Found the issue and will be fixed in next release.

**Comment by jekasi01** [comment]
Wow cool thx - that was quick :-) I will look out for the next issue. Thanks a lot
