### ISSUE TITLE
customUI errors

### ISSUE THREAD

**Issue by Agent6-6-6** [ZoomerAnalytics/xlwings#1041]
#### xlwings 0.15.2, Excel 365, Python 3.7

When selecting the xlwings ribbon group the following customUI error/warning occurs:-
![firsterror](https://user-images.githubusercontent.com/36808164/53290690-99a4fb00-380c-11e9-9bfa-f395e33923e3.png)
If you open the xlam file in the 'Custom UI editor for Microsoft Office' and do a validate on the XML code you get the following warning/error, with the suggestion for an alternative schema (note if you change this <s>it did not solve the above error</s>EDIT - actually after restarting excel I think it has corrected the issue (but I also checked the RunPython checkbox in the ribbon after getting the error which may do something to correct the issue?):-
![seconderror](https://user-images.githubusercontent.com/36808164/53290724-fc969200-380c-11e9-9e7b-e97ebcf82bcb.png)

Note you need the show user-addin interface errors selected to replicate and show the warnings.
![image](https://user-images.githubusercontent.com/36808164/53290755-7464bc80-380d-11e9-80a1-18423b699e48.png)

Regards

**Comment by fzumstein** [comment]
the warning seems bogus as you can find recent docs with that reference, e.g.: https://docs.microsoft.com/en-us/openspecs/office_standards/ms-customui/d842006e-3187-4f66-a17d-0819a3cc94b5

However, I think I fixed that error you saw, will release shortly, let me know if that doesn't resolve it.

**Comment by Agent6-6-6** [comment]
All good the 0.15.3 change to the callback sorted it.
