### ISSUE TITLE
Run-time error '1000' and AttributeError: module 'myproject' has no attribute 'hello_xlwings'

### ISSUE THREAD

**Issue by Brad-eki** [ZoomerAnalytics/xlwings#1042]
OSWindows 10

Anaconda, env: C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py37\

xlwings 15.3
Excel 365 (16.0.11231.20164) 32 bit
Python 3.7.2

xlwings has been installed in the anaconda env py37, and is confirmed not installed in the base

Can't get xlwings to work after following the install instructions. A few messages depending on the circumstance...

**Circumstance 1**

<code>xlwings quickstart myproject</code>
<code>cd myproject</code>

open myproject.xlsm

enable macros

Configure:-
interpreter: C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py37\pythonw.exe
No PYTHONPATH
Debug UDFs: Yes
Log File: C:\Users\me\\.xlwings
RunPython: Use UDF Server: Yes

* the xlwings dlls are confirmed to be in the same directory as the above pythonw.exe *

make a button. associate it with SampleCall()

edit SampleCall() to simplify code:
<code>RunPython ("import myproject;myproject.hello_xlwings()")</code>

Click the new button.

Run-time error '1000';
No command in the configuration, cannot start autostart server

Now to start the server.

**Circumstance 2**

In an Anaconda prompt **not changing directory**:
<code>conda activate py37</code>
<code>python -c "import xlwings as xw; xw.serve()"</code>
<code>xlwings server running, clsid={506E67C3-55B5-48C3-A035-EED5DEEA7D6D}</code>

pythoncom error: Python error invoking COM method.

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\win32com\server\policy.py", line 278, in _Invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\win32com\server\policy.py", line 283, in _invoke_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\win32com\server\policy.py", line 586, in _invokeex_
    return func(*args)
  File "C:\Users\me\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\xlwings\server.py", line 287, in Exec
    exec(stmt, globals, locals)
  File "<string>", line 1, in <module>
AttributeError: module 'myproject' has no attribute 'hello_xlwings'

hello_xlwings most certainly exists... It was crated by the quickstart. I can see it. The myproject.py is in the same directory as the .xlsm - again, quickstart did that for me.

**Circumstance 3**

So now, we ^C out of the server, remain in the anaconda activated env py37 and change directory to myproject.

Again we try and start the server, but this time we are in the same directory as all the myproject files:
<code>python -c "import xlwings as xw; xw.server()"</code>
<code>xlwings server running, clsid={506E67C3-55B5-48C3-A035-EED5DEEA7D6D}</code>

Ding! - it works.

Previous versions of xlwings didn't have a requirement to start the server yourself.

Besides going back to version 11, which version couldI roll back to which works?

**Comment by Brad-eki** [comment]
Same symptoms occurring in 15.2.

**Comment by Brad-eki** [comment]
Same symptoms for version 11.8.

Something is obviously very wrong.

Since I've been having trouble with xlwings, my Excel is claiming it cannot open two files of the same name on open. But I most certainly do not have more than one Excel file open, let alone attempting to open two of the same name. Any ideas on what that could be..?

**Comment by Brad-eki** [comment]
I _think_ have found when there is a version mismatch between the xlwings version installed in the site-packages and the xlam file in the trusted directory.

Excel reports two files open with the same name when there is only one Excel file open.

You can only successfully change the xlam file when Xlwings is not selected in the add-ins dialog box.

**Comment by fzumstein** [comment]
I think there are some misunderstanding with regards to how debugging works: You are supposed to have the `xw.serve()` on the source file of your function otherwise it doesn't know where to look for your functions, see: http://docs.xlwings.org/en/stable/debugging.html#udf-debug-server

**Comment by Brad-eki** [comment]
@fzumstein You are correct, I did miss that detail.

There are other issues I've been having, so I'll re-attempt them without the debug flag checked and if I have further issues I'll report them as I find them.

Cheers
