### ISSUE TITLE
fetch RTD data from excel to python

### ISSUE THREAD

**Issue by punittewani** [ZoomerAnalytics/xlwings#1046]
OS Window 10

xlwings 0.15.13, Excel 2007 and Python 3.5

I am using RTD in excel to fetch values realtime. 
The RTD formulae I use is rtd("pi.rtdserver" ,"MCX_CRUDEOIL19MARFUT", "Last")
Please help me call this in python directly. Thus eliminating use of excel.

**Comment by fzumstein** [comment]
I think this is a duplicate of #888. Let me know if not.

**Comment by zbjdonald** [comment]
See [this SO answer](https://stackoverflow.com/a/28401348). Do not try control .CalculationState, use default `wb.app.calculation = 'automatic'`. Try set formula first `sheet.range('A1').formula = RTD_excel_formula_str`, and periodically get value `sheet.range('A1').value`
