### ISSUE TITLE
xlwings 0.15.3 Try to load xlwings32-0.15.2.dll

### ISSUE THREAD

**Issue by WinQuant** [ZoomerAnalytics/xlwings#1049]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 2008

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.15.3 (installed with pip install xlwings)
Excel 2010
Python 3.6

#### Describe your issue (incl. Traceback!)

I installed the xlwings Excel add-in manually, by "Add-in" in Developer tab and browse to the xlwings.xlam installed in CONDA_HOME/Lib/site-package/xlwings/addin/xlwings.xlam.

In the xlwings tab, the version in the Advance section shows 0.15.2 and when "Import Functions", it tries to load xlwings32-0.15.2.dll, which does not exist as the version installed is 0.15.3.

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment]
I can't replicate this, the version packed with 0.15.3 is definitely 0.15.3. But you can always download the addin from the [release page](https://github.com/ZoomerAnalytics/xlwings/releases) directly.

**Comment by fzumstein** [comment]
Closing this. Feel free to reopen if the issue persists.
