### ISSUE TITLE
Call xlwings from Python: safearray error

### ISSUE THREAD

**Issue by JollyJumper1** [ZoomerAnalytics/xlwings#1061]
#### Describe your issue (incl. Traceback!)
Hello - I have code in Python which returns a DataFrame. I am trying to assign the DataFrame to a variant array in xlwings, but I get the following error:
Unexpected Python error: memory error: creating SafeArray

The code works in Python and the DataFrame is a 307 by 75 table. The DataFrame contains a mixture of data types.

Just wondering whether I am doing anything wrong?

```python

Dim avarInstruments() as variant

avarInstruments = loadInstruments()

function loadInstruments()
    If TypeOf Application.Caller Is Range Then On Error GoTo  failed    
        loadInstruments = Py.CallUDF("PythonScript", "loadInstruments", Array(), ThisWorkbook, Application.Caller)
    Exit function
failed:
    loadInstruments = ERR.description
end function

```

**Comment by fzumstein** [comment]
Please add a full example (with an Excel workbook and Python code) to replicate.

**Comment by JollyJumper1** [comment]
Hi Felix - thanks for helping. I found the error: one of the variables was a list and it seems that a VBA array cannot hold a list.

**Comment by fzumstein** [comment]
OK closing this then. feel free to provide more context of what you are trying to achieve to see if there's a solution.
