### ISSUE TITLE
Question: Can I restart the UDF server and The function import by programming? not from the add-in.

### ISSUE THREAD

**Issue by Hmissa** [ZoomerAnalytics/xlwings#1062]
Hi,

My question is : 
Can I restart the UDF server and the function import by VBA programming, not from the Add-in ribbon?

Thank you,
Saif.

**Comment by fzumstein** [comment]
In VBA, you can call the `KillPy` function from the addin. When you call the next function, it'll autorestart the server:

```
Sub Restart()
    KillPy
End Sub

```
