### ISSUE TITLE
How to set the color of a font in a cell？

### ISSUE THREAD

**Issue by Purple-tulip** [ZoomerAnalytics/xlwings#1066]
Windows 10  

Versions of xlwings,： __version__ = '0.11.4'
Excel and Python (e.g. 0.11.8, Office 365, Python 3.6.3)

please tell  me  How to set the color of a font in a cell？
Now I know how to set the background color of the cell. But I want to set the color of a font in a cell. 

The next code is to set the background color  : 
        wb = xw.Book(path)
        sht = wb.sheets[sheet]
        rng = sht[cell]
        rng.color = color
        wb.save()
I took a close look at the xlwngs code, but I didn't find the way to set it up. Is it that I don’t see it carefully? Please tell me how to set up?  Thanks :)

**Comment by Purple-tulip** [comment]
![color](https://user-images.githubusercontent.com/40619268/55204178-fd09ba80-5208-11e9-83a1-b6da6cea41d8.PNG)

**Comment by Purple-tulip** [comment]
The color of the data in the cells in the image is different.
Now,i want to use xlwings to set the color.
please tell me how to make it?
Thanks a lot :)

**Comment by fzumstein** [comment]
For now you'd have to work around like this: 

```
>>> import xlwings as xw
>>> from xlwings.utils import rgb_to_int
>>> wb = xw.books.active
>>> sht = wb.sheets[0]
>>> sht.range('A1').api.Font.Color = rgb_to_int((20, 20, 255))
```

see also: http://docs.xlwings.org/en/stable/missing_features.html

**Comment by Purple-tulip** [comment]
Thanks , thanks , thanks!   
I checked the documentation for xlwings，and found this   " api  Returns the native object (pywin32 or appscript obj) of the engine being used. "
so i will view pywin32.  I have a lot of things to learn.
Good luck !

**Comment by vba34520** [comment]
How to set single word of a cell?
Like, "ABCDE", "C" is red.

![image](https://user-images.githubusercontent.com/40198281/98785589-cc0ae780-2437-11eb-86de-831b41823427.png)

Looking forward to your reply! Thanks

**Comment by vba34520** [comment]
Here is example code:
```python
import xlwings as xw
from xlwings.utils import rgb_to_int

wb = xw.Book()
sht = wb.sheets['Sheet1']
sht.range('A1').value = 'ABCDE'

start_index = 3  # start from 1
length_string = 1
sht.range('A1').api.GetCharacters(start_index, length_string).Font.Color = rgb_to_int((255, 0, 0))  # Red

input('Enter to quit')
wb.close()
```
