### ISSUE TITLE
Returning different types

### ISSUE THREAD

**Issue by ankitagra** [ZoomerAnalytics/xlwings#1067]
#### How can I write a UDF that can return objects of different types depending on the input, lets say it retursn a scalar variable if input=='a', returns a Series if input=='b', or returns a DataFrame if input=='c'?

```python
@xl.func
@xl.ret( ?? )     #What parameters to use here? Can we make them dynamic?
def show_value(input):
    """Displays value of the stored variable"""

    if input=='a':
        return 1
    elif input=='b':
        return pd.Series([1,2,3], index=[4,5,6])
    elif input=='c':
        return pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], index=['a','b','c'])
```

**Comment by fzumstein** [comment]
dont use decorator but handle your customization directly in the code. eg if you want to leave away the headers of a df, do `df.values()`

**Comment by ankitagra** [comment]
I see. But will it dynamically expand to the size of the output then?

**Comment by ankitagra** [comment]
Thanks Felix. Per your suggestions, I applied customization within my code, and it works. I used @xw.ret(...) only with ``expand='table'`` option for dynamic expansion, and it behaves well with scalars too.
On a separate note, it would be nice to have native support for 'OrderedDict' in xlwings (like 'dict'). Currently, for 'OrderedDict', I am returning it as a 2D list (or Series).
