### ISSUE TITLE
multiprocessing threading does not work when calling xlwings from vba (Mac)

### ISSUE THREAD

**Issue by EmilyBarbour** [ZoomerAnalytics/xlwings#115]
I think this is related to the ssh not working when calling from vba that I submitted before.  

I have a threading function that creates pools and processes data.  The code works fine in python outside of xlwings and also works when calling xlwings from python.  It hangs when calling from vba.

**Comment by ArmandoOC** [comment]
Hello,
Does the most recent version of xlwings support multi-threading?

**Comment by fzumstein** [comment]
No, it's still open.

**Comment by ArmandoOC** [comment]
Ok, thanks. :)

**Comment by fzumstein** [comment]
This should now be resolved, see #1008. If this still persists, please add a sample to reproduce.
