### ISSUE TITLE
Make it easier to find/include the VB module

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#122]
Possibly include a template sheet that can be fired up with an easy command.

**Comment by ankostis** [comment]
An useful addition would be a xlwings cmd-line (or a plain python function) tool that imports the `vbas` code into a given excel-workbook.

Something like the following cmd-line example:

    > xlwings some_workbook.xlsx
    Adding xlwings's VBA-code `/full/path/of/some_workbook.xlsx-->some_workbook.xlsm`...Done.

**Comment by fzumstein** [comment]
I agree about the command line, but I couldn't really make it work on Mac yet (Excel was crashing). So for now, version 0.3.3 will feature this:

    >>> Workbook.open_template()

and will open an empty Excel file with the VBA module included. I don't think that you can inject code from the outside into Excel though. So two other ideas are to make it an add-in (https://github.com/ZoomerAnalytics/xlwings/issues/153) and to provide a command to copy the VBA code into the clipboard so that it can be simply pasted into an existing file.
