### ISSUE TITLE
DLL not found when running setup.py manually

### ISSUE THREAD

**Issue by pspramod123** [ZoomerAnalytics/xlwings#126]
trying to install on windows. when i run the setup.py install, i am getting an error message 
"error: can't copy 'xlwings32.dll': doesn't exist or not a regular file"
i have installed Anaconda (and also pywin32)

**Comment by cfkanesan** [comment]
Running `pip install .` from the source folder does not solve the problem.

**Comment by fzumstein** [comment]
you need to do `pip install xlwings-0.10.4.tar.gz` for local pip install if you can't use `pip install xlwings`. Don't unzip the package.
