### ISSUE TITLE
Range.number_format method not working (AttributeError)

### ISSUE THREAD

**Issue by ntdef** [ZoomerAnalytics/xlwings#130]
I get an attribute error every time I try to get the number_format from a Range.

Doing... 

    wb = Workbook()
    Range('A1').value = 2.03
    Range('A1').number_format  = '0.00%'
    Range('A1').number_format

...returns...

    AttributeError                            Traceback (most recent call last)
    <ipython-input-191-4eea412a01dd> in <module>()
    ----> 1 Range('A1').number_format

    AttributeError: 'Range' object has no attribute 'number_format'

**Comment by fzumstein** [comment]
Can you give me a little more details? Mac/Win, Version of Python, xlwings, Excel? Is this the whole Traceback? Is it the same if you try it in a terminal/command prompt instead of IPython?

**Comment by fzumstein** [comment]
I am closing this issue due to no follow-up. Feel free to reopen or let me know how you resolved the issue.

**Comment by ntdef** [comment]
I was using an old version of xlwings. This one is good to close.

**Comment by fzumstein** [comment]
Ok great, kind of suspected that ;-)
