### ISSUE TITLE
Range.hyperlink fails if the Hyperlink has been set with the cell formula

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#132]
Range.hyperlink only works if the link has been set programmatically, not when it it set with the `=HYPERLINK()` formula.

**Comment by fzumstein** [comment]
Something like this will work:
```
import re
formula = Range('A1').formula
hyperlink = re.findall(r'\"(.+?)\"', forumula)[0]
```

**Comment by Bernouilly** [comment]
This solution raise in new problem, though:
a formula containing a string (from a MATCH or a LOOKUP) will be interpreted as an hyperlink
The re should test the presence of 'HYPERLINK' instead.

**Comment by fzumstein** [comment]
matching `hyperlink` is an issue because of non-english versions. How is your cell formula or could you attach a small example please, thanks.
