### ISSUE TITLE
Allow to run VBA macros

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#134]
Win: `app.xl_app.Run("Macro1")` ==> use this syntax for xlwings
Mac: `app.xl_app.run_VB_macro('run_test.xlsm!Module1.test2')`

**Comment by rea725** [comment]
If I could vote for an enhancement, this one would be high on the list :)

**Comment by fzumstein** [comment]
Guess what: you *can* actually vote: https://zoomeranalytics.uservoice.com/
