### ISSUE TITLE
install error on Python 2.7.5 osx 10.9.1

### ISSUE THREAD

**Issue by jnuc093** [ZoomerAnalytics/xlwings#147]
➜  ~  pip install xlwings
Downloading/unpacking xlwings
  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239  Downloading xlwings-0.3.2.tar.gz (239Kb): 239Kb downloaded
  Running setup.py egg_info for package xlwings
    /Users/qk/build/xlwings/setup.py:7: Warning: 'with' will become a reserved keyword in Python 2.6
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/Users/qk/build/xlwings/setup.py", line 7
        with open(os.path.join(os.path.dirname(__file__), 'README.rst')) as f:
                ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    /Users/qk/build/xlwings/setup.py:7: Warning: 'with' will become a reserved keyword in Python 2.6

Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/Users/qk/build/xlwings/setup.py", line 7

    with open(os.path.join(os.path.dirname(__file__), 'README.rst')) as f:

            ^

SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /Users/qk/build/xlwings
Storing complete log in /Users/qk/Library/Logs/pip.log

and my python version is 

➜  ~  python
Python 2.7.5 (default, Sep 12 2013, 21:33:34) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by fzumstein** [comment]
Can you do `which pip` ? is it the same path as you get when you do `which python`? The error messages you get seem to come from a Python version < 2.6 (which xlwings doesn't support), so my guess is that pip is not targeting your python 2.7.5

**Comment by jnuc093** [comment]
➜  ~  which pip
/usr/local/bin/pip
➜  ~  which python
/usr/bin/python

**Comment by fzumstein** [comment]
yeah, so this is exactly the problem. `pip` ist targeting a different python version than `python`. To resolve, you should probably make sure that pip is installed on `/usr/bin/python` or you can try to install xlwings from source: download the package, unpack, cd into the xlwings folder and do: `python setup.py install`. However, maybe it's easier to go with a distribution like Anaconda...

**Comment by jnuc093** [comment]
➜  ~  pip --version
pip 1.1 from /Library/Python/2.5/site-packages/pip-1.1-py2.5.egg (python 2.5)

maybe here is the wrong

**Comment by fzumstein** [comment]
right...you need to find a way to install it into a python distribution >= 2.6. Again...it's usually easiest to just leave the system installations alone and work with an own installation like Anaconda.

**Comment by jnuc093** [comment]
i have installed Anaconda and clone the xlwings and run 

➜  xlwings git:(master) sudo python setup.py install
Password:
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /Library/Python/2.7/site-packages/xlwings-0.3.3dev-py2.7.egg-info
Writing /Library/Python/2.7/site-packages/xlwings-0.3.3dev-py2.7.egg-info

**Comment by fzumstein** [comment]
If you have Anaconda installed, you can just run `pip install xlwings`, or `conda install xlwings`. There's no need to clone from GitHub. What I meant before was to download the package from PyPI (not GitHub), extract it and run `python setup.py install` from there. But with Anaconda, this is not necessary anymore.

**Comment by jnuc093** [comment]
conda install xlwings is OK .thank u very much!
