### ISSUE TITLE
Debugging Documentation

### ISSUE THREAD

**Issue by rolbur** [ZoomerAnalytics/xlwings#148]
In the debugging documentation it says to add this in the python script:

```
if __name__ == '__main__':
    # To run from Python, not needed when called from Excel.
    # Expects the Excel file next to this source file, adjust accordingly.
    path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'myfile.xlsm'))
    Workbook.set_mock_caller(path)
    my_macro()
```

in order for me to work (running the python script from IDLE), i had to add 
`__file__ = sys.argv[0]`
otherwise i got an error saying that `__file__` is not defined.

Do you think it is just an issue with IDLE or should the line `__file__ = sys.argv[0]` be added to the debugging documentation? (could be useful because it took me about one hour to figure out whats wrong)

BR,
Roland

**Comment by rolbur** [comment]
sorry, all the bold words should have two underlines before and after...

**Comment by fzumstein** [comment]
This looks like an (old) IDLE bug: http://bugs.python.org/issue8515. Updating IDLE (or switching to a different IDE...) should resolve that.

**Comment by rolbur** [comment]
you are right! running the same code with Spyder gives me no error!
