### ISSUE TITLE
Any issues with adding visible parameter to Workbook init?

### ISSUE THREAD

**Issue by TFenby** [ZoomerAnalytics/xlwings#149]
I'm looking to use this for processing data in the background, and opening a workbook then immediately setting it as not visible is ugly. Any issue with adding visible=True to Workbook's init parameters, then passing that on to the various *_workbook functions?

**Comment by fzumstein** [comment]
What are you trying to do exactly? If you are just reading in data, packages like `xlrd` or `openpyxl` might be a better choice?

**Comment by TFenby** [comment]
Tried with both of those before, and they borked my formatting. This is the only one I've found that accesses Excel through COM and so doesn't have that concern.

**Comment by fzumstein** [comment]
I see... I can't tell you upfront if this is going to work or not...but this headless question has come up before (https://twitter.com/rbose85/status/522877928711802880) ... so might be worth looking into it

**Comment by TFenby** [comment]
It'd be a really simple matter to add, as long as there isn't any logic elsewhere that requires that it be visible. One such example of where that's not the case is here: https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/_xlwindows.py#L88

**Comment by fzumstein** [comment]
OK, yeah makes sense. I know you don't want to hide it after it's being shown, but still - maybe as a workaround you can do `wb.xl_workbook.Application.Visible = False` - it might help you test things out?

**Comment by TFenby** [comment]
Yeah, that's what I've been doing and it works perfectly fine. It's just ugly. I'll throw up a PR for this functionality in a sec.

**Comment by TFenby** [comment]
So I don't have a Mac to test the OSX implementation of this, but it's working fine on Windows. Looks like visibility control is an option of appscript, though. That something you can take care of?

**Comment by fzumstein** [comment]
sure, but it could take a few days until I can get to it

Am Mittwoch, 11. Februar 2015 schrieb Tyler :
