### ISSUE TITLE
Tox fails to run on Windows due to tox.ini deps

### ISSUE THREAD

**Issue by TFenby** [ZoomerAnalytics/xlwings#150]
As the subject says. Can't compile appscript on Windows due to missing Carbon headers.

**Comment by TFenby** [comment]
Tox config just seems to be broken on Windows in general. Need a way to copy in win32api since it can't be installed w/ pip. I'll look into it.

**Comment by fzumstein** [comment]
I use tox only on Mac as I had troubles making it work on Windows with numpy/pandas/win32 dependencies - use `runtests.py` for windows - I can push a zipfile online for downlaoding that contains all python versions with dependencies later.

**Comment by TFenby** [comment]
Ah, didn't even see it. I'll still look into getting Tox to work since I like it.

**Comment by fzumstein** [comment]
I agree - but I coulnd't make it work last time I tried - although I think in theory it should be possible using wheels or something...

**Comment by fzumstein** [comment]
Anyhow - if you'd still wanted to try out `runtests.py` in the meantime, you can download the zip file with all fully done environments here: https://www.dropbox.com/s/wlftlcryb411t9b/xlwings_python_test_installations.7z?dl=0

**Comment by TFenby** [comment]
pypiwin32 + setuputils>=0.8 in tox gets it working. Excel popping up during the tests is annoying, but that can be addressed by #149

**Comment by fzumstein** [comment]
what about numpy and pandas?

**Comment by TFenby** [comment]
Both install w/ pip just fine

**Comment by fzumstein** [comment]
cool will look into it again

**Comment by TFenby** [comment]
I'm just about done w/ this, then I can take care of #149

**Comment by TFenby** [comment]
One last thing on this: Tox doesn't have enough logic in its config file to depend on different things depending on the OS. Probably the cleanest thing to do would integrate it w/ setup.py (http://tox.readthedocs.org/en/latest/example/basic.html#integration-with-setuptools-distribute-test-commands). Then for OSX and Windows you just run `setup.py` tox or `setup.py test`. That sound ok?

**Comment by TFenby** [comment]
Actually, you might be able to reference requirements.txt from tox.ini, then have that refer to setup.py if you'd prefer to keep running tox w/ the tox command.

**Comment by TFenby** [comment]
#151

**Comment by fzumstein** [comment]
Closing this as I replaced the testing setup with conda envs.
