### ISSUE TITLE
Make an Excel Add-in

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#153]
May just be a matter of replacing `ThisWorkbook` with `ActiveWorkbook`. See also: http://stackoverflow.com/questions/28521702/when-excel-addin-runs-runpython-workbook-caller-raise-an-error

**Comment by acommendador** [comment]
We are experiencing a similar issue. Adding the xlwings.bas module to an Excel add-in then using the add-in with optimized connection set to true cause both Workbook.caller() and Workbook.current() to fail.  Moreover, since the python code can't get a handle to the hidden add-in workbook we cannot invoke wb.application.quit() to terminate the com server. As a result the EXCEL32 and pythonw process are orphaned when the Excel GUI exits and must be killed manually.

**Comment by fzumstein** [comment]
Did you replace `ThisWorkbook` with `ActiveWorkbook` when using as an add-in?

**Comment by acommendador** [comment]
Replacing all instances of <code>ThisWorkbook</code> with <code>ActiveWorkbook</code> within the xlwings.bas does seem to fix the errors when using <code>Workbook.caller()</code> and <code>Workbook.current()</code>.  That said, I've found a workaround that seems to work without modifying the xlwings.bas: pass in the full name of the user's workbook to the python function and use <code>Workbook(fullname=users_workbook_name)</code> to get a handle to the user's workbook.
Neither fix resolves the issue with the orphaned EXCEL32 and pythonw processes when using the optimized connection.  I'll add a new issue for that problem.

**Comment by acommendador** [comment]
This enhancement should allow access to both the user and the add-in workbook.  Replacing all instances of <code>ThisWorkbook</code> with <code>ActiveWorkbook</code> within the xlwings.bas only allows access to the user workbook.

**Comment by petobens** [comment]
Hi @fzumstein (and @acommendador)  I've discovered xlwings today and I think it is great. I have one question though. If I want to call python from excel then every time I open a new excel file I have to do?

>To make this run, just import the VBA module xlwings.bas in the VBA editor (Open the VBA editor with Alt-F11, then go to File > Import File... and import the xlwings.bas file. )

The way to "automatize" this process would be to transform the VBA module into an add-in which then is loaded just once through the VBA Editor `Tools -> References`? If that's the case (i.e if I understood properly) then +1 for the add-in idea.

Once again for creating/maintaining such a great tool.

**Comment by fzumstein** [comment]
Hi @petobens, you understood everything correctly, and making an add-in out of the VBA module is a priority (but has been for a while ;-)

**Comment by petobens** [comment]
Thanks @fzumstein for the quick reply. Unfortunately I don't have the skills to implement the addin myself but I really hope to see it working someday (since it is definitely a nice/needed feature).

Once again thanks for creating/maintaining xlwings.

**Comment by fzumstein** [comment]
To be continued in #301
