### ISSUE TITLE
Named range independent of sheets

### ISSUE THREAD

**Issue by petrushy** [ZoomerAnalytics/xlwings#156]
It seems like the named ranges in Excel is including the sheet information. In xlwings the sheet needs to be specified (or be on firs/active page) now, could this instead use the sheet information in the excel named range definition?

Many thanks

**Comment by fzumstein** [comment]
Could you give me a concrete example of how the behavior seems to differ between VBA and xlwings?

**Comment by petrushy** [comment]
Hi,

I'm not using VBA, so maybe it's there the difference is, but when I look in excel on the defined names I get the following:
![capture](https://cloud.githubusercontent.com/assets/846232/6318353/b6aef576-ba8d-11e4-8cde-17ca9cf4a48f.PNG)
(maybe a bad example as all the named ranges are on same sheet (System))

Also selecting them from the excel pop-up highlight the cell in correct sheet.

Not used to VBA but maybe this is the same problem:
http://stackoverflow.com/questions/8128092/get-sheet-name-from-a-named-ranges-name-object

**Comment by petrushy** [comment]
I guess this is related as well, accessing the range via the Workbook instead of sheet:
http://www.bettersolutions.com/excel/EFC133/LF926361312.htm

**Comment by fzumstein** [comment]
thanks for the all the infos - I will need to look into it.

**Comment by fzumstein** [comment]
I am closing this as it is the same as #256
