### ISSUE TITLE
Add Application.calculation

### ISSUE THREAD

**Issue by willu47** [ZoomerAnalytics/xlwings#158]
I am running a series of simulations in Excel, and need to write, and then read a bunch of cells within a Python loop.

Currently, when writing data to Excel using `Range('Sheetname', (row, col)).value = new_value`, the worksheet recalculates each time.

Is there anyway to turn off sheet calculation until all the writes have been made, then calculate once?

**Comment by fzumstein** [comment]
I am just currently implementing the Application class, so that would fit in there... Chances are that it ll make it into the next release :)

**Comment by willu47** [comment]
Great!

**Comment by fzumstein** [comment]
Other than that you can do the following for a quick workaround until it's implemented:
```
wb = Workbook()
wb.xl_app.ScreenUpdating = False
```

**Comment by fzumstein** [comment]
sorry you wanted `Calculation` not `ScreenUpdating`

**Comment by fzumstein** [comment]
so you could do:
```
In[5]: from xlwings import Calculation
In[6]: wb.xl_app.Calculation =Calculation.xlCalculationManual
In[7]: Range('A1').value = 1
In[8]: wb.xl_app.Calculation = Calculation.xlCalculationAutomatic
```

**Comment by willu47** [comment]
That's perfect.  A huge speed up!  Thanks so much ;)
