### ISSUE TITLE
Documentation needs?

### ISSUE THREAD

**Issue by ntdef** [ZoomerAnalytics/xlwings#165]
While I think the documentation at docs.xlwings.org is pretty good, are there any holes where I can help out with expanding the documentation?

**Comment by fzumstein** [comment]
Well I think there's two things you can do: Try to remember which parts of the library were most unintuitive for you when you got started and try to write docs for these parts. Or, search for the `docs` tag on the issues, especially: https://github.com/ZoomerAnalytics/xlwings/issues/56

**Comment by ntdef** [comment]
Great! I'll look into those. I've been going through the `bug` tag trying to find places where I can help out. I think this package is great and I really want to help contribute.
