### ISSUE TITLE
Mac: Allow to target various installations of Excel (e.g. 2011/2016)

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#169]
It should probably be easy to resolve (for now you could try to replace `app('Microsoft Excel')` in `_xlmac.py` with the actual path to Excel): Something like: `app('/Applications/Microsoft Office 2011/Microsoft Excel.app')`

**Comment by clemensmeyer** [comment]
Yep, I just tried it and it works like a charm! Might make sense in general to put the application name/path in a variable, as it's used quite a few times.

**Comment by fzumstein** [comment]
Closed by 58ffba76c33777c261a89602966d36bd42626f6a

**Comment by pjdw** [comment]
I replaced app('Micro . . with app('fullpath xl 2011 in _xlmac.py, but when running i get:
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    wb = Workbook()
  File "/Users/PdW/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/xlwings/main.py", line 141, in __init__
    self.xl_app, self.xl_workbook = xlplatform.new_workbook()
  File "/Users/PdW/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/xlwings/_xlmac.py", line 119, in new_workbook
    xl_workbook = xl_app.workbooks[1]
  File "/Users/PdW/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/aeosa/appscript/reference.py", line 579, in __getattr__
    raise AttributeError("Unknown property, element or command: %r" % name)
AttributeError: Unknown property, element or command: 'workbooks'
>>> 
Can somebody help?

**Comment by fzumstein** [comment]
You probably haven't replaced it in all places and so it tries to talk to Excel 2016 which is not supported with 0.3.5. You may want to have a look into the (unstable) `develop` branch where you have the possibility to specify things in `Workbook(app_target='/Path/to/Excel.app')`. But it's not implemented yet for when you call it from Excel.

I hope to release 0.3.6 pretty soon with app_target and Excel 2016 support...

**Comment by pjdw** [comment]
Thanks a lot for advice; i got it running.
Keep put the good work. Cheers, Pieter
