### ISSUE TITLE
Mac: Excel 2016 compatibility

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#170]
appscript doesn't work with 2016 out of the box, see: http://lists.apple.com/archives/applescript-users/2015/Mar/msg00114.html

**Comment by fzumstein** [comment]
Using a static glue from Office 2011 seems to work fine: http://lists.apple.com/archives/applescript-users/2015/Mar/msg00290.html  

```
>>> from appscript.terminology import dump
>>> dump('Microsoft Excel', '/path/to/myappglue.py')

>>> import myappglue
>>> from appscript import app
>>> app = app('Microsoft Excel', terms=myappglue)
```

but there's issues in AppleScript with path names and saving:

```
tell application "Microsoft Excel"
	get full name of active workbook
end tell
```

returns:

```
"/Users/Felix/Library/Containers/com.microsoft.Excel/Data/Desktop/Workbook3.xlsx"
```

may be connected with the savings issue... and  may be fixed using `os.path.realpath()` ?

**Comment by fzumstein** [comment]
- [ ] app_visible = False doesn't work
- [ ] saving doesnt work (AppleScript issue)

**Comment by zefyrr** [comment]
Why is this issue closed? It still is an issue, no?

**Comment by fzumstein** [comment]
What you are referring to is covered in #206. This one is only from python to Excel.
