### ISSUE TITLE
Click a button 'Update', 'Don't Update, 'Cancel' button while opening a workbook

### ISSUE THREAD

**Issue by lazarus-zamenhof** [ZoomerAnalytics/xlwings#172]
Some workbooks require a manual intervention during opening. The user has to click either 'Update', 'Don't update' or 'Cancel' button. This usually stops the automation script from executing. It would be desirable if the user could set a default behavior to perform.

![image](https://cloud.githubusercontent.com/assets/9486308/6827433/a981ce68-d307-11e4-9146-cbe2ea8276aa.png)

`wb = Workbook('C:\Worbooks\MyWorkbook.xlsx', action='u')`

By passing the parameter xlwings would open a workbook and click 'Update' in case the window pops up.

**Comment by fzumstein** [comment]
Could you attach a screenshot please?

**Comment by lazarus-zamenhof** [comment]
I have updated the main message.

**Comment by damcedami** [comment]
That warning will not occur if excel is not opened as window, as a workaround you can use `Workbook(app_visible=False)`, so your automation will not stop.

**Comment by fzumstein** [comment]
with upcoming v0.9.0 you should be able to use `app.display_alerts = False`
