### ISSUE TITLE
Mac: When writing to locked cell, xlwings doesn't give error message

### ISSUE THREAD

**Issue by dauledk** [ZoomerAnalytics/xlwings#175]
A1 is a locked cell. 

When I do a Range(1, "A1").value = 5, no error message is given, but the value has not been set to 5. It would be great if you could do something like:

Range(1 , "A1").unprotect(passwd=****).value = 5

Sorry if this is already mentioned, or if I'm using the wrong tags (its my first issue on github). 
And btw thanks for a ultra nice python-excel-mac module!

Brgds, from a small bar in Copenhagen already implementing xlwings :)

**Comment by fzumstein** [comment]
Hi - good catch, but the reason for the unshown error is AppleScript, through which xlwings is accessing Excel and changing AppleScript's behaviour is outside of my power...

Will need to look into the unprotect method...

Looking forward to get an xlwings powered beer ;-)

**Comment by dauledk** [comment]
Ok. 

Maybe the best workaround then would be to create  a macro in VBA that unprotects all sheets? Then the next question is if it is possible to run a macro from xlwings?

You just give me a heads up, then you are very welcome ;)

**Comment by fzumstein** [comment]
There's an open issue for running VBA macros: #134

However, (un)protecting Sheets should really be implemented in xlwings directly. I've opened an issue for this here: #177
