### ISSUE TITLE
Save a Python list to excel in a vertical way

### ISSUE THREAD

**Issue by lazarus-zamenhof** [ZoomerAnalytics/xlwings#178]
`my_list = ['a','b','c']`
`Range('sh', 'A1').value = my_list `

This would populate cells like this:

A1| B2 | C2
------------ | ------------- | -------------
a | b | c

It would be nice if you could choose a vertical orientation to save lists like this.

A1| a
------------ | -------------
A2 | b
A3 | c

Eg. `Range('sh', 'A1', orientation='vertical').value = l`

or 

`Range('sh', 'A1').value(orientation='vertical') = l`

Also, I'm not sure what is rationale behind the current default behavior of saving horizontally but it seems to me more intuitive to store lists in Excel verically rather horizontally.

Eg. You would rather have a list o banks in the screadsheet like this

Name | IBAN
------------ | -------------
UBS | xxx
Credit Suisse | yyy

rather than like this.

Name | UBS | Credit Suisse
------------ | ------------- | -------------
IBAN | xxx | yyy

**Comment by fzumstein** [comment]
Hi, this is actually a duplicate: #11, please see there for a relatively easy workaround with `zip` (and `list`) for now. Visually, it's certainly more intuitive the way it's currently implemented, especially in the form of numpy arrays:

```
>>> import numpy as np
>>> lst = [1,2,3,4]
>>> np.array(lst)
array([1, 2, 3, 4])
>>> np.array(lst)[:,np.newaxis]
array([[1],
       [2],
       [3],
       [4]])
```
