### ISSUE TITLE
xlwings Workbook() call returns AttributeError: Open.Application

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#179]
see: http://stackoverflow.com/questions/29349050/xlwings-workbook-call-returns-attributeerror-open-application?noredirect=1#comment46997274_29349050

**Comment by damcedami** [comment]
I'm also experienced this bug, same as the author of SO thread. I also try @fzumstein advice and got `<COMObject Excel.Application>` as return value, either `Workbook()` working or not.

Strangely enough, if I stop `EXCEL.EXE` process from Task Manager, open the excel file manually by double clicking, close the excel file manually, then run `Workbook()` it's works again, I'll gladly provide any information needed.

Windows 7 64 bit, Python 2.7 (Anaconda distribution, IPython Notebook), Excel 2013.

**Comment by fzumstein** [comment]
thanks for the hint, @damcedami ! what about if you leave out any open/closing of the Excel file in between? Just force `EXCEL.EXE` to quit from the Task Manager, then do `Workbok()`? Does it work then, too?

**Comment by damcedami** [comment]
Hmm..strange, when I do `Workbook()` then I edit cell directly (not through xlwings) and left the cursor open, then I do `Workbook()` again, the bug occurred. What I mean about left the cursor open, it's like when you double click a cell then you edit it but not press enter or tab, so the cursor still blinking in the cell.

In that way I can produce the bug, hope I explained it clearly.

**Comment by damcedami** [comment]
My apologize, from my previous comment, what I did, produce different error, it's not `AttributeError: Open.Application` but `AttributeError: Excel.Application.Workbooks`.

As for @fzumstein suggestion, yes, I produce same error, only happen when I force end `EXCEL.EXE` process from Task Manager, after that I have to close Python completely (in my case, need to create new IPython Notebook) for `Workbook()` work again.

Also, I have slightly different error message from original post at SO thread, if he by simply calling `Workbook()` produce `AttributeError: Open.Application`, but in my case it produce `AttributeError: Add.Application` and I can only produce `AttributeError: Open.Application` when I open an existing Excel file like `Workbook($file)`, and again, all that message happen when I forcefully end `EXCEL.EXE` process.

**Comment by acommendador** [comment]
We're experiencing a similar problem when using Workbook(fullname=<workbook_name>). The stack trace is:

<pre>Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Local\Continuum\Miniconda3\lib\site-packages\my_test.py", line 164, in get_data
    wb = Workbook(fullname=workbook)
  File "C:\Users\myuser\AppData\Local\Continuum\Miniconda3\lib\site-packages\xlwings\main.py", line 135, in __init__
    self.xl_app, self.xl_workbook = xlplatform.get_workbook(self.fullname)
  File "C:\Users\myuser\AppData\Local\Continuum\Miniconda3\lib\site-packages\xlwings\_xlwindows.py", line 53, in get_workbook
    xl_app = xl_workbook.Application
  File "C:\Users\myuser\AppData\Local\Continuum\Miniconda3\lib\site-packages\win32com\client\dynamic.py", line 522, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: Book2.Application
</pre>

Once we start getting this error we need to close and reopen the workbook.

**Comment by MyTotoro** [comment]
Experiencing something similar.

VBA Code:
```
Function G(a As String, b As String, c As String, d As String) As String
    
    addy = Application.Caller.Address
    s = "import abc; abc.G('" & CStr(addy)
    s = s & "','" & a
    s = s & "','" & b
    s = s & "','" & c
    s = s & "','"
    s = s & d
    s = s & "')"

    RunPython (s)

End Function
```

Error that I get is:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\username\PycharmProjects\abc.py", line 282, in G
    wb = Workbook.caller()
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\xlwings\main.py", line 183, in caller
    return cls(xl_workbook=xl_workbook)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\xlwings\main.py", line 130, in __init__
    self.xl_app = xlplatform.get_app(self.xl_workbook)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\xlwings\_xlwindows.py", line 78, in get_app
    return xl_workbook.Application
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\win32com\client\dynamic.py", line 522, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: c:\users\username\aaa.xlsm.Application
```

I've removed some strings in the directory 

Version info:
```
2.7.9 Anaconda 2.2.0
0.3.1 xlwings
Excel 12.0 (2007)
```

**Comment by fzumstein** [comment]
@MyTotoro any chance you can upgrade to 0.3.5 and see if that helps?

**Comment by MyTotoro** [comment]
I actually downgraded to 0.3.1 to test, had the same problem with 0.3.5

```
Sub Wrapper(a As String)
    RunPython ("import abc; abc.rand_numbers()")
End Sub

Function asdf()
Call Wrapper("123")
End Function
```

will break the code, but 

```
Sub Wrapper()
    RunPython ("import abc; abc.rand_numbers()")
End Sub
```

Will not

**Comment by fzumstein** [comment]
Ok that's interesting...I will look into that. however, in general, if you want to do functions, you should have a look a the sister project https://github.com/ericremoreynolds/excelpython

**Comment by MyTotoro** [comment]
Yeah I looked at it, your project had support for Pandas... which is a deal breaker, keep up the good work, this project has potential

**Comment by fzumstein** [comment]
@acommendador xlwings hasn't been built with having multiprocessing/threading in mind, so this behavior is kind of expected. I've opened an specific issue though ( #199) since this topic has come up a few times now...

**Comment by fzumstein** [comment]
Closing this issue as I think it's not relevant anymore with upcoming v0.9.0. please reopen if I am wrong.
