### ISSUE TITLE
Python 3.4 compatability

### ISSUE THREAD

**Issue by fireflydt** [ZoomerAnalytics/xlwings#180]
Is xlwings being upgrade to python 3.4. Example is xlwings use of unicode instead of str.

**Comment by fzumstein** [comment]
Hi, sure, xlwings works with Python 3.4 and unicode. Please report a specific problem if you run into one.

**Comment by fzumstein** [comment]
Hi I guess I also finally understood this issue: This is #161 and will be resolved with the next version.
