### ISSUE TITLE
pip install version is not update yet ?

### ISSUE THREAD

**Issue by zanjibar** [ZoomerAnalytics/xlwings#181]
pip install xlwings  and get a ' unicode error '. Recent version this error fixed ,So when pip version update ?

**Comment by zanjibar** [comment]
pip install xlwings  and get a ' unicode error '. Recent version this error fixed ,So when pip version update ?

**Comment by fzumstein** [comment]
There is currently this bug: #154, i.e. xlwings can't currently deal when you have stored your Excel file under path with unicode characters. Is this the issue that you're facing?

Other than that, make sure you're running the latest version:

```
import xlwings
xlwings.__version__
```

If it is < 0.3.4, then do `pip install --upgrade xlwings`

**Comment by fzumstein** [comment]
You are on Python 3, correct? I think I understand now, you mean this error: #161 which has been fixed on master, but not released yet. Hope to push it out over the next few days!
