### ISSUE TITLE
Column name and row name from get_selection()

### ISSUE THREAD

**Issue by tnagengast** [ZoomerAnalytics/xlwings#182]
When using get_selection() on a cell, is is possible to return the value of the column name and row name? I'm not seeing it in the API documentation.

**Comment by damcedami** [comment]
`get_selection()` return value is Range object, I believe you can use `get_address()` to get column and row name.

**Comment by fzumstein** [comment]
That's right, you can do:

```
>>> import Workbook
>>> wb = Workbook()
>>> wb.get_selection().get_address()
'B4'
```

Once #143 is taken care of, you'll also be able to do `wb.get_selction().row` or `wb.get_selection().column`.

**Comment by tnagengast** [comment]
Worked like a charm - thanks! Looking forward to 143.

**Comment by fzumstein** [comment]
yup - should make it in with the next release or so...
