### ISSUE TITLE
numpy.int32/numpy.int64 are not correctly handled

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#19]
TypeError: Objects of type 'numpy.int32' can not be converted to a COM VARIANT (but obtaining the buffer() of this object could).

Seems to be OK on >=1.8.0, not sure what the real problem is, but converting it using `np.asscalar()` works.

**Comment by fzumstein** [comment]
Same problem with numpy 1.9.1:

```
import pandas as pd
from xlwings import Workbook, Range, Sheet
 
def my_macro():
wb = Workbook.caller()
df = pd.DataFrame({'A':[1,2,3],'B':[1,2,3],'C':['x','y','z'],'D':['x','y','z']})
x = df.describe(include=['object'])
Range('A1').value = x.iloc[3]
 
You may get this error:
 
---------------------------
Error
---------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "X:\02_0170\01_RMPM\04_Risk_Framework\04_Tools and methodologies\Python - OpenCSVpy\loaddf.py", line 30, in my_macro
    Range('Categorical','A1').value = x.iloc[0:4]
  File "C:\Program Files\Euroglot\Python\27\lib\site-packages\xlwings\main.py", line 648, in value
    self.row1, self.col1, row2, col2), data)
  File "C:\Program Files\Euroglot\Python\27\lib\site-packages\xlwings\_xlwindows.py", line 152, in set_value
    xl_range.Value = data
  File "C:\Program Files\Euroglot\Python\27\lib\site-packages\win32com\client\dynamic.py", line 560, in __setattr__
    self._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, value)
TypeError: Objects of type 'numpy.int64' can not be converted to a COM VARIANT (but obtaining the buffer() of this object could)
```

**Comment by fzumstein** [comment]
Run the conversion if:

```
>>> np.result_type(my_array)
dtype('O')  # type Obejct
```

**Comment by Juanlu001** [comment]
Hit today by this. We are trying to provide a self-contained example but it's proving challenging. Any ETA?

**Comment by fzumstein** [comment]
Are you experiencing this on Mac?

**Comment by Juanlu001** [comment]
Windows 7 actually

**Comment by fzumstein** [comment]
weird, I would have expected this to be fixed by this (but on Mac it was missing): https://github.com/ZoomerAnalytics/xlwings/issues/415

what are you getting when you run `type()` on the number that causes the issue? and what issue do you get at all?

**Comment by Juanlu001** [comment]
Thanks to @jmatiasindizen we finally reproduced the issue:

```
from xlwings.udfs import xlfunc
import numpy as np

@xlfunc
def test():
    return np.int64(10)
```

And when using this UDF from Excel we're getting this error: `Unexpected Python Error: TypeError: Objects of type 'numpy.int64' can not be converted to a COM VARIANT (but obtaining the buffer() of this object could)`.
