### ISSUE TITLE
excel & Python files on ONEDRIVE  https://d.docs.live.net/782e... path provided

### ISSUE THREAD

**Issue by patrickcourtot** [ZoomerAnalytics/xlwings#192]
Hi 
I discovered that if a excel file (calling a python) script is located in a ONEDRIVE folder, sometime the call do not work. A blank error message is sent out.

When I move this file and the python script to a other folder like C:\Temp, everything is always OK .

This is because the file path sometimes looks like https://d.docs.live.net/782ea9e4ee2349ed/....

What is strange is that it is not allays the case, but I am not able to identify why and when the "real" path is provided and when the HTTP path is provided by windows. The same file can get the real path or the HTTP path.
Perhaps something to do with GetAbsolutePath Function in the FileSystemObjec ?

Any idea how to get around it?

**Comment by fzumstein** [comment]
See #215
