### ISSUE TITLE
xlwings hangs when using a pandas dataframe with timezone aware datetimeindex

### ISSUE THREAD

**Issue by acommendador** [ZoomerAnalytics/xlwings#195]
Replicate with the following code:
<pre>
from xlwings import Workbook, Range
import pandas as pd
import numpy as np
dt = np.datetime64(1434149887000,'ms')
data_list = np.empty(1, dtype=np.float64)
data_list[:] = 1
dti = pd.DatetimeIndex(data=[dt],tz='GMT')
df = pd.DataFrame(data=data_list, index=dti, columns=['A'])
wb = Workbook()
Range('A1',wkb=wb).value = df
</pre>

The code will work if line <code>dti = pd.DatetimeIndex(data=[dt],tz='GMT')</code> is changed to <code>dti = pd.DatetimeIndex(data=[dt])</code>.

We found that it hangs during the last line of the main.py Range value method: <code>xlplatform.set_value(xlplatform.get_range_from_indices(self.xl_sheet, self.row1, self.col1, row2, col2), data)</code>.

**Comment by fzumstein** [comment]
This happens on Mac, correct?

**Comment by fzumstein** [comment]
Fixed by af128a9085a0b37d797b47a3c90d6a7cb450e57d
