### ISSUE TITLE
problem with same workbook opened in two different Excel instances

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#203]
If the exact same workbook is opened in two different Excel instances, calling xlwings from one of the two will "fail" as xlwings will get back the first excel workbook available in the ROT. Therefore running the python code on the wrong workbook. This leads to weird behavior for the user.

A workable solution to at least detect the issue maybe to pass the Application.Hwnd as 4th argument to python (besides the ["-c", workbook path, "from_xl"] arguments). This would then allow to check in the Workbook.caller() function that the returned workbook wb has wb.xl_app.Hwnd == Hwnd from Excel.

Better would be to get directly the proper workbook (instead of just throwing an error in case of issue as here above) using the window handle of the workbook/excel window (see answer of Peter Thornton in https://social.msdn.microsoft.com/Forums/office/en-US/e3e99712-01a7-483e-bf0e-52bb1f94889c/how-to-use-accessibleobjectfromwindow-api-in-vba-to-get-excel-application-object-from-excel?forum=exceldev for VBA example). But I could not succeed in transforming this code into proper python code to propose a full blown solution under windows.
This approach could also allow to get back the Excel that is the "active" one (using the Hwnd of the caller Excel and the code referenced here above).

**Comment by fzumstein** [comment]
Good catch, I was meant to work on getting the active one over various instances, there's an idea in #30

**Comment by fzumstein** [comment]
Although I guess #30 would still not help, but it would help this other similar issue here: http://stackoverflow.com/questions/31106542/does-xlwings-only-work-with-the-first-instance-of-excel

what is your use case of having the same sheet open 2x?

**Comment by sdementen** [comment]
The use case is the following:
- an excel workbook is used as a GUI to query information from a DB based on criteria in the workbook (the workbook is set a read-only as it is really just a GUI)
- the user opens the workbook 2 times in two excel instances as he/she is working in parallel on two different criteria for queries
- once he/she runs a python script through xlwings, xlwings needs to recover the proper workbook to retrieve the criteria and export the data to the workbook.

==> general user case: Excel workbook used as a GUI. User wants to start 2 times the GUI to work in parallel.

**Comment by fzumstein** [comment]
Ok thanks for the use case... I have a feeling though it's not gonna be easy to make this work...

**Comment by sdementen** [comment]
Where do you spot the complexity here ? Would it lie  in converting the VBA code referenced hereabove into python (it should use comtypes or pythoncom and call the AccessibleObjectFromWindow (this is mine...) ? Or is it somewhere else ?

**Comment by fzumstein** [comment]
no nothing in concrete... it's just that I haven't really seen this approach before. But your input is definitely valuable, I need to look into it. If you happen to make it work in the meantime, let me know!

**Comment by fzumstein** [comment]
Sometimes, things are a whole lot easier: https://github.com/ZoomerAnalytics/xlwings/commit/9a20686df7495a162e402206040d108ef0f4ba87

**Comment by fzumstein** [comment]
Actually, @sdementen this is kind of surprising me that this works as `GetActiveObject` usually only goes against the first instance of Excel. Do you mind testing with master to see if this indeed resolves your issue?

**Comment by fzumstein** [comment]
Hm... I think that was really false alarm :dizzy_face:

**Comment by sdementen** [comment]
@fzumstein, I have tested the solution with the Application.hwnd as arg and it works well to at least identify "buggy" calls (ie when we call xlwings from one workbook and it opens the other (wrong) workbook, xlwings throw an exception).

**Comment by fzumstein** [comment]
great! did you want to open a Pull Request?

**Comment by fzumstein** [comment]
I also just found the source of my confusion: I tested it with `OPTIMIZED_CONNECTION = True` which could also be considered a possible solution then.

**Comment by sdementen** [comment]
If I understood properly, the OPTIMIZED_CONNECTION starts a COM server ...
which AFAIK does not work if the windows machine is lock down (ie no admin
rights)

**Comment by fzumstein** [comment]
`OPTIMIZED_CONNECTION` does indeed start a COM server (of the [ExcelPython](https://github.com/ericremoreynolds/excelpython) project), but it doesn't need admin rights to do so. It's got other issues though, e.g. it currently times out with long running processes.
Anyhow, I've pushed a fix now (develop branch) that does the HWND check to raise an Error in your case.

Unfortunately, I didn't find a way to get a COM object from a HWND with pywin32...

**Comment by sdementen** [comment]
To get back a COM object from a HWND, one must use the Accessibility
API (AccessibleObjectFromWindow)
as described by Peter Thornton in
https://social.msdn.microsoft.com/Forums/office/en-US/e3e99712-01a7-483e-bf0e-52bb1f94889c/how-to-use-accessibleobjectfromwindow-api-in-vba-to-get-excel-application-object-from-excel?forum=exceldev
 . However, the code is in VBA and I did not succeed in converting it to
python (with pywin32 + pythoncom).

Regarding the COM server, I think it needs to change some entries in the
windows registry and the latter may be locked down (my case).

**Comment by fzumstein** [comment]
yup, only that `AccessibleObjectFromWindows` seems not directly available from pywin32.

* `TestObjectFromWindow ` on https://github.com/Travis-Sun/pywin32/blob/f999b364ae8c52b9ccf98e6a3d1220397cb8ebfe/com/win32com/test/testExplorer.py seems to go in that direction, but I couln't make it work neither.
* Another approach is going via `ctypes`: http://forums.devshed.com/python-programming-11/help-ctypes-com-134001.html but I am stuck at the same point as the question in the link

=> what error do you get when running with `OPTIMIZED_CONNECTION`?

**Comment by sdementen** [comment]
When registering any COM server (not xlwings specially as complex to test),
I get:

Traceback (most recent call last):
  File "..."
  File "...\lib\site-packages\win32com\server\register.py", line 589, in
UseCommandLine
    RegisterClasses(*classes, **flags)
  File "...\lib\site-packages\win32com\server\register.py", line 430, in
RegisterClasses
    addPyComCat, dispatcherSpec, clsctx, addnPath)
  File "...\lib\site-packages\win32com\server\register.py", line 184, in
RegisterServer
    _set_string(keyNameRoot, desc)
  File "...\lib\site-packages\win32com\server\register.py", line 32, in
_set_string
    value)
pywintypes.error: (5, 'RegSetValue', 'Access is denied.')

ie the registry is locked down. When starting regedit.exe I also get a
message "Registry editing has been disabled by your administrator" which
looks a rather reasonable decision if you want to have a locked down PC.

**Comment by fzumstein** [comment]
I don't get why is the xlwings COM server complex to test? what happens when you run it with `OPTIMIZED_CONNECTION = True` ?

**Comment by sdementen** [comment]
Indeed, I just opened the fibonacci example to test ... and it worked !
Thank you for pushing me to retest this COM server functionality :-)
Is there one python process started per Excel instance ?

**Comment by fzumstein** [comment]
That's right, yes. But bear in mind that this feature still runs under the header "experimental"...

**Comment by sdementen** [comment]
Could you give the attention points re the use of the optimised mode
(except for the timeout issue) ?
I would like to better understand the "risk" I take if I go down this path

**Comment by fzumstein** [comment]
Well if you forget to put `Workbook.caller()` inside the calling function, then it will not manage to release the Excel process properly once you exit Excel...also, it works a bit different in that it'll not always reload every change to your Python code base as it does with `OPTIMIZED_CONNECTION = False`. See also http://docs.xlwings.org/vba.html .

**Comment by sdementen** [comment]
Is it possible to kill+restart explicitly from excel the python server
running in the background ? in case code is updated (or there are memory
issues : leaks, cache dictionaries growing too far, ...)

**Comment by fzumstein** [comment]
well, currently not, but once we're making an add-in, that should be easy: https://zoomeranalytics.uservoice.com/forums/269851-xlwings/suggestions/9263793-make-an-excel-add-in-instead-of-the-vba-module

**Comment by fzumstein** [comment]
@sdementen I finally implemented a full HWND approach, have a look at the hwnd branch...
