### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by nyobna** [ZoomerAnalytics/xlwings#209]
I'm trying to use xlwings for the first time. I am using Ipython with Anaconda installed. I tried the following very simple code:

from xlwings import Workbook, Range
wb= Workbook()
Range('A1').Value = 1000

A new excel instance is open but nothing else happens. When I write 1000 manually and try the following:

Range('A1').Value

I get an error:

AttributeError                            Traceback (most recent call last)
<ipython-input-3-45058eab6df0> in <module>()
----> 1 Range('A1').Value

AttributeError: 'Range' object has no attribute 'Value'

Is it a version error? Can't see what I'm doing wrong?? The simulation example seemed to work as well. Thanks!!

**Comment by fzumstein** [comment]
Python and therefore xlwings uses lower case letters for attributes by convention, so while your syntax will work in VBA, for xlwings you need to change `value` into lower case: `Range('A1').Value`

**Comment by nyobna** [comment]
Wow, I'm such an idiot. Thank you so much! I would have wasted hours and hours figuring that out! Great great product, really looking forward to playing with this!

**Comment by aman0221** [comment]
why Range('A1').vertical is not working

**Comment by fzumstein** [comment]
vertical is long gone, use `myrange.expand('down')`, see: https://docs.xlwings.org/en/stable/datastructures.html#range-expanding
