### ISSUE TITLE
Update template: issue if path to python PYTHON_WIN starts with a lowercap letter (e.g. "c:\" instead of "C:\")

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#234]
In the excel template, if one uses in the PYTHON_WIN a path starting with lowercap the DriveCommand variable is not set proprerly.
The [A-Z] range should be extended to [A-Za-z] in code below in ExecuteWindows

    If Left$(PYTHON_WIN, 2) Like "[A-Z]:" Then
        ' If Python is installed on a mapped or local drive, change to drive, then cd to path
        DriveCommand = Left$(PYTHON_WIN, 2) & " & cd " & PYTHON_WIN & " & "

I can do a pull request by not sure if the diff on the excel template will make any sense.

**Comment by fzumstein** [comment]
Oooh I totally forgot to update the template! This has already been fixed her: https://github.com/ZoomerAnalytics/xlwings/pull/214 so just take the `xlwings.bas` file from the installation directory and replace it manually.... but I am about to make a new release today so will fix that!
