### ISSUE TITLE
list index out of range due to missing 4th argument

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#235]
The following traceback appears sometimes.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "...\mymodule.py", line 7, in rand_numbers
    wb = Workbook.caller()  # Creates a reference to the calling Excel file
  File "...\lib\site-packages\xlwings\main.py", line 195, in caller
    xl_app, xl_workbook = xlplatform.get_open_workbook(fullname, hwnd=sys.argv[4])
IndexError: list index out of range

It is probably a typo in the python code (should it be sys.argv[3] ?)  but there may be also some missing code in the VBA code. In the ExecuteWindows function, the line

                   """" & WORKBOOK_FULLNAME & """ ""from_xl"" 2> """ & LOG_FILE & """ ", _

should probably replaced by

                   """" & WORKBOOK_FULLNAME & """ ""from_xl"" " & Application.Hwnd & " 2> """ & LOG_FILE & """ ", _

**Comment by fzumstein** [comment]
Same comment as with #234 - just upgrade to the latest xlwings.bas file from the installation directory. I am closing this issue as it's really the same as #234.

**Comment by sdementen** [comment]
It works like a charm now (multiple instances, same file, read-only files, sharepoint files,  etc) ! 
thanks for this excellent release !

as you may see from the other issue, I am investigating the OPTIMIZED_CONNECTION flag...

**Comment by fzumstein** [comment]
Well, thanks for pushing so hard for the HWND approach! Oh, it even does resolve the sharepoint/onedrive file issues, excellent! I wasn't even thinking about that but it makes perfect sense...
