### ISSUE TITLE
OPTIMIZED_CONNECTION=True may lead to ghost processes

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#236]
On 0.4.1 with OPTIMIZED_CONNECTION = True, I call the buggy_function as defined herebelow

    from xlwings import Workbook
    
    app = None
    
    def buggy_functions():
        global app
    
        """ produces standard normally distributed random numbers with shape (n,n)"""
        wb = Workbook.caller()  # Creates a reference to the calling Excel file
        app = wb.xl_app
        #app = None

When I quit Excel, both Excel and the pythonw process stay alive. I must kill Excel in the Windows Task Manager to kill both.

If the last line is uncommented (cancel the global reference to the app), processes are properly killed when exiting Excel.

**Comment by fzumstein** [comment]
Welcome to COM hell. Same effect should happen when you place `wb = Workbook.caller()` outside of the function. For some reason it doesn't manage to garbage collect all the Workbook references correctly and therefore doesn't end the Python process. We haven't found the real reason yet. However, the current workaround of not using a module-wide global with the workbook or app reference seems to work reasonably well.

**Comment by sdementen** [comment]
Indeed, clearing the référence 
Would it be possible to kill the python process before/when closing excel ?
Or check every second from python if app.Visible=true and if not kill python and excel afterwards ?

**Comment by fzumstein** [comment]
we also allow for `app_visible=False`, so that check wouldn't work. Our plans are actually to integrate ExcelPython fully in the near future, so then we'll give it another look for sure. Until then, things stay experimental ;-)

**Comment by sdementen** [comment]
When you say integrate with ExcelPython, what do you have in mind? Use the connection/interface with excel from ExcelPython and use the excel API from xlwings ? If you have a link to some URL talking about this (email thread, wiki page, ...), I'd be interested !

**Comment by fzumstein** [comment]
No formal issue opened right now, but it's mostly about adding support for UDFs - and in fact most of it is already there. What's missing is the developer add-in to be able to import UDFs that are decorated in Python. A few edges need to be ironed out like those you've already spotted and some other things need to be refactored so that e.g. we can use the pandas DataFrame handling for UDFs, too.
