### ISSUE TITLE
VBA module: ReadTextFile fails for sharepoint file path (https://...)

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#247]
So probably, the log file should be placed in a local folder rather than next to the excel file...

**Comment by Vancamjr** [comment]
When using xlwings.bas with a personal macro library (personal.xlsm located in a XLStart folder) a further problem arises.  On startup Excel opens every file in the designated XLStart folder.  Since the log file and python.py files are co-located in this directory we have a problem.

**Comment by fzumstein** [comment]
There have been issues reported with regards to personal.xlsm/XLStart folder: #204 
You should be able to put the python file somewhere else and adjust the PYTHONPATH in the VBA settings accordingly...

**Comment by Vancamjr** [comment]
Thanks, and yes that was my first thought.  Further I planned to create a library of python files in this location to handle various routine chores.  Unfortunately updating PYTHONPATH (pointing to the PyCharm directory for this library) in the VBA was not successful.  

Using the simplest code possible


when the macro is called in Excel I see a screen flicker and a Running… indication (see below)
this suggests something is happening but excel never stops showing Running.. until the application is aborted.
 


I’ve tried every permutation I can think of but so far no luck.

Same story with the fibonacci.xls from the examples folder.

I have no problem going the other way Python3.5 >> Excel  (after import xlwings)

-john

**Comment by fzumstein** [comment]
Your (tweet)[https://twitter.com/Mooniac/status/663082778049671168] is actually very much intelligible: it means that it doesn't find the xlwings package. When called from Excel, it starts the default python installation (the one you invoke by simply typing) `python` at a terminal window. If that is not the one which has xlwings installed, you either need to specify the path to the interpreter via Settings in the VBA module or you need to adjust the path to make your python distribution the default.

**Comment by Vancamjr** [comment]
Thanks, your explanation proved very helpful.  I wasn’t having much luck with the python path then it occurred to me that I could modify the ExecuteMac function as shown below.  Here I change /python to /python3.5 to redirect xlwings to use python 3.5 instead of the default python.  With that simple change everything seems to be working as intended.  

    more...
  ' Transform from MacOS Classic path style (":") and Windows style ("\") to Bash friendly style ("/")
    PYTHONPATH = ToPosixPath(PYTHONPATH)
    LOG_FILE = ToPosixPath(LOG_FILE)
    PythonInterpreter = ToPosixPath(PYTHON_MAC & "/python3.5")
    'PythonInterpreter = ToPosixPath(PYTHON_MAC & "/python")    <== copy of original before changing to python3.5
    WORKBOOK_FULLNAME = ToPosixPath(ThisWorkbook.Path & ":" & ThisWorkbook.Name) 'ThisWorkbook.FullName doesn't handle unicode on Excel 2011

Thanks for your help.

-john

**Comment by fzumstein** [comment]
Hey that's actually kind of a catch here, the python interpreter should be specified including the interpreter itself, not only up to the directory. I have created an own issue #289 for this.

**Comment by fzumstein** [comment]
The log file goes now into `/tmp` on Mac per default.
