### ISSUE TITLE
access application object from Sheet or Range

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#253]
It could be useful to get access to the application object (from xlwings not the xl_app) from a Sheet or a Range object (something like sh.app or sh.application or sh.parent).

(Felix, i will post a couple of small API "enhancement" through github, is it ok for you ? or do you want me to use UserVoice ?)

**Comment by sdementen** [comment]
btw, I can do PR to implement them but I'd like to have opinion/advice before doing so

**Comment by fzumstein** [comment]
Sure, sounds good! And posting them here makes sense, too.

**Comment by sdementen** [comment]
is it possible for me to make an issue as "enhancement" ? or is it only the "owner" of the git repo that can do that ?

**Comment by fzumstein** [comment]
Yeah only the owners can add the `enhancement` label
