### ISSUE TITLE
writing/reading pandas dataframes

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#255]
It could be useful to have a simple way to read/write dataframes from excel with an API similar to:

    df = Range("A1").df(index=True, header=False).value

or

    Range("A1").df(index=True, header=False).value = df

This could be achieved by having some asdataframe keyword argument for the current Range (similar to asarray) as

    Range("A1", asdataframe=True,index=True, header=False).value = df

However, I wonder if it is not better to leave out the Range object as wrapper of the excel Range object and use accessor to read/write to the range object as

    df = Range("A1").df(index=True, header=False).value
    arr = Range("A1").array(atleast2d=True).value
    lst = Range("A1").list(atleast2d=True).value

(the default being list with atleast2d =False) and the same to write data to it (but there atleast2d would not be required as it can be guessed from the input).
For pandas dataframes:
- instead of df, dataframe, data_frame or DataFrame (as in pandas) could be used
- additional arguments could be added (like index_col, parse_cols, etc as in pandas.read_excel and pandas.to_excel).

We can keep the current syntax for backward compatibility with some WarningDeprecated.

Opinions ?

**Comment by fzumstein** [comment]
Is this only thougt to handle non-hierarchical dataframes?

**Comment by sdementen** [comment]
What are hierarchical dataframes ? multiindex dataframes ?

**Comment by sdementen** [comment]
Regarding atleast2d, I wonder now if it is not better to make it an attribute of the range that:
- can be set manually to True
- is set to True if .table is used 
- is set to True if .horizontal and .vertical are used one after the other
- is set to True if a vertical range is extended with .horizontal (or horizontal range is extended with .vertical)

Then this attribute can be used by the "df" and "array" accessors. The list "accessor" is then not necessary anymore (just use the .value)

**Comment by fzumstein** [comment]
Yes, I was referring to multi-index / multi-header dataframes like these:
```
first              bar                 baz                 foo          
second             one       two       one       two       one       two
first second                                                            
bar   one    -0.410001 -0.078638  0.545952 -1.219217 -1.226825  0.769804
      two    -1.281247 -0.727707 -0.121306 -0.097883  0.695775  0.341734
baz   one     0.959726 -1.110336 -0.619976  0.149748 -0.732339  0.687738
      two     0.176444  0.403310 -0.154951  0.301624 -2.179861 -1.369849
foo   one    -0.954208  1.462696 -1.743161 -0.826591 -0.345352  1.314232
      two     0.690579  0.995761  2.396780  0.014871  3.357427 -0.317441
```

**Comment by sdementen** [comment]
My daily use does not involve such dataframes currently but it would be
rather straightforward to support them.
I am working on such changes and will sumbit them to you (hopefully) soon.

On Sunday, October 18, 2015, Felix Zumstein <notifications@github.com>
wrote:
> Yes, I was referring to multi-index / multi-header dataframes like these:
>
> first bar baz foo
> second one two one two one two
> first second
> bar one -0.410001 -0.078638 0.545952 -1.219217 -1.226825 0.769804
> two -1.281247 -0.727707 -0.121306 -0.097883 0.695775 0.341734
> baz one 0.959726 -1.110336 -0.619976 0.149748 -0.732339 0.687738
> two 0.176444 0.403310 -0.154951 0.301624 -2.179861 -1.369849
> foo one -0.954208 1.462696 -1.743161 -0.826591 -0.345352 1.314232
> two 0.690579 0.995761 2.396780 0.014871 3.357427 -0.317441
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/NjqaUylMyE1kC-Ju9EfuQW1SmPyaI-DEm0fuwGAxBZUafob0_xB_0gdG31qYOC3JCljBJNZPU0mRE-9I9qd9CqDiljzJycoT_MHRW0mYnFEkaPzF1n_FUE98cVTFnrPsyf5FQ1A3rBPC3bMuVPyxGj5jaVbnBg=s0-d-e1-ft#https://github.com/notifications/beacon/ABPpdiXBk0166UpPcu2bj_IFCkR2zGe1ks5o85JfgaJpZM4GQkU8.gif
>

**Comment by sdementen** [comment]
The PR #263 is now in a good state to look at.

It supports hierarchical dataframes as well as timezone conversion for DatetimeIndex (when used as index, not columns). Roundtrip df->excel->df should work properly except for the names of columns that is always lost.

I would like to add an extra feature that would allow to register Range dataframe "formats" and attach to them conversion functions as well as default dataframe Accessor arguments.

For instance, one could register a format "pivot_data_sales" that would add some functions to be applied when setting or getting that would transform the data (pandas pivot/unpivot) as

    xlwings.register_format("pivot_data_sales", 
                            get_conversion=function1, 
                            set_conversion=function2)

or register a format "consumption_data" that has 2 index columns (one of which is a DatatimeIndex in timezone "Europe/Brussels" and 3 headers rows as

    xlwings.register_format("consumption_data", index=2, header=3, tz="Europe/Brussels")

Then, one could use a simple

    df = Range("A1").table.dataframe(format="consumption_data").value

equivalent to

    df = Range("A1").table.dataframe(index=2, header=3, tz="Europe/Brussels").value


or    

    Range("A1").table.dataframe(format="pivot_data_sales").value = df

equivalent to

    Range("A1").table.dataframe().value = function2(df)

This feature is quite helpful when reading/writing/rereading/rewrinting/etc data in a workflow to avoid re-encoding the metadata about a range format each time.

Any feedback ?

**Comment by fzumstein** [comment]
closed by PR #381

**Comment by keluc** [comment]
It seems to me that the multiheader case is not resolved yet when there are names associated to the levels in the columns. This is not tackled in the testcases because while the testcase "test_dataframe_multiindex" includes the names for the three levels, the testcase "test_dataframe_multiheader" does not.  A better testcase is:

``` 
df_expected = pd.DataFrame([[0.0, 1.0, 2.0, 3.0, 4.0],
                                    [0.0, 1.0, 2.0, 3.0, 4.0],
                                    [0.0, 1.0, 2.0, 3.0, 4.0],
                                    [0.0, 1.0, 2.0, 3.0, 4.0],
                                    [0.0, 1.0, 2.0, 3.0, 4.0],
                                    [0.0, 1.0, 2.0, 3.0, 4.0]], columns=pd.MultiIndex.from_arrays(header, names=['first','second']))
```
Then you'll notice that for this case the names are not written to excel. I haven't yet found were to fix should be.

![image](https://user-images.githubusercontent.com/1886829/39156495-af59275c-4756-11e8-9b11-4ffac45ddbde.png)

![image](https://user-images.githubusercontent.com/1886829/39156473-8a58f234-4756-11e8-827b-b3a0e043195f.png)

ps. tested it with xlwings 0.11.5 but I think the last 2 versions didn't fix this

**Comment by fzumstein** [comment]
it would be better to open a separate issue for that, thanks.
