### ISSUE TITLE
Range.resize is wrong in case row_size or column_size is None

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#262]
I would expect that

    Range("A1:C5").resize(row_size=1)
would give a range covering "A1:C1" but it gives the range "A1" (ie if column_size=None, it is assumed to be = 1).
In the code of the resize method, the "if row_size" is maybe better covered by a "if row_size is not None" to catch the case where the size=0 (which should be an error I guess) and ditto for the column_size

**Comment by fzumstein** [comment]
Good catch. It's a plain bug, should work the same as in VBA.

**Comment by fzumstein** [comment]
Should have been closed with 0.5.0
