### ISSUE TITLE
Range doesn't preserve kwargs when used with methods/properties that return a Range

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#265]
I see often in the code the structure

        return Range(xlplatform.get_worksheet_name(self.xl_sheet), (self.row1, self.col1), (row2, col2), **self.kwargs)

which create a new Range object based on an existing Range object + change in some attributes (usually row/col).

An issue with this construct is that if one changes attributes like asarray or atleast_2d from elsewhere than in the constructor, it does not preserve it, for example

    rng = Range("A1", atleast_2d=True)
    rng.atleast_2d=False
    print rng.offset(0,0).atleast_2d # ==> print True while I would expect False

This is due to the self.kwargs not being updated after construction.

I wonder if it could not be simpler and more robust to have a "copy" method that would simply copy the Range object as well as a "set" method allowing to have chained setattr.

The code above would look like

        return self.copy().set(row1=self.row1, col1=self.col1, row2=self.row2, col2=self.col2)

The copy would be a simple call to the standard copy.copy method

    def copy(self):
        return copy.copy(self)

and the set would be

    def set(self, **kwargs):
        for k,v in kwargs.iteritems():
            setattr(self, k, v)
        return self

To make it shorted, we could also have a copy that set at the same time

    def copy(self, **kwargs):
        return copy.copy(self).set(**kwargs)

What do you think ?

PS: feel free to tell me if there are issues you want to tackle yourself. I let you know when I start working on some fix anyway to avoid duplicating efforts.

**Comment by fzumstein** [comment]
Why not just pass the arguments explicitly? e.g. in the case of offset:
```
return Range(xlplatform.get_worksheet_name(self.xl_sheet), (row1, col1), (row2, col2), asarray=self.asarray, atleast_2d=self.atleast_2d)
```

**Comment by sdementen** [comment]
It can be done like this indeed ==> we would need to add everywhere a copy of a range is returned this and if we add a new attribute to a range, we must not forget to update all functions accordingly.

Looking at how pandas is doing, I see they also use a copy method when they need to return a new dataframe instead of modifying in place (e.g. https://github.com/pydata/pandas/blob/472e6e0e6de2434a3c79d5ec95d8a11a8ea394b6/pandas/core/frame.py#L2696)

**Comment by sdementen** [comment]
After some reading and thoughts, the Range object appears to be considered an immutable object (except for the underlying data in the Excel Range) and its attributes are not expected to be changed after creation => current code is correct. It took me some time to notice this immutability.
I am closing the issue.
