### ISSUE TITLE
refactoring pd/np

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#266]
I see in the code (main.py) constructs like

        if hasattr(np, 'ndarray') and isinstance(data, np.ndarray):

Isn't it more readable to write:

        if np  is not None and isinstance(data, np.ndarray):

(but not sure if the hasattr construct is not covering more than simply checking the module np or pd has been imported properly)

**Comment by fzumstein** [comment]
I guess you might be right, `hasattr` would only be necessary if I would `pass` on the `ImportError`.

**Comment by fzumstein** [comment]
Closed by f32ad98c42ea6c3feb92c508b8447d1a86203df1
