### ISSUE TITLE
32 bit Excel <--> 64 bit python: Automation error

### ISSUE THREAD

**Issue by AntonioSuriano** [ZoomerAnalytics/xlwings#271]
Today I tested this configuration

Windows 8.1 64 bit
Excel 2013 32 bit
Anaconda python 64 bit (the last)
xlwings 0.4.1
pandas 0.17
numpy 1.10

and I got "Automation error" by xlwings and some more strange messages by Excelpython.

I tried also 
Windows 8.1 64 bit
Excel 2013 32 bit
Anaconda python 32 bit (the last)
xlwings 0.4.1
pandas 0.17
numpy 1.10

and it all worked perfectly.

I don't know if it is xlwings connect or pandas printing or ADO connection because from immediate window print Py.Str(py.eval("1+1")) was fine in 64 bit environment.

By the way there is a lot of stuff that it is difficult to manage in 64 bit python (cython for example).

**Comment by fzumstein** [comment]
Antonio, you need to include more details. What did you do when you got that error? what were the settings, did you try it from excel or python, what's the full stack trace? minimal code sample etc etc. 32 Excel/64 bit Python is the most common combination so I doubt that this is the reason for the error...

**Comment by AntonioSuriano** [comment]
Hi, from Excel to python using the Runpython function.
The function print on a cell a pandas Series. It looks for the series in a dictionary, if it is not present it queries Oracle. So there are many links  that could cause a 32bit-64 bit interface error.

I forgot to test the Runpython ("pass"). 

Tomorrow, if I have time, I'll do it. Anyhow I'll use the 32 bit Python for different reasons.

**Comment by AntonioSuriano** [comment]
Ok, 

the Runpython ("pass") works fine.

There are other components called in my python functions that don't work.
I checked with my IT and they confirm they provided only a 32-bit set of libraries.
