### ISSUE TITLE
Range header argument could also apply to setting a pandas Series

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#276]
In the doc (and the code), the index argument is used for both DataFrame and Series while the header only for DataFrame

    index (boolean, default True) – Includes the index when setting a Pandas DataFrame or Series.
    header (boolean, default True) – Includes the column headers when setting a Pandas DataFrame.

it could be better to also use the header argument when setting Series

**Comment by fzumstein** [comment]
Were you picturing this: 

```
In[33]: pd.Series([1.1, 3.3, 5., np.nan, 6., 8.], name='myseries')
Out[33]: 
0    1.1
1    3.3
2    5.0
3    NaN
4    6.0
5    8.0
Name: myseries, dtype: float64
```

to be shown in Excel as 

```
     myseries
0    1.1
1    3.3
2    5.0
3    NaN
4    6.0
5    8.0
```
in case `header=True`?

**Comment by sdementen** [comment]
Yes but with the name of the index alose in the header

**Comment by sdementen** [comment]
Yes but with the name of the index also in the header

**Comment by sdementen** [comment]
Yes but with the name of the index also in the header

**Comment by sdementen** [comment]
Yes but with the name of the index also in the header

**Comment by fzumstein** [comment]
Makes sense!
