### ISSUE TITLE
Changing of sheets in user interface causes exception

### ISSUE THREAD

**Issue by leaffan** [ZoomerAnalytics/xlwings#280]
I am populating a worksheet 1 with data from an external source. On a separate worksheet 2 in the same workbook I'd like to print diagnostic messages, i.e. to indicate the progress of the process.

This is the main class defined in *excel_export.py*:

    import time
    from xlwings import Workbook, Sheet, Range

    class ExcelExporter(object):
      def __init__(self):
          self.wb = Workbook.caller()
      def do_something(self):
          Range(1, 'A1:A100').clear_contents()
          Range(2, 'A1:A100').clear_contents()
          for i in range(0, 50):
              Range(1, "A%d" % (i + 1)).value = i * 2
              time.sleep(0.1)
              Range(2, "A%d" % (i + 1)).value = "Iteration %d done" % (i + 1)

It is called from the Excel workbook via RunPython using a separate file *app.py*:

    from excel_export import ExcelExporter

    def main():
      ee = ExcelExporter()
      ee.do_something()

Calling code from the workbook is this:

    RunPython ("import app; app.main()")

Without user interaction this works fines. However, when trying to switch between worksheets manually (via the Excel GUI) during the process an exception of the following kind is thrown:

    File "D:\work\****\app.py", line 17, in main
      ee.do_something()
    File "D:\work\****\excel_export.py", line 25, in do_something
      Range(1, "A%d" % (i + 1)).value = i * 2
    File "C:\osgeo4w\apps\Python27\Lib\site-packages\xlwings\main.py", line 866, in value
      self.row1, self.col1, row2, col2), data)
    File "C:\osgeo4w\apps\Python27\Lib\site-packages\xlwings\_xlwindows.py", line 269, in set_value
      xl_range.Value = data
    File "C:\osgeo4w\apps\Python27\Lib\site-packages\win32com\client\dynamic.py", line 560, in __  setattr__
    self._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, value)
      pywintypes.com_error: (-2147352567, 'Ausnahmefehler aufgetreten.', (0, None, None, None, 0, -2146777998), None)

Is this kind of interaction not allowed/possible/encouraged or am I missing something here? (Like somehow making sure that a certain sheet is selected before issuing the command to write data to the range.)

In any way thank you for this great module.

**Comment by fzumstein** [comment]
Yes, COM throws an exception when it cannot write to cells. This happens e.g. when you are manually editing a cell while you try to write to the sheet from outside. So this is indeed expected and you should not manually change it while you write to it from xlwings.
