### ISSUE TITLE
automate update of xlwings VBA code in examples

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#283]
Hello Felix,

I have automated the update of the xlwings module of an XL addin from the text file "xlwings.bas".

Just in case you would like to automate the update of all xlwings examples, you could use something like::

        wb = Workbook("name of the example.xlsm").xl_workbook
        # remove the old xlwings module
        wb.VBProject.VBComponents.Remove(wb.VBProject.VBComponents("xlwings"))
        # import the new one
        wb.VBProject.VBComponents.Import("path\to\xlwings.bas")
        wb.Save()

Nothing you probably did not known or could not find by yourself but as I had it cleanly and tested, I though it could be useful to you.

**Comment by fzumstein** [comment]
thanks for the input!
