### ISSUE TITLE
Unable to use RunFrozenPython

### ISSUE THREAD

**Issue by thomasoconnell** [ZoomerAnalytics/xlwings#288]
Apologies if the format of this comment is not per GitHub standards (I am new to GitHub). I have a project in which I have been using xlwings to call a Python script saved in the same directory ("DataProcessing.py). However, it would be best to provide the executable Python file, rather than having the user download a Python package and other relevant modules. I have used PyInstaller to free the Python script  originally called with RunPython (i.e., 'RunPython ("import DataProcessing")'), and have tried changing the line in VBA calling the script to 'RunFrozenPython  ("import DataProcessing")', 'RunFrozenPython ("DataProcessing")', and 'RunFrozenPython ("DataProcessing.exe")'. I have also tried modifying the settings of the xlwings.bas module included in VBA, to no avail.

Could someone please advise on the syntax required for use of "RunFrozenPython", or what I might be doing wrong? I could not see much direction in the documentation:
https://media.readthedocs.org/pdf/fzumstein/latest/fzumstein.pdf

**Comment by fzumstein** [comment]
`RunFrozenPython("DataProcessing.exe")` is the correct way, as you can check in the VBA module [here](https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/xlwings.bas#L197) or when you have a look at `fibonacci.xlsm` file in the example folder or from the homepage. But you're right, proper documentation is lacking on this feature.
In the end, to get it running, you'll usually want to make sure it runs when calling it from the command line directly (there's a lot that can go wrong with freezing), and when it does, call it through VBA.

**Comment by leonbrave** [comment]
```
hi there, i have a noob question, apologies in advance, but what i trying to do is:

I have a python scrip called test.py and test.py has functions, so on my vba code i called like this :

Pythoncall.task_1
Pythoncall.task_2

on the Pythoncall module i have:


Sub task_1()
RunPython ("import test; test.task_1()")
End Sub

Sub task_2()
RunPython ("import test; test.task_2()")
End Sub

```

so i did the Pyinstaller thing and i have my Test folder "build\test"

can i give arguments to the function i want to run on test.exe ?

i hope i was clear  with the question

**Comment by fzumstein** [comment]
Hi @leonbrave you may want to try this to use arguments: http://stackoverflow.com/a/9497409/918626

**Comment by leonbrave** [comment]
hi there, thanks for comment this, but i will try to explain again, i need to tell to the .exe (frozen) what function i want to run first.

so instead 
RunPython ("import test; test.task_1()")

i want to do the same but using the "frozen" folder and run first the task_1 function first and after that call again the runpython (frozen) and run the task_2 function. :)


thanks in advance

**Comment by fzumstein** [comment]
Have a look at the Database example: There I use `combobox.py` and `playlist.py` to build separate executables

**Comment by leonbrave** [comment]
thanks, i will check :)
