### ISSUE TITLE
Fully integrate ExcelPython

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#296]
- [x] 1 - docs
- [x] 2 - add Example
- [x] 3 - check if mac fails on the decorators, or make it work, respectively
- [x] 4 - replace `dims=2` with `ndim=2`
- [x] 5 - refactor `wb` into `xl_workbook` in `import_udfs` to be consistent with rest
- [x] 6 - fix addin (older xl versions)
- [x] 7 - double-check that xlam.bas file is *not* included in the package
- [x] 8 - optionally add a method/command line call that installs/updates the addin in the XLSTART or AppData/Addins folder? While it will not be updated automatically upon pip install --upgrade, pip install --upgrade on the other hand will fail if Excel is open

**Comment by AntonioSuriano** [comment]
:)
