### ISSUE TITLE
Create a runtime xlwings add-in

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#301]
The xlwings add-in introduced in v0.6.0 is only a developer add-in. Let's turn it into a runtime addin so that the xlwings VBA module is not necessary to run things. 
- Settings:
  global settings and possibility to use workbook specific settings (select with e.g. checkbox/radiobutton). The workbook specific settings should be stored as XML file in the xlsm-Zipfile: https://msdn.microsoft.com/en-us/library/bb608627.aspx
- Button to restart the Python interpreter
- Button to run `xlwings quickstart myproject`
- Alternatively, it should still be possible to add the xlwings VBA module to allow users to run things without the need to install the add-in

**Comment by sdementen** [comment]
How far is this feature ?

**Comment by fzumstein** [comment]
Nothing working committed yet. But it'll be config based. So I am actually thinking of being able to use a per-workbook config file to override the global settings instead of tinkering with the xml internals.

**Comment by sdementen** [comment]
I wonder if this would support my classical use case:
- a conda envs is created with all the dependencies + module with xlwings functions on the user laptop
- the excel file (in read-only) is hosted on a network folder, can be loaded by the user and then saved wherever he wants (no extra file to copy with the excel file)

As far as I understand your proposal, you would add some ini file in the same folder than the excel to be copied with ? If so, my use case will break...
Could it jus to use a hidden sheet with some named range in it with the config  variables ?

**Comment by fzumstein** [comment]
Or something like that. I am sure we can come up with a solution ;) I ll let you know when I have something working.

**Comment by fzumstein** [comment]
#691
