### ISSUE TITLE
refactor API and Application/Sheet/Range object model

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#303]
Hello Felix and others,

here is some open brainstorming on xlwings API.

xlwings currently uses implicit current instances (workbook and sheet) for most of its functions. If one does not want to use the current instance, he/she needs to specify it in as argument in the function (e.g Sheet(..., wkb=...). This is somewhat unpythonic (explicit is better than implicit) but also bug prone.

For instance, the code:

    @property
    def last_cell(self):
        return Range(xlplatform.get_worksheet_name(self.xl_sheet), (self.row2, self.col2), **self.kwargs)

works fine until one does

    some_wb.set_current()
    r = Range('A1')
    another_wb.set_current()
    r.last_cell

where the last_cell is now done on the another_wb instead of the some_wb.
Some other functions of the Range class returning new Ranges suffer from the same bug too (__next__, table, vertical, ... ). Solving this probably requires to write

    @property
    def last_cell(self):
        return Range(xlplatform.get_worksheet_name(self.xl_sheet), (self.row2, self.col2), wkb=Workbook(xl_workbook=self.xl_workbook), **self.kwargs)

which starts to be quite convoluted.

Besides, and IMHO, a neat part of the excel object model is the hierarchical relationships between application => workbook => sheet => range (each of them being the parent of the other).
It is then easy to add a sheet to a specific workbook (wb.Sheets.Add ...) or refer to the range of a specific sheet (sh.Range ...).

I would find nice to extend the xlwings API by a) keeping the 'current' instance logic (for backward compatibility or for simple interactions) and b) extending the API more in line with the Excel COM object model. For example, for the Application class:
  - extend __init__(self, wkb=None, target=None, visible=True, new_instance=False)
  - add a workbooks property with a collection interface : .add (create new workbook), .new (create workbook from a template), .open (open existing workbooks), __getitem__ (return workbook with name or index given in arg)

The Application would also return always the same instance when it refers to the same xl_app.
The same can be done for Workbook (with a sheets collection that would include an .iteritems method to iterate over (sheet name, Sheet instance) and a __contains__ method to test for sheet existence) and Sheet (with a range method) with all of them being 'singleton' (ie one python object for each Excel object).

We would explicitly have the parent - child relationship with:
 - The Workbook would have a link to xl_workbook and to its Application (.app and .parent)
 - The Sheet would have a link to xl_sheet and to its Workbook (.wkb and .parent)
 - The Range would have a link to xl_range and to its Sheet  (.sheet and .parent)

The code hereabove could be rewritten as

    @property
    def last_cell(self):
        return self.sheet.range((self.row2, self.col2), **self.kwargs)

The code

    Sheet("new sheet", wkb=wb)
    Sheet.all()
    Sheet.count()

would be written as

    wb.sheets.add("new sheet")
    wb.sheets
    len(wb.sheets)

and overall, it would map better with the Excel object model (at least the one under Windows, I have no knowledge of the Mac one).

Any opinion/advice ?

**Comment by fzumstein** [comment]
Yes, you're right, the API needs a refactoring, Eric and I have had similar discussions. This is planned for a v1.0 release. Since we have labeled the package as beta/v0.x with a note on possible backward incompatible changes, we should not care about it until v1.0 is released. The object model is the same on Mac and Windows, so that's not an issue. We'll post our ideas here, but my planned roadmap is to first merge/release the `excelpython-integration` branch, your `accessor` branch and then create a proper `add-in` before we get to that topic.

**Comment by sdementen** [comment]
ok, if you want me to give a hand on some topic, do not hesitate
