### ISSUE TITLE
Excel 2016 & Windows 10

### ISSUE THREAD

**Issue by drummonds** [ZoomerAnalytics/xlwings#317]
In order to get to work on my computer I changed line 234 in xlwings\main.py from 
            xl_app, xl_workbook = xlplatform.get_open_workbook(fullname, hwnd=sys.argv[4])
to
            xl_app, xl_workbook = xlplatform.get_open_workbook(fullname)

Only 3 arguments are passed.
I really like it.

**Comment by fzumstein** [comment]
I guess what you *should* have done is updating the VBA module in Excel to the latest version instead. Currently that's a manual process and we don't even have a check for it.

**Comment by drummonds** [comment]
(This is just a comment for me so that I can remember exactly what to do.  I reinstalled Python and so recreated the problem. )
http://docs.xlwings.org/en/latest/vba.html

**Comment by fzumstein** [comment]
So can you confirm that the issue was an outdated xlwings VBA module?

**Comment by drummonds** [comment]
Sorry yes you were right.
