### ISSUE TITLE
[Mac] Unable to instantiate Workbook even though Excel file exists

### ISSUE THREAD

**Issue by rkpatel33** [ZoomerAnalytics/xlwings#320]
I am trying to create a workbook by filename however the following code does not seem to work:

```
import xlwings as xw
XL_FILENAME = 'AssetAllocation_v2.xlsx'
wb = xw.Workbook(XL_FILENAME)
```

Even though the file is in my current directly:  https://www.evernote.com/l/AAo5LRq67nVPEpAelfName0Brf0LEMyv5Z0

Thi is the error:

```
/Users/rishi/Virtualenvs/global/lib/python2.7/site-packages/psutil/_psosx.pyc in wrapper(self, *args, **kwargs)
    207                     raise NoSuchProcess(self.pid, self._name)
    208                 else:
--> 209                     raise ZombieProcess(self.pid, self._name, self._ppid)
    210             if err.errno in (errno.EPERM, errno.EACCES):
    211                 raise AccessDenied(self.pid, self._name)

ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=67)
```

**Comment by fzumstein** [comment]
I think that this is the same error as #315 and seems to be caused by a recent upgrade of psutil.

However, my guess is that if you ingore the error, the Workbook is still instantiated correctly?

**Comment by rkpatel33** [comment]
No, it does not seem to instantiate properly, in the statement

```
wb = Workbook('AssetAllocation_v2.xlsx')
```

`wb` is still empty. I'm guessing it's not possible to roll back the required psutil to an earlier version?

**Comment by fzumstein** [comment]
what version are u on? sure you can just do pip install psutil==3.2.2, for
example

Am Donnerstag, 3. Dezember 2015 schrieb rkpatel33 :

**Comment by rkpatel33** [comment]
I will downgrade then. I have:


*xlwings==0.6.0*


*psutil==3.3.0*



______________________________________
Rishi K. Patel
​, ​
Founder
​,
www.docnavapp.com
*​*
​
rishi@docnavlab.com
​,
917-647-0892​
LinkedIn <https://www.linkedin.com/in/rkpatel33>
