### ISSUE TITLE
able to change the color of a portion of a string in a cell.

### ISSUE THREAD

**Issue by barelyPy** [ZoomerAnalytics/xlwings#321]
Hi, this is a minor feature request, but it would help us immensely.

I am very glad we have .xl_range .xl_sheet to work with.
But I can not make the following syntax work:
xlwings.Range('A1').xl_range.Characters(starting_index, str_size).Font.Bold = True

Thanks.

**Comment by fzumstein** [comment]
You need to use `xlwings.Range('A1').xl_range.GetCharacters(starting_index, str_size).Font.Bold = True`

**Comment by barelyPy** [comment]
Dear Sir,

Thank you so much for such an in time and personal response.

On Sat, Dec 5, 2015 at 3:55 AM, Felix Zumstein <notifications@github.com>
wrote:

> You need to use xlwings.Range('A1').xl_range.GetCharacters(starting_index,
> str_size).Font.Bold = True
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZoomerAnalytics/xlwings/issues/321#issuecomment-162168092>
> .
>



-- 
Sincerely and Respectfully

Yun Liu
