### ISSUE TITLE
Static objects and consts in vba module

### ISSUE THREAD

**Issue by AntonioSuriano** [ZoomerAnalytics/xlwings#328]
A lot of stuff in VBA xlwings module is dynamic.

Example:

every udf has Set xlpy = Py.Module("xlwings"), could it put as module static variable?

Another example the function setting returns always the same values that are so recomputed hundreds of times.

I dunno what is the impact on performance of these. Probably negligible, probably not.

**Comment by fzumstein** [comment]
Thanks for the input. We're looking into performance improvements in the future. The biggest performance gain could be achieved by marrying the ExcelPython v1 and v2 approach.
