### ISSUE TITLE
udf can share objects only with @xlsub and not with standard xlwings subs?

### ISSUE THREAD

**Issue by AntonioSuriano** [ZoomerAnalytics/xlwings#329]
I have in my module some global objects.
These objects are generated by a subroutine.

If I call this subroutine using the @xlsub  the udfs can see the global objects.

If I call the subroutine using RunPython ("import mymodule; mymodule.inizializza()") the udfs cannot see the global objects.

Is it the standard behaviour or there is something wrong in my RunPython syntax?

**Comment by AntonioSuriano** [comment]
Well I am happy with UDFs: this is the real way of making xlwings useful in production environments.

By the way after an afternoon of coding I have 11 zombie python processes. I am looking forward to the fix :)

**Comment by AntonioSuriano** [comment]
What really rocks is that with @xlsub and @xlfunc you can edit your py file on the fly and get the new result.

**Comment by fzumstein** [comment]
Hi Antonio, posting some sample code would help.

**Comment by AntonioSuriano** [comment]
well,

something like (I am not at work now so I go by hearth)

global dizionario_oggetti= {}

@xlfunc
def interroga_dizionario(a):

**Comment by fzumstein** [comment]
To answer the original question of this thread: yes, `RunPython` starts and stops an own python session every time, while the decorator syntax talks to a single python process that keeps on running after the udf is called.

**Comment by AntonioSuriano** [comment]
Well I have optimized connection=True and usually I use buffers of objects with RunPython effectively.

It just seems that RunPython and xlsub have different namespaces but I don't know how to let them communicate.

**Comment by fzumstein** [comment]
Why would you want to to mix them? OTIMIZED_CONNECTION will most likely go away in one of the next releases as it's essentially the same as using a `@xlsub` decorator.

**Comment by AntonioSuriano** [comment]
RunPython seems 3x faster, but it is not that important.
