### ISSUE TITLE
writing pandas dataframe fails if index also a column

### ISSUE THREAD

**Issue by simonm3** [ZoomerAnalytics/xlwings#334]
if you do `df=df.set_index(df.col1)` then you have an index of col1 and a column col1 which is still a valid pandas dataframe.

`Range("A1").value = df` now fails with "cannot insert col1 already exists as it resets the index before writing. Would be better to output index then columns rather than failing.

**Comment by fzumstein** [comment]
Fixed, until the next release just use `Range('A1', index=False).value = df`
