### ISSUE TITLE
Controlling the Excel instance

### ISSUE THREAD

**Issue by tomanizer** [ZoomerAnalytics/xlwings#335]
xlwings should allow the user to determine explicitly if he wants to connect to a running Excel instance or a new Excel instance.

Suggestion:
a = xlwings.Application() -> creates a new Excel instance, with a as a handle on the instance.
a(wb="C:\MyWorkbook.xls") -> opens the workbook in this specified Excel instance, not the active one.
a.close -> closes the instance (and all running workbooks in it)

Use case:
A Python program uses xlwings to open an workbook, manipulate and refresh it, and close it.
This program should not affect other random workbooks or Excel sessions currently open on the user's desktop.
Currently xlwings connects to a random Excel instance if it finds one running, and if it doesn't, it opens a new one. Once connected to the application, xlwings can manipulate and change the behavior of the Application object which it did not create, e,g. load new addins or change switch the calculation mode from automatic to manual, which  then affects all other workbooks in this Excel session.
For all kinds of automation jobs, xlwings needs to be able to create it's own instance, not interfering with the users other work.

**Comment by tomanizer** [comment]
This thread explains the issue.
It suggests to use pywin32s DispatchEx method instead of Dispatch in order to create a new instance for automation jobs.

http://stackoverflow.com/questions/18648933/using-pywin32-what-is-the-difference-between-dispatch-and-dispatchex

**Comment by tomanizer** [comment]
Is issue #218 related to this?

**Comment by fzumstein** [comment]
Good catch, it's the same issue, yes. I ll close the other one.

**Comment by tomanizer** [comment]
why did you remove it from the milestone?
Is there anything I can do to get this in?

**Comment by fzumstein** [comment]
it's gonna be part of a bigger refactor (blue sky branch) so will take little longer
