### ISSUE TITLE
xlwings not recognised as an internal or external command

### ISSUE THREAD

**Issue by tobairsegais** [ZoomerAnalytics/xlwings#336]
I'm not sure how windows is supposed to recognise the xlwings command line commands for the 'template' functionality.

I only get the command not recognised windows error message, even when running from the xlwings install directory where the xlwings32.dll is located.

I have installed xlwings using  $ conda install xlwings  into an Python 3.5 environment. xlwings v 0.6.1 is installed
Can you suggest a solution please?

**Comment by fzumstein** [comment]
I think the conda package hasn't been updated correctly for >v0.6.0 to include the command line client. Thanks for reporting. In the meantime, you should be able to install it via pip.

**Comment by tobairsegais** [comment]
Hi Felix,
You're welcome. Can you let me know when this gets released.
David


David Mansfield | +852 6348 5541 | david_t_mansfield@hotmail.com


-------- Original message --------

**Comment by fzumstein** [comment]
I opened an issue here: https://github.com/ContinuumIO/anaconda-issues/issues/612

**Comment by fzumstein** [comment]
the conda v0.6.4 package seems to correctly support the command line client now.
