### ISSUE TITLE
Import Python UDFs Not Working

### ISSUE THREAD

**Issue by 891077401** [ZoomerAnalytics/xlwings#337]
I get an error message using xlwings in Excel 2013, which says to "Make sure that this workbook contains the xlwings module and you are trusting access to the VBA project object module (Options)."

Steps I have taken:
1. Imported xlwings.bas
2. Made sure the file names for the .xlsm and .py were the same and in the same folder
3. Made sure UDF_PATH was unaltered
4. Made sure trust settings included the path to file in Options

What could cause this issue?

**Comment by fzumstein** [comment]
Not sure if you got No 4 right, what you want is this checkbox:

![screen shot 2016-01-06 at 09 46 13](https://cloud.githubusercontent.com/assets/2265504/12138601/6a9a3700-b45a-11e5-9765-42b926d7a804.png)

**Comment by 891077401** [comment]
Thanks, you were spot on.
