### ISSUE TITLE
__file__ and logging module

### ISSUE THREAD

**Issue by PhE** [ZoomerAnalytics/xlwings#343]
I would like to use the logging module from my Python code embedded in an Excel addin (xlwings based).

I failed to use the The LOG_FILE settings of xlwings. It seems to catch only stderr output and not the logging module.

So I decided to configure the logging module to output to a file.
I want this log file to be next to my Python source code or next to my Excel addin file.
When I use the \_\_file\_\_ in my Python source, I get this error : 
```
NameError: name '__file__' is not defined
```

When I use : `os.path.dirname(os.path.realpath('__file__'))`, I get `C:\Program Files\Microsoft Office\Office15` which is not where my addin and py files are !

How can I get the absolute path of my running Python code ?

**Comment by fzumstein** [comment]
I don't know why you get the error, but the `__file__` trick is indeed unreliable under certain circumstances. The following sample works:

```
import os
import inspect
import logging
import xlwings as xw

this_dir = os.path.realpath(os.path.dirname(inspect.getfile(inspect.currentframe())))

logging.basicConfig(filename=os.path.join(this_dir, 'xw.log'), level=logging.INFO)
log = logging.getLogger(__name__)


def test1():
    log.info('test1')
    xw.Workbook.caller()
    xw.Range('A1').value = 'test1'
    log.info('test2')
```

**Comment by PhE** [comment]
It works. Thanks.
