### ISSUE TITLE
Working with Chart as OpenpyXl 

### ISSUE THREAD

**Issue by coolpix77** [ZoomerAnalytics/xlwings#347]
Hi,
Is there a way to work with charts as OpenPyXl do ? I mean, xlwings allow to create chart as image. But I would like to control excel chart with it.

**Comment by fzumstein** [comment]
Sure: http://docs.xlwings.org/api.html#chart - it's just not supporting that much natively, but you can always work around for now as described here: http://docs.xlwings.org/missing_features.html
