### ISSUE TITLE
Use Range.Value inside an UDF 

### ISSUE THREAD

**Issue by coolpix77** [ZoomerAnalytics/xlwings#348]
Hi,

I would like to use UDF as a "macro".
For instance :
```
@xw.xlfunc
def random(r,c):
    """Returns a random number between 0 and 1"""
    app = xw.Application(xw.Workbook.caller())
    x = np.random.randn(r, c)
    xw.Range(1,(1,1)).value=x
```

So no return and no need to use matricial excel operation. I think it's easier this way.
But actually, I just get an "Erreur Automation"
Thanks !

**Comment by fzumstein** [comment]
This is not possible by Excel's design: see: http://stackoverflow.com/questions/20768373/writing-into-excel-worksheet-from-custom-vba-function-not-sub

Any solution would require some hacking, so we're currently not looking into it, although you're not the only one wanting this feature (you're still invited to vote): https://zoomeranalytics.uservoice.com/forums/269851-xlwings/suggestions/9308589-possibility-to-create-functions-that-can-amend-val

For now just change it into a `xw.xlsub` and call it as a macro.
