### ISSUE TITLE
Calling Excel VBA from Python

### ISSUE THREAD

**Issue by PhE** [ZoomerAnalytics/xlwings#351]
I thought Is saw it in the doc but can't find it again, so I'm not sure it's possible :
Can we call Excel VBA function from Python code that has been triggered by a RunPython() command ?

My main purpose is to call Excel back for any user interaction (MsgBox #144, forms, InputBox, ...).

**Comment by fzumstein** [comment]
No, it's not yet properly implemented, see #134.

However, [here](http://stackoverflow.com/questions/30308455/how-do-i-call-an-excel-macro-from-python-using-xlwings) you can see how you can still do it.
