### ISSUE TITLE
UNC paths with spaces in it

### ISSUE THREAD

**Issue by sanzoghenzo** [ZoomerAnalytics/xlwings#352]
Hi,
thanks for this great sw, I'm starting using it to move from VBA to python and trying to centralize the code at work in order to minimize the propagation of old/buggy versions.
I tried to place a stand alone example on a samba share/UNC path, but trying to run the macro returned an error. I found it was because of missing double quotes, so I quickly solved it by changing line 233 of xlwings.bas to

    DriveCommand = "pushd """ & PYTHON_WIN & """ & "

I hope you forgive me if I didn't go with the PR path :)
keep up the good work!

**Comment by fzumstein** [comment]
good catch, thanks!
