### ISSUE TITLE
Cannot read back cell from which UDF was called

### ISSUE THREAD

**Issue by 891077401** [ZoomerAnalytics/xlwings#353]
How do I find out the location of the cell from which the UDF is called? Is this possible?

**Comment by 891077401** [comment]
This is my solution:

@xw.xlfunc
@xw.xlarg("caller", vba="Application.Caller")
def CELL_THAT_CALLED(caller):
    return caller.Address

**Comment by fzumstein** [comment]
Yes, that's fine. We're still in the process of aligning ex-ExcelPython within xlwings (also documentation-vise) and the API might change slightly in the future.
