### ISSUE TITLE
Unable to import table from another wkb into caller wkb using UDF

### ISSUE THREAD

**Issue by 891077401** [ZoomerAnalytics/xlwings#354]
I want to manipulate different parts of the wkb with a UDF. (for example, if a particular cell has values above 10, then the next two rows should be completely changed with the values from another workbook). How do I do this with xlwings? I am having trouble with handling workbooks that works otherwise outside the context of UDFs.

**Comment by fzumstein** [comment]
Hi, this is the same issue as #348, please see my answer there.
