### ISSUE TITLE
ImportPythonUDFS throws a run-time error '53' (xlwings 0.6.4)

### ISSUE THREAD

**Issue by cincin77** [ZoomerAnalytics/xlwings#355]
Hello,

on my windows machine, i have python 3.5.1. I installed xlwings and its addin. When i click "Import Python UDFs",  i get the following error: "File not found: xlwings32.dll".

Although it says that this error was fixed in 0.6.2, i have it. Do i miss something?

thanks.

**Comment by fzumstein** [comment]
I assume you have installed xlwings with conda? There was an error in the conda package that should have been fixed yesterday though, so `conda upgrade xlwings` should resolve things. An alternative would be to install it with pip.

**Comment by cincin77** [comment]
Hello,

i installed using setup.py; what should i do if i cant use pip?

thanks.

**Comment by fzumstein** [comment]
OK, can you check in your base installation of Python if xlwings32.dll is sitting in the same directory as python.exe?

**Comment by cincin77** [comment]
It didnt exist. I copied it and retried; same error.

**Comment by fzumstein** [comment]
* is your vba module the latest version, too?
* in ur vba settings, is `PYTHON_WIN = ""` ?
* if so, when you call `python` from a command prompt, does that launch the correct python installation?

**Comment by cincin77** [comment]
i didnt touch the vba settings:
   PYTHON_WIN = ""
    PYTHON_MAC = ""
    PYTHON_FROZEN = ThisWorkbook.Path & "\build\exe.win32-2.7"
    PYTHONPATH = ThisWorkbook.Path
    UDF_PATH = ""
    LOG_FILE = ""
    SHOW_LOG = True
    OPTIMIZED_CONNECTION = False

this was my first xlwings installation so vba module is also the latest.
python call corresponds to my only python installation.

**Comment by fzumstein** [comment]
you did enable `Trust access to the VBA project object model `the as described here: https://github.com/ZoomerAnalytics/xlwings/issues/337 and here: http://docs.xlwings.org/udfs.html ?

**Comment by cincin77** [comment]
yes, it was enabled.

**Comment by fzumstein** [comment]
what happens if you click `Alt + F8` and run the ImportUDFs macro from there?

**Comment by cincin77** [comment]
exactly same error message.

**Comment by fzumstein** [comment]
what' the size in KB of your dll?

**Comment by cincin77** [comment]
235 KB.

**Comment by fzumstein** [comment]
What's your Excel version? and it's 32 bit, correct?

**Comment by cincin77** [comment]
Hello,

it is Excel 2013 32 bit.
Suddenly, after lunch, it just started to work. I dont know what caused this but it is working now.
Sorry for taking your time; i close this case.
