### ISSUE TITLE
UDF without excelpython or xlsm

### ISSUE THREAD

**Issue by sethor** [ZoomerAnalytics/xlwings#356]
Dear All,
I am having problems making Python-based UDFs as part of an add-in. I want users to be able to use it from any kind of workbooks, so I can't use the newly attached features based on excelpython. I tried to write simple functions, passing the function arguments as parameters of  the RunPython function. When I call it with the VBA's Run Sub button, it works fine, but when I call it from the Excel table, it gives a quite long AttributeError originating from the wb = Workbook.caller() line in my Python file.
Could someone give me an example to how can a UDF be written this way, if it is even possible? Also, is there any way to use excelpython-based functions and udfs with an add-in in a simple xls/xlsx file?
Here is my trial VBA code:
```
Function muha()
    RunPython ("import excel; excel.muha()")
    muha = 2
End Function
And the related part of my python code:
wb = ""  #I'm using it in other functions as well...
def muha():
    wb = Workbook.caller()
    Range('Sheet1', 'A2').value = 4
```
I would really appreciate any kind of help, I'm kind of stuck with this problem.
Thank you in advance!
Peter

**Comment by fzumstein** [comment]
It's not really clear to me what your main issue is. You say that you can't use the new decorator syntax for UDFs, why not?

**Comment by sethor** [comment]
Because (if I understand it correctly) this solution is based on ExcelPython, and can be used only with macro-enabled workbooks. However, I am writing an add-in to simple xls/xlsx files as well, so I can't force my users to save their files az xlsm all the time.
So I wanted to avoid having to use the "import UDFs" utility, as I tried ExcelPython earlier and couldn't solve the macro problem. That's why I'm trying to make it work with a simple argument - passing solution. I call the function from excel in a field with = myfunc('param'); in the VBA code I have
sg I showed earlier, and in the python code a simple sg I showed ealier, too. So basically my question is: can I use UDFs defined in Python with xlwings without having to use macro-enabled workbooks?
It is probably a noob question, sorry for that, just started using xlwings and VBA.
Thank you for your help!

**Comment by fzumstein** [comment]
It's not a good strategy to use `RunPython` for UDFs - it's just too slow for that. You should be able to put the VBA wrapper code, that is generated by importing the UDFs, into your add-in, but that would obviously require you to redeploy the add-in whenever you want to change/add more UDFs in the future.

**Comment by sethor** [comment]
Yes, but unfortunately I can't have that liability, the whole point of this add-in is to have the code in python instead of VBA. If slowness wasn't an issue, is it possible to solve this problem with RunPython?

**Comment by sethor** [comment]
One possible solution would be if RunPython was able to communicate the caller cell to python. I couldn't find anything of the sort, but sg like Cell.caller() in python would be extremely useful. If not that, then it should be manageable by getting a return-value-sort-of-thing from RunPython, would it be possible?

**Comment by fzumstein** [comment]
Getting the calling cell is not an issue, you would need to replace `ThisWorkbook` with `ActiveWorkbok` when using things from an add-in, see [here](https://github.com/ZoomerAnalytics/xlwings/blob/master/scripts/build_addins.py). Note that we'll be working on an actual add-in somewhere in the near future. `RunPython` cannot return values, so that's anyhow not an option.
Please have a look at https://www.pyxll.com/ which might be exactly what you need, although it's not free for commercial use.

**Comment by sethor** [comment]
Yes, I've already replaced all instances of ThisWorkbook with ActiveWorkbook and added the whole modified xlwings bas file to my addin's modules. My main problem is that after entering a function that contains RunPython into a cell, I get an AttributeError, originating from xlwings' main.py, it seems it can't get the name of the open workbook. This line throws the error:
xl_app, xl_workbook = xlplatform.get_open_workbook(fullname, hwnd=sys.argv[4])
However, if I call the function directly from VBA, there isn't any error. Could you help me out with that?
Unfortunately I can't use non-free elements in the add-in, so pyxll is out of the picture.

**Comment by sethor** [comment]
Oh and of course, the problematic code part is the wb = Workbook.caller() in the python file.
