### ISSUE TITLE
calling python directly from a cell without using the udf utility

### ISSUE THREAD

**Issue by sethor** [ZoomerAnalytics/xlwings#362]
Hi! I can't solve this issue and it's really bugging me: the Workbook.caller() functions throws an AttributeError when I call it from a cell directly with = myfunction(). myfunction() is a function which calls the python code with RunPython.
It seems that the problem comes from RunPython being unable to pass correctly the hwnd or application id to the python part. As there is no intrinsic error handling inside most functions, the error surfaces only at pywin32's dinamic.py's __getattribute__ function. It catches the problem after checking every possible attributes.
Before that, the error gets through the following functions: 
```
xlwings\main.py
 xl_app, xl_workbook = xlplatform.get_open_workbook(fullname, hwnd=sys.argv[4])
xlwings\_xlwindows.py in get_open_workbook
duplicate_fullnames = get_duplicate_fullnames()
xlwings\_xlwindows.py in get_duplicate_fullnames
 for xl_app in get_xl_apps():
xlwings\_xlwindows.py in get_xl_apps
xl_app = get_xl_app_from_hwnd(hwnd)
xlwings\_xlwindows.py in get_xl_app_from_hwnd
return disp.Application
pywin32\win32com\client\dynamic.py in __getattr__
raise AttributeError("%s.%s" % (self._username_, attr))
```
Could you help me with that?

**Comment by sethor** [comment]
Any help would be greatly appreciated!

**Comment by fzumstein** [comment]
The issue with these kind of thing is that Excel UDFs only allow to change the calling cell. There's a hack in your particular use case that you can try which is setting `waitOnReturn := False` [here](https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/xlwings.bas#L218). This makes the call run in the background and it therefor can access cells outside of the calling cell as the UDF call returns instantly.

Please note though that I again would not advise you to rely on this approach.

**Comment by sethor** [comment]
Thank you very much, it really is working this way. What undesired effects can be the result of turning waitOnReturn off? Debugging problems?

**Comment by sdementen** [comment]
Could this functionality be set at the UDF level ?
something in the vein of:

@xlfunc
def calculate_with_delay(input, output):
    # this gives back the hand to Excel and yield the return value of
the function
    yield "calculating"

    # this runs async
    output.Value = "output of the function"

    # OPTIONAL (as probably very tricky/impossible to do)
    # this update the return value of the function
    yield "done" # this would be return again

**Comment by ericremoreynolds** [comment]
Yes it's tricky to implement, but asynchronous functions would are a feature which would have a wide appeal I believe. It's on our todo list...

**Comment by fzumstein** [comment]
see #473
