### ISSUE TITLE
Can not call a function which has a default parameter

### ISSUE THREAD

**Issue by cincin77** [ZoomerAnalytics/xlwings#363]
Hello,

I have a function whose last parameter is optional as it has a default value. It works when that parameter isnt given in the python console but when it is used in Excel through xlwings, it doesnt return. (#VALUE!) Do i miss something? Is there a way to make it work?

thanks.

**Comment by fzumstein** [comment]
You're right - that's currently not supported yet.

**Comment by DougAJ4** [comment]
In this situation I add the argument as optional with a default value in the VBA code, e.g.:

Function MyFunc(... , Optional optionalarg1 as Long = 0, Optional optionalarg2 as Double = 1.0)

**Comment by fzumstein** [comment]
Closed by PR #389
