### ISSUE TITLE
Using docstrings with UDF

### ISSUE THREAD

**Issue by DougAJ4** [ZoomerAnalytics/xlwings#367]
Is it possible to add argument descriptions for UDFs, as well as the description of the function?

The code seems to allow for this, but the udf.py example does not include argument descriptions, and I can't get it to work.

**Comment by fzumstein** [comment]
yes, function description are possible using simple docsteings but arg descriptions are currently broken, see #312

**Comment by DougAJ4** [comment]
Thanks for the quick response.  It will be an excellent addition when fixed!

I have been using ExcelPython for over a year now (and Pyxll before that),
but have just started with xlwings.  The good news is that all my
ExcelPython udfs seem to work with minimal changes under xlwings (i.e. just
replace the ExcelPython module with xlwings module).

You might like a look at my first xlwings effort at:
https://newtonexcelbach.wordpress.com/2016/02/14/use-matplotlib-from-excel-with-xlwings/

Thanks again.

Doug

**Comment by fzumstein** [comment]
yes, saw that, thanks a lot for this blog post! We're currently working on a bigger release that amongst other things streamlines the behaviour of the old xlwings with the ExcelPython part. So hopefully we can include the fix for argdocs in there.

**Comment by fzumstein** [comment]
fixed by #589
