### ISSUE TITLE
Generate automatically VBA binding code from UDF

### ISSUE THREAD

**Issue by arita291** [ZoomerAnalytics/xlwings#368]
Hello,

Do you think we can add automatic VBA code generation for Python UDF binding,
using  import inspect in Python. We just need to know the type of each argument

Real --> x = NDims(x, -1)
Array --> x = NDims(x, 2): Set x = Py.Call(Py.Module("numpy"), "array", Py.Tuple(x))

Function matrix_mult(x, y)
        name1 = "matrix_mult"
       ' If TypeOf Application.Caller Is Range Then On Error GoTo failed
       'Cast the arguments  --> NUMPY, add extra parameters
        If TypeOf x Is Range Then x = x.Value2
        If TypeOf y Is Range Then y = y.Value2
                
        If Not TypeOf x Is Object  Then x = NDims(x, 2): Set x = Py.Call(Py.Module("numpy"), "array", Py.Tuple(x))
        If Not TypeOf y Is Object  Then y = NDims(y, 2): Set y = Py.Call(Py.Module("numpy"), "array", Py.Tuple(y))

    
        Set args = Py.Tuple(x, y)  'Generate from Python

        'Call function (nothing to change)
        Set xlpy = Py.Module("xlwings"):         Set script = Py.Call(xlpy, "udf_script", Py.Tuple(PyScriptPath))
        Set func = Py.GetItem(script, name1): Set res1 = Py.Call(func, args): res1 = Py.Var(res1, True)
        
        matrix_mult = res1
        Exit Function
failed:

**Comment by fzumstein** [comment]
It's not really clear what you want here. Can you please describe the issue you're facing rather than providing the solution?

**Comment by arita291** [comment]
Hi,
I have few python modules containing around 300 functions....
I would like to generate the VBA code for wrapping in VBA and use them in VBA.

Manually, it's very lond and on top, wrapping one simple function with 5 arguments takes,
minimum:  15lines of VBA code....
15*200 = 3000 lines of VBA code (90% are copy paste code).
To solve it:
   Generate from Python, reading the python file (containing the functions) generate prototype in VBA.


Main issue to find the correct type for each argument.

**Comment by fzumstein** [comment]
You just need to decorate your functions and import them via the add-in, this automatically creates the VBA wrapper code, see [here](http://docs.xlwings.org/udfs.html#simple-user-defined-functions).

**Comment by arita291** [comment]
Ok, thansk (I was looking at your spreadsheet (worksheet name for UDF).

It seems the name of the python script cannot be changed ??
(same name than Excel Workbook ?)

Sub ImportPythonUDFs()
    Dim scriptPath As String, tempPath As String
    scriptPath = PyScriptPath()
    tempPath = Py.Str(Py.Call(Py.Module("xlwings"), "import_udfs", Py.Tuple(scriptPath, ThisWorkbook)))
End Sub

**Comment by fzumstein** [comment]
It can be changed under `UDF_PATH`. please have a look at the docs [here](http://docs.xlwings.org/vba.html#settings)

**Comment by arita291** [comment]
Ok, it works. Thank you. Package is a good one.
To reduce the amout of code, one do this in VBA, since this code is repeated all long:

Function callpython(name1, func, args)
 Set xlpy = Py.Module("xlwings"):      Set script = Py.Call(xlpy, "udf_script", Py.Tuple(PyScriptPath))
 Set func = Py.GetItem(script, name1): Set res1 = Py.Call(func, args):
 callpython = Py.Var(res1, True)
End Function
 
 Function matrix_mult(x, y)
        name1 = "matrix_mult"
..... 
 matrix_mult = callpython(name1, func, args)
