### ISSUE TITLE
Reduce the amount of VBA code for UDF binding

### ISSUE THREAD

**Issue by arita291** [ZoomerAnalytics/xlwings#370]
From previous discussion, we can reduce the amount of VBA code generated for UDF binding:
(Imagine you have 500 functions to bind....)

1.) Reduce the VBA code for variable binding (array, scalar), if possible, put one line for each variable (I tried,it seems that numpy array Cast cannot go through VBA)

2) Calling ofr Python function can be done in ONE LINE:

Reduce VBA Code is

```
Function matrix_mult(x, y)
name1 = "matrix_mult"
..... 
matrix_mult = callpython(name1, func, args)
End Function

Function callpython(name1, func, args)
   Set xlpy = Py.Module("xlwings"): Set script = Py.Call(xlpy, "udf_script", Py.Tuple(PyScriptPath))
   Set func = Py.GetItem(script, name1): Set res1 = Py.Call(func, args):
   callpython = Py.Var(res1, True)
End Function
```

**Comment by fzumstein** [comment]
This has already been completely refactored for upcoming v.0.7
