### ISSUE TITLE
Enable use of xlwings.bas without having to modify Settings function

### ISSUE THREAD

**Issue by jimm-domingo** [ZoomerAnalytics/xlwings#373]
We include the xlwings' VBA module in an Excel add-in that we develop in house.  Every time we upgrade xlwings to a newer version, we copy its VBA module into our project.  But each time we have to modify several lines of codes in the Settings function to assign values we need.

It would be better to be able to drop a new copy of `xlwings.bas` into the project without having to alter its code.  It would have some public variables or a public procedure for assigning its settings, so another VBA module could set them.  For example:

```
' VBA module for ThisWorkbook

Private Sub Workbook_Open()
#If Mac Then
   xlwings.PYTHON_MAC = ...
#Else
   xlwings.PYTHON_WIN = ...
#End If
   xlwings.SHOW_LOG = False
   ...
End Sub
```

**Comment by fzumstein** [comment]
Plan is to actually turn things into an official xlwings add-in in the near future...for now I would like to keep things in a single vba module for ease of use.
