### ISSUE TITLE
Functions works from ExcelPython but not xlwings

### ISSUE THREAD

**Issue by DougAJ4** [ZoomerAnalytics/xlwings#401]
I have a spreadsheet that calls Scipy functions, written using ExcelPython.  All the functions work from xlwings, except for one:

```
def xl_SolveFSPC(Func, values, smethod):
    stime = time.clock()
    pfun = globals()[Func]
    nx = int(values[0])
    ny = int(values[1])
    hx, hy = 1./(nx-1), 1./(ny-1)
    P_left, P_right = values[2], values[3]
    P_top, P_bottom = values[4], values[5]
    M = get_preconditioner(nx, ny, hx, hy)
    guess = np.zeros((nx, ny), float)
    svalues = np.array([values])
    solveopt = {'disp': True, 'jac_options': {'inner_M': M}}
    res = sopt.root(pfun, guess, svalues, method = smethod, options = solveopt)
    rtn = res.fun
    if res.x.ndim == 1: 
        resx = [res.x] 
    else: 
        resx = res.x
    return [resx, rtn, [res.success, res.message, time.clock() - stime]]
```
Func and smethod are strings, values is a 1D array with 6 values.  I have checked that values is being imported correctly.

When I run this function using ExcelPython or direct from Python it returns the correct results, but when I run it using xlwings I get:
"TypeError: __init__() got an unexpected keyword argument 'inner_M'
    x, info = nonlin.nonlin_solve(f, x0, jacobian=jacobian(**jac_options),
  File ""C:\Users\douga_000\Anaconda2\lib\site-packages\scipy\optimize\_root.py"", line 294, in _root_nonlin_solve
    **options)
  File ""C:\Users\douga_000\Anaconda2\lib\site-packages\scipy\optimize\_root.py"", line 198, in root
    res = sopt.root(pfun, guess, svalues, method = smethod, options = solveopt)
  File ""c:\users\douga_000\documents\spread\xlwings\xlScipy.py"", line 890, in xl_SolveFSPC
    return ToVariant(getattr(obj, method)(*pargs, **kwargs))
  File ""C:\Users\douga_000\Anaconda2\lib\site-packages\xlwings\server.py"", line 183, in Call
    return func(*args)
  File ""C:\Users\douga_000\Anaconda2\lib\site-packages\win32com\server\policy.py"", line 585, in _invokeex_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File ""C:\Users\douga_000\Anaconda2\lib\site-packages\win32com\server\policy.py"", line 282, in _invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File ""C:\Users\douga_000\Anaconda2\lib\site-packages\win32com\server\policy.py"", line 277, in _Invoke_"

Any ideas?

**Comment by fzumstein** [comment]
Could you please make a self-contained example with all imports, dependencies (like get_preconditioner) and some sample imput data?

**Comment by DougAJ4** [comment]
[xlSolveF.zip](https://github.com/ZoomerAnalytics/xlwings/files/177685/xlSolveF.zip)


OK, the attached file contains:
xlSolveF.xlsb - The ExcelPython version
xlSolveF_xlw.xlsb - The xlwings version
xlSolveF.py - The python code for both versions.

The spreadsheets are identical, other than that one has the ExcelPython module, and the other the xlwings module.

Sorry the VBA is so long.  Let me know if that is a problem and I can trim it back, but the same 3 arguments are passed to the Python code, which is the same for both.

You will see that I am now getting a different error message to that posted above, but the ExcelPython version still works.

**Comment by DougAJ4** [comment]
I think I have solved this one:

The Scipy.optimize.root function has an option disp:
**disp** : bool, optional
  Print status to stdout on every iteration

If this option is set to false the function works from xlwings.

Presumably the output to stdout is messing with the xlwings code.  Is there an option to ignore output to stdout?
