### ISSUE TITLE
Cx_freeze standalone breaks with version 0.7 in Windows

### ISSUE THREAD

**Issue by dhbachh** [ZoomerAnalytics/xlwings#413]
Hi guys,
i'm a massive fan of your module and have been using it for quite some time.
In order to automate a lot of the processes at work I usual distribute my xlwing code as an executable.
However after downloading the 0.7 version and compiling it with cx_Freeze
the following errors appears when calling the executable

![bugxlwings0 7](https://cloud.githubusercontent.com/assets/12612251/13929877/41e0dbb4-ef94-11e5-9cf3-27836437f6b9.PNG)

It should be noted that the error has only appeared on the 0.7 version and was absent under 0.6.4.
By searching around the web I also noticed that you guys already faced this sort of issue in the past versions : http://stackoverflow.com/questions/27871394/error-with-cx-freeze-and-xlwings-as-standalone-version-with-fibonacci-tutorial

https://github.com/ZoomerAnalytics/xlwings/issues/133

Thanks a lot for delivering such an awesome and powerful tool,

PS: you should maybe think of setting up a donation page sometime : ) I know an awful lot of people that wouldn't hesitate supporting your module

**Comment by fzumstein** [comment]
Ok thanks, this will be fixed with v0.7.1. If you need a fix now, change line 14 of server.py with this here: 

    if not hasattr(sys, 'frozen'):
        os.chdir(sys.exec_prefix)

**Comment by schoolie** [comment]
Just ran into this bug today. Thanks for the fix!

**Comment by denfromufa** [comment]
is it possible to freeze xlwings with python UDF into one .xll/.exe that can be straight loaded into Excel?
