### ISSUE TITLE
numpy scalars break with v0.7

### ISSUE THREAD

**Issue by cincin77** [ZoomerAnalytics/xlwings#415]
I can no longer call my Python functions after i upgraded to v0.7.
v0.7 is installed while there was v0.6.x on the system. xlwings addin update is run. v0.7's .bas file is imported into the excel. xlwings32.dll that comes with v0.7 is copied to the python installation folder.
Excel knows about the Python functions but they return #VALUE!

**Comment by fzumstein** [comment]
Can you please download the udf.zip (example 6) from [here](http://xlwings.org/examples/), unzip and check if it works or if you get any errors with this?

**Comment by cincin77** [comment]
It worked. Then should everything be ok?

**Comment by fzumstein** [comment]
Are you using very big arrays in your functions, i.e. do they work with a small toy sample? If so, then it's likely that some of the data processing/cleaning we've added causes this, see also: #396, #397, #401.

If that's not the case, then please post a sample UDF to replicate the issue.

**Comment by cincin77** [comment]
actually it is a very simple UDF that causes this problem:

import math
from scipy.stats import norm
import xlwings as xw

@xw.func
def GBlackScholes(callputflag,S, X, t, r, b, v):
    d1 = (math.log(S/X)+(b+math.pow(v, 2)/2)*t)/(v*math.sqrt(t))
    # print(d1)
    d2 = d1 - v * math.sqrt(t)
    if callputflag == 'c':
        val = S*math.exp((b-r)*t)*norm.cdf(d1) - X*math.exp(-r*t)*norm.cdf(d2)
    elif callputflag == 'p':
        val = X*math.exp(-r*t) * norm.cdf(-d2) - S*math.exp((b-r)*t)*norm.cdf(-d1)
    return val

**Comment by fzumstein** [comment]
Ok the issue is that `val` is a numpy scalar of type `numpy.float64` which are currently causing troubles as this has in fact changed with 0.7 (<0.7 numpy scalars were returned as 1d arrays). To fix this, just transform things back into a regular float: `return float(val)` for now until we have a fix implemented for this.

**Comment by cincin77** [comment]
Thanks.
By the way, i had another function that returns nothing and it also had the problem. I returned a dummy value in order to solve it. Shall this be another bug?

**Comment by fzumstein** [comment]
This one has already been logged here: #390
