### ISSUE TITLE
add basic matplotlib docs to manual

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#417]

**Comment by DougAJ4** [comment]
Good idea :)

Did you see?:
https://newtonexcelbach.wordpress.com/2016/02/14/use-matplotlib-from-excel-with-xlwings/
and
https://newtonexcelbach.wordpress.com/2016/03/20/xlscipy-with-xlwings/

**Comment by fzumstein** [comment]
sure thing, we tweeted about it: https://twitter.com/ZoomerAnalytics/status/699325205198585856
