### ISSUE TITLE
ExitCode VBA command causing run-time error

### ISSUE THREAD

**Issue by jtoro21** [ZoomerAnalytics/xlwings#423]
When trying to run the examples from the xlwings website, I consistently encounter the error message: `Run-time error '5': Invalid procedure call or argument`, which breaks at the line:

`ExitCode = AppleScriptTask("xlwings.applescript", "VbaHandler", ParameterString)`

I am running Excel 2016 (version 15.20) on Mac and have already run `$ xlwings runpython install` as suggested.

**Comment by fzumstein** [comment]
How did you install xlwings in the first place? pip or conda?

**Comment by jtoro21** [comment]
Using conda

**Comment by fzumstein** [comment]
If you click `Cmd+Shift+G` in a Finder, then paste in the following path: `~/Library/Application Scripts/com.microsoft.Excel` and click `Go` to get to that folder, can you see the file `xlwings.applescript` in there?

**Comment by jtoro21** [comment]
Yup, it's located there, but I had to add it manually. When I initially ran the `$ xlwings runpython install` command, I encountered this error in the terminal:

`Traceback (most recent call last):
  File "//anaconda/bin/xlwings", line 6, in <module>
    sys.exit(xlwings.command_line.main())
  File "//anaconda/lib/python3.4/site-packages/xlwings/command_line.py", line 245, in main
    args.func(args)
  File "//anaconda/lib/python3.4/site-packages/xlwings/command_line.py", line 175, in runpython_install
    shutil.copy(os.path.join(this_dir, 'xlwings.applescript'), destination_dir)
  File "//anaconda/lib/python3.4/shutil.py", line 235, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "//anaconda/lib/python3.4/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/anaconda/lib/python3.4/site-packages/xlwings/xlwings.applescript'`

After I fetched the xlwings.applescript file from the GitHub master and placed it in that location, the script did not produce an error but now I have a run-time error in Excel

**Comment by fzumstein** [comment]
I see, the conda package hasn't been built correctly and is missing that file, you should have opened an issue right away when u saw this happening...I will take it up with them.

Do you mind uninstalling the conda package and doing `pip install xlwings`? and see if you hit the same issue? Maybe something went wrong when you manually downloaded the file. If that doesn't help, I can show you how to debug the applescript call to get a bit more meaningful error messages.

**Comment by fzumstein** [comment]
The issue of the missing file was actually on my side - will be fixed in the next version, see #424.

**Comment by jtoro21** [comment]
I fixed the issue on my side. My applescript file was the culprit--I had not downloaded it properly from GitHub during my troubleshooting. Thank you for your guidance with my issue!
