### ISSUE TITLE
Set cells as selected

### ISSUE THREAD

**Issue by ErichDonGubler** [ZoomerAnalytics/xlwings#428]
I know that in VBA it's possible to select cells for the user, and I can't find anything in the docs or API that would suggest that `xlwings` can do so currently. It would be awesome if I could do something like this:

```python
import xlwings
wb = xlwings.Workbook('...')
xlwings.Range('A1:C4').select()
```

...and see the changes reflected in the Excel UI.

EDIT: I see now that the COM interface lets you do something like this:

```python
import xlwings
wb = xlwings.Workbook('...')
xlwings.Range('A1:C4').xl_range.Select()
```

...where `xl_range.Select()` is the magic phrase. Looks like this is easy to implement, though I'm not sure where to put the code.

**Comment by fzumstein** [comment]
available with v0.9.0
