### ISSUE TITLE
import error: import by filename is not supported when importingUDFs in  xlwings-0.7.1 (code worked in 0.7.0)

### ISSUE THREAD

**Issue by sean-violante-lendico** [ZoomerAnalytics/xlwings#435]
I am using the anaconda distibution and set UDF_MODULES=thisworkbook.path & "udffile.py" in xlwings Setting function

![image](https://cloud.githubusercontent.com/assets/11405896/14276588/c25eed3a-fb1f-11e5-99b0-a03072afab78.png)
my code was working in xlwings 0.7.0 and no longer works....

**Comment by fzumstein** [comment]
That's an API change as documented [here](http://docs.xlwings.org/en/stable/whatsnew.html#api-changes). (Although the wording has been mixed up...it should read: `UDF_PATH` has been replaced by `UDF_MODULES`). Make sure to re-import after updating.
