### ISSUE TITLE
formatting string to number while writing back to Excel

### ISSUE THREAD

**Issue by sethor** [ZoomerAnalytics/xlwings#436]
I need to write a huge pandas dataframe from Python to Excel. Among others, it has fields in which there are random alphanumeric combinations, like 1234E324. When writing to Excel, xlwings converts these values to a normal-form number (12e326 or sg). I tried to convert every element to string in the dataframe, but xlwings just won't notice that. I know that there are other conversion possibilities in the newest release, but could we solve this problem with our recent 0.6.4 version?
Thank you very much for your help in advance!

**Comment by sethor** [comment]
I managed to solve the issue, just needed to format the cells from python with win32com to text before inserting the result with xlwings.

**Comment by fzumstein** [comment]
I think this is probably this issue: https://github.com/ZoomerAnalytics/xlwings/issues/36
If you could still post a minimal sample of such DataFrame to replicate the issue would be great.

**Comment by sethor** [comment]
import pandas as p
import xlwings as x
d = {'col1': ['123e12', 'asd'], 'col2': ['a', 'b']}
df = p.DataFrame(data=d)
 x.Range('A1').Value = d

**Comment by ludaavics** [comment]
Having a similar issue.  how exactly did you solve?

**Comment by fzumstein** [comment]
In those cells where you have malformed values, you need to set the number format to Text before writing out the values:

```
xw.Range('A1').number_format = '@'
```

**Comment by sethor** [comment]
Actually I ended up using win32com for writing the results back to Excel. I used the formatting approach fzumstein mentioned as well - due to instabilities both before and after writing to Excel.

**Comment by jp-0** [comment]
UDFs with `@xw.ret(expand='table')` still write-back as numbers instead of string for all but the cell in which the call resides

For example:
```python
@xw.ret(expand='table')
def example():
    return ['001', '0102', '003', '4']
```

Hitting F9 while editing the calling cell shows `{"001","0102","003","4"}`
However the expanded cell output gives cells with values: `"001", 102,   3,   4`


I don't believe fzumstein's workaround is applicable in the UDF case (?)
> In those cells where you have malformed values, you need to set the number format to Text before writing out the values: `xw.Range('A1').number_format = '@'`
