### ISSUE TITLE
Setting border format on Mac

### ISSUE THREAD

**Issue by petobens** [ZoomerAnalytics/xlwings#440]
I'm trying to change the border format on Mac using Excel 2016. I tried the following code:
```python
for border_id in range(7, 12):
    xw.Range('D2').xl_range.borders(border_id).LineStyle = 1
    xw.Range('D2').xl_range.borders(border_id).Weight = 2
```
but I get:
>'NoneType' object has no attribute 'LineStyle'
>'NoneType' object has no attribute 'Weight'

Is there a workaround? Thanks in advance.

**Comment by fzumstein** [comment]
Unfortunately, appscript is not having the same syntax as pywin32. Something like this should work:
```
from xlwings import Workbook, Range
from appscript import k

wb = Workbook.active()

Range('B2').xl_range.get_border(which_border=k.border_top).weight.set(2)
Range('B2').xl_range.get_border(which_border=k.border_top).line_style.set(k.dash)
```

**Comment by petobens** [comment]
Thank you!
