### ISSUE TITLE
Insert a picture only if it doesn't exist

### ISSUE THREAD

**Issue by petobens** [ZoomerAnalytics/xlwings#441]
How do I add (i.e insert) a picture file only if it doesn't exist? Currently I'm using:
```python
xw.Picture.add(fig_path + '/quality_index.png', sheet='Overall Index',
               left=xw.Range('G1').left, top=xw.Range('G1').top,
               height=400, width=500)
```
However every time I run my python script a new picture is inserted on top of the prexisiting one. I would like to check if that picture exists (by assigning it a name first?) and then only insert it if it doesn't exist.

Bonus: can I specify the size of the picture in cm or inches?

Thanks!!

**Comment by fzumstein** [comment]
This is how it's being done for the matplotlib chart picture, you should be able to apply the same principle: https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/main.py#L2014-L2020

**Comment by petobens** [comment]
Thank you! 
Is it possible to get a list with the names of all the pictures and charts in given sheet?

**Comment by petobens** [comment]
Also, is there can I try something similar to `xw.ShapeAlreadyExists` with `Chart`? (`ChartAlreadyExists` doesn't work).

**Comment by fzumstein** [comment]
You can get the names of all pictures/charts by falling back to pywin32 on Windows, see [here](http://docs.xlwings.org/en/stable/missing_features.html).

This could be a start: 

```
import xlwings as xw

wb = xw.Workbook.active()

shapes = xw.Sheet(1).xl_sheet.Shapes
print([i.Name for i in shapes])
```

**Comment by fzumstein** [comment]
To check if a chart already exists, you can do the same as here: Check if the name is part of all shapes: 
https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/main.py#L1842-L1843  The functionality is not part of the public API, but you should be able to import and use `get_shape_names`

**Comment by petobens** [comment]
Great. Thank you!!
