### ISSUE TITLE
Returning Numpy arrays from Python 3

### ISSUE THREAD

**Issue by DougAJ4** [ZoomerAnalytics/xlwings#451]
I have recently installed 32 bit Python 3, after previously using Python 2.7.  The 2.7 version is 64 bit, although I have previously used a 32 bit version with ExcelPython.

I have found that to return Numpy arrays I must now convert them to a list, using for example:
  return np.linspace(start, stop, num, endpoint, retstep).tolist()

The error message I get without that is: Unexpected Python Error: TypeError: Internal error - the buffer length is not the sequence length!
(which wasn't very helpful in tracking down the error).

Is it possible to get the tollst() step automated, or is there some other way of avoiding this error?

**Comment by fzumstein** [comment]
Can you paste a specific example that fails?

**Comment by DougAJ4** [comment]
Sure, here is the full code for a Numpy function that worked with 64 bit Python 2.7, but not 32 bit Python 3:
``def xl_linspace(start, stop, num, endpoint, retstep):
    return np.linspace(start, stop, num, endpoint, retstep)
``
Adding .tolist() to the end of the second line fixes the problem, but there are a lot of functions, and in some cases the Numpy arrays are inside a tuple, so I have to check each function to make sure the .tolist() is in the right place.

**Comment by fzumstein** [comment]
I can't replicate your issue, but I fail to import the function alltogether because `stop` is a reserved word in VBA. This works for me:

```
import xlwings as xw
import numpy as np

@xw.func
def xl_linspace(start, stop2, num, endpoint, retstep):
    return np.linspace(start, stop2, num, endpoint, retstep)
```

are you using v0.7.1?

**Comment by DougAJ4** [comment]
The VBA code I was using was actually old ExcelPython code that I wrote myself, and it used Stopnum rather than stop.

I tried the auto-import routine, using the udf sample file, and I get an error at:
tempPath = Py.Str(Py.Call(Py.Module("xlwings"), "import_udfs", Py.Tuple(scriptPath, ThisWorkbook)))
Error message:
[import error.pdf](https://github.com/ZoomerAnalytics/xlwings/files/234253/import.error.pdf)

So it looks like the problem is associated with finding the right modules, and the need to use .tolist() was just a side effect.

I am using v0.7.1, and I updated with Conda update xlwings.  The system path included both the folder for the old version and the new one, with the new one first.  I tried deleting the old folder from the path, but that didn't make any difference.

**Comment by fzumstein** [comment]
Any chance that the xlwings VBA module is not the latest? Can you quickly try that things work when you start from scratch with `xlwings quickstart some_name`?

**Comment by DougAJ4** [comment]
OK, starting from scratch everything in the sample udf file seems to work (including the matrix_mult using numpy).

It will be a day or two before I have time to get back to my scipy functions, but I hope this will allow me to sort out the problem.

Thanks very much for the quick response and all your help.

**Comment by fzumstein** [comment]
I am closing this for now, please reopen if you need more help.

**Comment by DougAJ4** [comment]
I have been experimenting with the numpy linspace function.  It seems the problem occurs if retstep is True.  In that case the function returns an array containing the array of sequence numbers, then the step size between each number, as a single float.

I now have in VBA
```
Function xl_LinSpace(startnum As Double, stopnum As Double, n As Long, _ 
    Optional endpoint As Boolean = True, Optional retstep As Boolean = False)
    Dim rtn As Variant
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        xl_LinSpace = Py.CallUDF("xlwscipy", "xl_linspace", Array(startnum, stopnum, n, endpoint, retstep), ThisWorkbook)
        Exit Function
failed:
        xl_LinSpace = Err.Description
End Function
```
and in Python:
```
@xw.func    
def xl_linspace(startnum, stopnum, num, endpoint, retstep):
    rtn = np.linspace(startnum, stopnum, num, endpoint, retstep)
    return rtn
```
If I omit retstep, or set it to false, the function returns a 1xnum array, but if I set retstep to True I get:
Unexpected Python Error: TypeError: Internal error - the buffer length is not the sequence length!

Note that if I call the function from Python it works as expected, returning:
>>> x = xsp.xl_linspace(1,2,6)
>>> x
(array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ]), 0.2)

**Comment by DougAJ4** [comment]
Hi Felix,

I added a comment to the closed issue yesterday.

Just checking if you get notification, or if I should post as a new issue?
There still seems to be an issue returning an array, if it is not a regular
1D or 2D array.

Regards

Doug

**Comment by fzumstein** [comment]
I get the confirmation but havent had time to look into it yet. you can
also reopen the issue
Am 06.05.2016 20:30 schrieb "DougAJ4" <notifications@github.com>:
