### ISSUE TITLE
Mac Sheet Copy

### ISSUE THREAD

**Issue by phillippersley** [ZoomerAnalytics/xlwings#455]
I'm currently using the following workaround to copy sheets on Windows:

`
sh.xl_sheet.Copy()`

where sh is a Sheet object. 

Is there a way to do this on Mac?

**Comment by fzumstein** [comment]
This is the according syntax for appscript:

`xw.Sheet(1).xl_sheet.copy_worksheet(after_=xw.Sheet(1).xl_sheet)`
