### ISSUE TITLE
Writing out Pandas DataFrame subclassed object uses wrong converter

### ISSUE THREAD

**Issue by Notre1** [ZoomerAnalytics/xlwings#457]
I have a pd.DataFrame subclassed object that I was previously successfully writing to a Range.  After I upgraded xlwings to 0.7.1 (from 0.3.5) it started throwing an Exception when it came to the line that writes the data to the Range.

The Exception is `TypeError: Objects for SAFEARRAYS must be sequences (of sequences), or a buffer object.`  It is being raised at line 62 of the conversion\standard.py file.

Basically this fails:
`Range('A1').value = df_subclass `

But either of these work:
```
Range('A1').options(pd.DataFrame).value = df_subclass 
Range('A1').value = pd.DataFrame(df_subclass )
```

My object is a straight-forward subclass (just adding a metadata property) and `isinstance(df_subclass , pd.DataFrame)` returns `True`, so I thought that I might try to fix the problem myself and submit a pull request, but couldn't figure out where xlwings is detecting the data type.

**Comment by fzumstein** [comment]
The type is detected [here](https://github.com/ZoomerAnalytics/xlwings/blob/ae931099959edce807e3ee1ff5aa61d73216d232/xlwings/conversion/standard.py#L218) and hence it makes perfect sense that this doesn't work the way it used to work pre-v0.7.0.

Stating the Converter explicitly as you do here makes sense:
```
Range('A1').options(pd.DataFrame).value = df_subclass 
```

Alternatively, you can subclass the `xlwings.conversion.PandasDataFrameConverter` and register it as the default converter for your subclass (see also the docs on [Custom Converters](http://docs.xlwings.org/en/stable/converters.html#custom-converter)):

```
from xlwings.conversion import PandasDataFrameConverter

class DfSubclassConverter(PandasDataFrameConverter):
    pass

DfSubclassConverter.register(DfSubclass)
```

This then allows you to call it like that again:

```
Range('A1').value = df_subclass 
```

**Comment by fzumstein** [comment]
I am closing this issue, hope the solutions works. Please note that I edited the answer shortly after adding it, so if you've only looked at the email notification, make sure to check the simpler solution directly on GH.
