### ISSUE TITLE
0.7.1 RunFrozen - 'exe' is not recognized as an internal or external command]

### ISSUE THREAD

**Issue by rbn920** [ZoomerAnalytics/xlwings#460]
In 0.7.1 I am getting an error when trying to run a frozen script

`
    'foo.exe' is not recognized as an internal or external command,
    operable program or batch file.
`

I then froze it with 0.6.4 and all is fine.

**Comment by fzumstein** [comment]
This has been fixed in #452 on the develop branch and will be available with the next release (0.7.2)

**Comment by rbn920** [comment]
Thanks, sorry for opening another issue.
