### ISSUE TITLE
error 69

### ISSUE THREAD

**Issue by Neocurve** [ZoomerAnalytics/xlwings#465]
I cannot installed xlwings on pycharms . 
It is installed by conda , as well as pip install xlwings and received success message. 
but once I select xlwings from project interpreter on pycharms it comes with error 69 and not be able to import as such.

can you please help

**Comment by fzumstein** [comment]
Can you open a command prompt and try if the following works?

```
C:\Users\felix>python
Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import xlwings
>>> xlwings.__version__
'0.7.2'
>>>
```

**Comment by Neocurve** [comment]
Hi,

many thanks for the help. 
I'm sorry for my limited understanding in Python. 
but I'm using Mac for my work which I have problem with this package.
this morning I have tried xlwings on windows and works fine. but I have issue with Mac which I'm using at home.
your prompt commands are for windows ? as I have tried these and not working.

**Comment by fzumstein** [comment]
The commands look pretty much the same on a Mac Terminal: 

```
Felix:dev Felix$ python
Python 3.5.1 |Anaconda 2.5.0 (x86_64)| (default, Dec  7 2015, 11:24:55) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xlwings
>>> xlwings.__version__
'0.7.2'
>>> 
```

If you're having issues, we recommend to install de Anaconda distribution with default settings, as that will give you a working installation with xlwings already preinstalled.

**Comment by Neocurve** [comment]
thank you for update. 
It works on Anaconda,but I was baffled why it has an issue on PyCharms.
by the way, thanks again

**Comment by fzumstein** [comment]
All good then or are you still having issues on PyCharm? You need to point PyCharm (Settings) to use the correct Python interpreter.

**Comment by Neocurve** [comment]
not yet! there is nothing really especial on interpreter setting. Or maybe I have done something wrong. the only thing that I'm going to check, is the destination of xlwings installed by Anaconda and PyCharm. I couldn't figure it out. if you come with any solution for mac OS X that would be great. as I mentioned, it installed that on windows and works fine

**Comment by fzumstein** [comment]
If you can do from a Mac Terminal:

```
$ python
>>> import xlwings
>>> xlwings.__version__
0.7.2
```

Then it's a pure PyCharm issue. If that's not the case, please reopen the issue.
