### ISSUE TITLE
Writing large arrays to Excel times out appscript on Mac

### ISSUE THREAD

**Issue by asifkhalak** [ZoomerAnalytics/xlwings#466]
Hi-

I'd like to write a large array, but am having trouble with the mac Appscript internals timing out.  I found that there is a 'timeout' setting -- see example 6 in the following article  http://www.macdevcenter.com/pub/a/mac/2007/05/08/using-python-and-applescript-to-get-the-most-out-of-your-mac.html?page=last&x-showcontent=text

However, I'm having trouble changing the timeout setting...  For instance, the following times out after 120s, not 1800s.  

```
import numpy as np
import pandas as pd
import xlwings as xw

i = 1500
dx = pd.DataFrame(np.random.rand(i,i))
dx.columns = map(str, dx.columns)
wb = xw.Workbook()
wb.xl_workbook(timeout=1800)
xw.Range('Sheet1', (1,1)).table.clear_contents()
xw.Range('Sheet1', (1,1), header=True, index=False).value = dx
```

What's the correct way to change the timeout argument set in appscript for the assignment command?

**Comment by fzumstein** [comment]
My suggestion would be to use chunking instead of changing the timeout, see #77

**Comment by asifkhalak** [comment]
Thanks!
