### ISSUE TITLE
Excel addin not working.

### ISSUE THREAD

**Issue by fkalpa** [ZoomerAnalytics/xlwings#467]
trying to replicate the example on
https://www.youtube.com/watch?v=l_DgTxQ0aD8

I installed python using Anaconda distribution 32 bit on Windows 7 Professional
I just upgraded to xlwings-0.7.2 using "$>pip install --upgrade xlwings".

I created a folder in mydocs\PythonWings with 2 files: correl2.xlsm (similar 2D array like in video) and correl2.py (same code as in video). Once i hit the import Python UDFs button, I get "ImportError:Import by Filename is not supported" msgbox

the code stops in VBA in the xlwings module in the "ImportPythonUDFs()" subroutine at the following line:
tempPath = Py.Str(Py.Call(Py.Module("xlwings"), "import_udfs", Py.Tuple(scriptPath, ThisWorkbook)))﻿

**Comment by fzumstein** [comment]
Do you have the xlwings VBA module present in the correl2.xlsm file? see http://docs.xlwings.org/en/stable/vba.html#xlwings-vba-module

**Comment by fkalpa** [comment]
Yes. I added using the following instructions:
http://docs.xlwings.org/en/stable/vba.html

**Comment by fzumstein** [comment]
Can you download the udf.zip sample from the homepage (http://xlwings.org/examples/), unzip it and check if you get any error message when hitting Ctrl-Alt-F9? 

Then try to reimport the code?

**Comment by fkalpa** [comment]
i unzipped in a separate folder, hit Ctrl-Alt-F9 and all the blue cells return "Object doesn't support this property or method" . Same error message when hitting the GetWorkbookName button. 

I tried hitting import Python UDFs button and a msg box pops up with the message "WindowsError;[Error 2] The system cannot find the file specified u'udf
  return os.stat(filename).st_mtime
File 
  C:\Users\FK51891\AppData\Local\Continuum\Anaconda2\Lib\genericpath.py line 62, in getmtime
  mtime = os.path.getmtime(filename)"

**Comment by fkalpa** [comment]
i feel my installation may be corrupted. therefore, may i suggest posting a youtube video on how to install xlwings and a few steps on how to verify the installation is successful.
thanks for your help Felix

**Comment by fzumstein** [comment]
I would suggest to simply reinstall Anaconda: xlwings is already preinstalled there (although not in the latest version). So you would need to run `conda upgrade xlwings` or `pip install xlwings --upgrade` to get the latest version.

**Comment by fzumstein** [comment]
If on a command prompt you can do the following, that's already a good start:

```
C:\Users\felix>python
Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import xlwings
>>> xlwings.__version__
'0.7.2'
>>>
```

**Comment by fzumstein** [comment]
Closing this... please reopen if you need more help.
