### ISSUE TITLE
is mutating input array to UDF feasible?

### ISSUE THREAD

**Issue by denfromufa** [ZoomerAnalytics/xlwings#474]
e.g. using address of the range?

**Comment by denfromufa** [comment]
maybe using this https://github.com/ZoomerAnalytics/xlwings/issues/362#issuecomment-182474308

**Comment by fzumstein** [comment]
Can you please include a sample to clarify what you mean, thanks.

**Comment by denfromufa** [comment]
Public Function add2arr(Arr As Range, Bias As Double, Mutate As Boolean) As
String
    rc = Arr.Rows.Count
    cc = Arr.Columns.Count
    Dim Arr1 As Variant
    If Mutate Then
        Set Arr1 = Arr 'gives value error when set later
    Else
        ReDim Arr1(1 To rc, 1 To cc) As Double
    End If
    For r = 1 To rc
        For c = 1 To cc
            Arr1(r, c) = Arr(r, c) + Bias
            add2arr = add2arr + Str(Arr1(r, c))
        Next c
    Next r
End Function

**Comment by fzumstein** [comment]
As per Excel's design, you can't write outside of the Excel formula. We might provide a workaround one day as per #362
