### ISSUE TITLE
Workbook option in Sheet class initialisation ineffective

### ISSUE THREAD

**Issue by ndclt** [ZoomerAnalytics/xlwings#475]
I wanted to open two workbook at the same time and to be able to write in a non active one. I write a small test describing the matter.
config:
xlwings 0.7.2
Excel 2007

    # coding: utf8
    import unittest
    from xlwings import Workbook, Sheet, Range
    from pywintypes import com_error

    class TestBugSheet(unittest.TestCase):
        def setUp(self):
            self._origin = Workbook()
            self._destination = Workbook()

        def test_bug_sheet_init(self):
            origin_sheet = Sheet(1, wkb=self._origin)
            Range(origin_sheet, "A1").value = [["I am in the wrong Workbook"]]
            self._origin.close()
            result_sheet = Sheet(1, wkb=self._destination)
            self.assertEqual(Range(result_sheet, "A1").value, None)

        def tearDown(self):
            self._destination.close()
            try:
                self._origin.close()
            except com_error:
                pass

**Comment by fzumstein** [comment]
Thanks! That's a design issue of the current implementation, but it'll be fixed with the next bigger release (complete refactor).

**Comment by ndclt** [comment]
Thank you for the feedback.
