### ISSUE TITLE
Range won't take a variable with the R1C1 style format

### ISSUE THREAD

**Issue by bwlinux** [ZoomerAnalytics/xlwings#476]
xlwings 0.7.2, Excel 2016 Windows, Python 2.7.11

I have a worksheet that has a fixed number of columns but a varying number of rows.  When I populate the worksheet   I store the start row and end row in K1 and L1 which are hidden to the end user

If I dynamically build my range string like this...
`rangeStr = "(" + str(int(rowStart)) +",1),("+ str(int(rowEnd)) +",4)"`

and then try to call the Range function like this:
`xwDistancesList = Range('1. RallyMan Distances',rangeStr).value`

I get an error.  However if I hard code the values in the Range arguments it works.
`xwDistancesList = Range('1. RallyMan Distances', (6,1),(5556,4)).value`

debugging the code I think I have found the problem, thus it's a bug of sorts
line 661 of main.py running in debug reports:
![capture](https://cloud.githubusercontent.com/assets/3944481/15581551/74282f4c-2332-11e6-90e7-43e7d5ca71db.PNG)

Because python is passing the string rangeStr in quotes the function is only seeing 2 arguments instead of 3.  For R1C1 style your code expects
`'Sheet name', (6,1), (5556,4)`
yet it appears I'm passing 
`'Sheet name', '(6,1), (5556,4)'`

I can write a function to convert R1C1 style ranges to A1 style I guess, but I wanted to bring this to your attention.

**Comment by fzumstein** [comment]
Not sure I follow... why don't you just leave out all the `str` operations? Something like this:

`xwDistancesList = Range('1. RallyMan Distances',(rowStart, 1), (rowEnd, 4)).value`

**Comment by bwlinux** [comment]
Doh!!!!!    

Because I was over complicating things.  I thought I had to quote the range which I don't. 

Thanks for the quick response, sorry for the false report.
