### ISSUE TITLE
ImportPythonUDFs throws a run-time error '53' (xlwings 0.7.2)

### ISSUE THREAD

**Issue by quantvol** [ZoomerAnalytics/xlwings#485]
I've installed xlwings 0.7.2 with Anaconda2 (64-bit), using Excel 2010 (64-bit) on Windows 7.  I ran xlwings addin install and xlwings quickstart myproject.  But when I run ImportPythonUDFs  I get run-time error '53' File not found: xlwings64.dll.

I tried reinstalling xlwings using both conda and pip, I checked that the dll is in the same folder as pythonw.exe, I checked that  PYTHON_WIN = "", and I check that my Python path is set correctly.

Any ideas?  I was able to use xlwings successfully a couple months ago, I'm not sure what changed since then (besides updating conda and xlwings).  Any guidance would be appreciated.

**Comment by fzumstein** [comment]
If you download the `udf.zip` from http://xlwings.org/examples/ and hit Ctrl+Alt+F9, does it give you the same error?

**Comment by quantvol** [comment]
Yes, I get "File not found: xlwings64.dll"

**Comment by fzumstein** [comment]
Just to make sure you're not working with an old dll: is your `xlwings64.dll` of the size 336 KB?

**Comment by quantvol** [comment]
Yes, it's 336 KB

**Comment by quantvol** [comment]
I just did a clean install of Anaconda and xlwings now works.  Thanks for your help, I'll close the issue.
