### ISSUE TITLE
Error in Python --> empty error msg in Excel

### ISSUE THREAD

**Issue by sethor** [ZoomerAnalytics/xlwings#488]
Hi,
I have a fairly complicated Python code in which I am handling errors and giving them exit codes. However, when an error occurs in Python and the Python process ends with e.g. exit(10), the VBA part won't execute the ErrorHandler, but will throw an empty error message.
Is there a solution to this problem? I would really like to keep the exit codes in Python if it is possible.
Thank you very much for your help in advance!
Cheers,
Peter

**Comment by fzumstein** [comment]
Can you post a minimal example and how you are calling the code (RunPython, UDF)? You are on Windows, right?

**Comment by sethor** [comment]
Sure, I'm using RunPython and Windows:
RunPython ("import pythoncode; pythoncode.function1(" & param1 & ", '" & param2 & "', '" & param3 & "', '" & param4 & "', '" & param5 & "', '" & param6 & "')")

**Comment by fzumstein** [comment]
OK and what about function1, can you paste an example for that one?

**Comment by sethor** [comment]
Here is the relevant part:
...
try:
                ...some function...
except SomeError:
                ..logging...
                exit(10)
...

**Comment by fzumstein** [comment]
On windows, RunPython checks if the exit code is 0 and if not, it displays the error. We can probably add another check to see if the error log is empty to suppress that (which is more how it works on mac, too).

**Comment by sethor** [comment]
That would be really great, thank you very much!

**Comment by fzumstein** [comment]
Hey actually reading this again, wouldn't you want xlwings to display an error message in that case? and why don't you just reraise the exception in that case instead of using an exit code?

**Comment by sethor** [comment]
Hi,
I managed to solve this problem with a little workaround: it seemed that the emprty error msg only appears when the error originates from one of the side Python modules in an embedded try..except structure, so I just needed to change that structure in those modules.
I definitely need error codes as it is kind of a policy for code development for us.
