### ISSUE TITLE
only last of multiple open workbooks is accessed

### ISSUE THREAD

**Issue by haraldgsinger** [ZoomerAnalytics/xlwings#493]
import pandas as pd
import xlwings
print xlwings.__version__
# 0.7.2
from xlwings import Workbook, Range

df=pd.DataFrame([("test1")])
df.to_excel('test1.xlsx')

df=pd.DataFrame([("test2")])
df.to_excel('test2.xlsx')

wb1=xlwings.Workbook('test1.xlsx')
print Range('B2',wbk=wb1).value
# test1
wb2=xlwings.Workbook('test2.xlsx')
print Range('B2',wbk=wb2).value
# test2

print Range('B2',wbk=wb1).value
# test2

**Comment by fzumstein** [comment]
There's a typo in the keyword: it should be `wkb` instead of `wbk`. We're currently rewriting this part for the next release so it will handled like in Excel and without keyword.
