### ISSUE TITLE
ImportPython UDFs Error

### ISSUE THREAD

**Issue by davidl5** [ZoomerAnalytics/xlwings#494]
Hello

I am a beginner in Python.

I tried to execute a sample file called "udf.xlsm" to understand xlwings but I get an error message every time (see below) : [Error 2] The specified file can not be found

![capture](https://cloud.githubusercontent.com/assets/20070062/16235817/7269f970-37d6-11e6-88b2-a87ec26efe7d.JPG)

Can you help me to solve this issue ?

Thank you for your help.

David

**Comment by fzumstein** [comment]
Did you unzip the zip file before trying the example?

Also, when you open a command prompt and type the following, does it all work?

```
C:\Users\Felix>python
>>> import xlwings as xw
>>> xw.__version__
'0.7.2'
```

**Comment by davidl5** [comment]
The file is unzip and your previous command work.
I can read/write into Excel with Python using xlwings. The problem happen only when I try to use a Python function in Excel.

**Comment by fzumstein** [comment]
Does the Fibonacci sample work?

**Comment by davidl5** [comment]
When I click on "ImportPython UDFs" I have the same error.
When I click on the "Lite" button from Fibonacci, I get the following error message:
---------------------------
Error
---------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "h:\a recherche\python\xlwings-master\examples\fibonacci\fibonacci.py", line 31, in xl_fibonacci
    n = Range('B1').options(numbers=int).value
AttributeError: 'Range' object has no attribute 'options'
Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

**Comment by davidl5** [comment]
sorry for the police

**Comment by fzumstein** [comment]
Looks like it's going against an xlwings version < 0.7.2? Do you have multiple installations of Python?

**Comment by davidl5** [comment]
I have only the version 2.7

**Comment by nedwardsnae** [comment]
I'm also experiencing a similar issue to the OP, although I'm getting a different error message. Just installed xlwings 0.7.2 on a Win10 machine using Excel 2016 with the add-in installed. Clicking the "Import Python UDFs" button results in the error below being displayed.
![image](https://cloud.githubusercontent.com/assets/3097360/16270193/6148a79c-388d-11e6-9f7f-ffb8054e7bd4.png)
Calling the python functions from macros seems to work fine (can generate the fibonacci sequence by clicking on the "Lite" button in the sample), just seems to be the add-in not behaving correctly.

**Comment by denfromufa** [comment]
I wonder if python and excel bitness (32 or 64 bit) have to match for this
COM interop?

**Comment by fzumstein** [comment]
No, nothing to do with the bitness as things run out-of-process. xlwings supports a mix of any version of python with any version of Excel and any version of Windows.

**Comment by fzumstein** [comment]
@nedwardsnae check if a reboot of Windows helps. Also check if you get the same errors when do run the udf sample and hit `Ctrl+Alt+F9` (without importing).

**Comment by davidl5** [comment]
an idea to solve the problem ?

**Comment by fzumstein** [comment]
@davidl5 can you past the full path to your Python interpreter under `PYTHON_WIN` in the xlwings VBA module and see if running Fibonnacci Lite does give you the same error as before?

**Comment by nedwardsnae** [comment]
> check if a reboot of Windows helps

Done this, same error occurs.

> Also check if you get the same errors when do run the udf sample

Same error, here is what is displayed:
![excel_2016-06-22_15-42-34](https://cloud.githubusercontent.com/assets/3097360/16271011/3ab6ad42-3890-11e6-8496-2389af70d0e3.png)

When I click the button, the same error is displayed

> hit Ctrl+Alt+F9 (without importing).

Nothing happens/changes when I do this, unfortunately.

**Comment by fzumstein** [comment]
@nedwardsnae  this works for you as follows in a command prompt?
```
C:\Users\Felix>python
>>> import xlwings as xw
>>> xw.__version__
'0.7.2'
```

**Comment by nedwardsnae** [comment]
Yes:
![image](https://cloud.githubusercontent.com/assets/3097360/16271318/6c875e10-3891-11e6-836c-2e3004992595.png)

**Comment by davidl5** [comment]
I have an error almost similar:

---------------------------
Error
---------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "h:\a recherche\python\xlwings-master\examples\fibonacci\fibonacci.py", line 7, in <module>
    from xlwings import Workbook, Range
ImportError: No module named xlwings
Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

**Comment by fzumstein** [comment]
@davidl5 so there seem to be 2 issues: (1) the python installation that you want does not have xlwings installed and (2) the default python installation is also different from the version you want. You would need to put the python installation that you want on your path and make sure it has xlwings installed. My suggestion would be to simply reinstall Anaconda and make sure you have the checkboxes on the last installing step checked, see [here](https://github.com/ericremoreynolds/excelpython/issues/52#issuecomment-159319008)

**Comment by fzumstein** [comment]
@nedwardsnae can you please also check if you get the same error by pointing `PYTHON_WIN` to your Python interpreter, see above?

**Comment by nedwardsnae** [comment]
Oops - sorry for wasting your time @fzumstein. It seems that Python 3 was in my system path, and while running python in my command line invoked the 2.7 version, process monitor was showing the pythonw.exe from my python 3 installation being run. The excel plugin now works fine having removed that version from my path. Sorry and thanks for the help!

**Comment by davidl5** [comment]
I have just reinstall the last version of Anaconda with the checkboxes checked and I have still the same problem 
![image](https://cloud.githubusercontent.com/assets/20070062/16272397/f2d80cce-389d-11e6-8125-4513f65315e7.png)

**Comment by denfromufa** [comment]
@davidl5 maybe this has to do something with French :) what is the full filename in the error?

**Comment by davidl5** [comment]
[Error 2] The specified file can not be found.
The Excel file name is udf.xlsm

**Comment by fzumstein** [comment]
@davidl5 does the file path contain any non ascii characters like `é`?

**Comment by davidl5** [comment]
Only ascii characters and same error.

Why there is a "u" before the file name (tests_python) ?

![image](https://cloud.githubusercontent.com/assets/20070062/16303397/b99d998e-3950-11e6-9f5b-308b5320f09a.png)

**Comment by denfromufa** [comment]
'u' is for unicode strings.

**Comment by fzumstein** [comment]
What path do you get if you do the following in a command prompt:

```
python
>>> import sys
>>> sys.executable
'C:\\Users\\Felix\\Anaconda3\\python.exe'
```

**Comment by davidl5** [comment]
'C:\\Users\\levydav\\AppData\\Local\\Continuum\\Anaconda2\\python.exe'

**Comment by fzumstein** [comment]
When you do the following, what do you get?

```
cd C:\Users\levydav\AppData\Local\Continuum\Anaconda2
python
>>> import xlwings
>>> xlwings.__version__
```

**Comment by davidl5** [comment]
'0.7.0'

**Comment by davidl5** [comment]
do you have any idea please ?

**Comment by denfromufa** [comment]
did you try v0.7.2?

**Comment by davidl5** [comment]
I reinstall python/anaconda and the version 0.7.2 of xlwings
I get the following error message when I click on "ImportPython UDFs" 

![pic](https://cloud.githubusercontent.com/assets/20070062/16494209/b5d0ea98-3ee8-11e6-8a3d-fc8539cf3f1d.jpg)

thank you for your help

**Comment by fzumstein** [comment]
Looks like a bit of progress to me... can you try again with a fresh download of an unzipped UDF sample from the homepage? Alternatively, can you send me your Workbook and py file please? Email is on my profile.

**Comment by davidl5** [comment]
it's works !!!
thanks a lot for your help
