### ISSUE TITLE
Convert Excel Errors

### ISSUE THREAD

**Issue by ghost** [ZoomerAnalytics/xlwings#496]
Would be nice to be able to convert cells with errors similar to able to convert empty cells to a certain value
http://stackoverflow.com/questions/2424718/how-to-know-if-a-cell-has-an-error-in-the-formula-in-c-sharp

```
If you need to check for a specific CVErr value (e.g., #N/A), then you would first check to make sure that the data type is an Integer (Int32) and then check the specific value held by the cell, according to this table:
•-2146826281 = #Div/0!
•-2146826246 - #N/A
•-2146826259 = #Name?
•-2146826288 = #Null!
•-2146826252 = #Num!
•-2146826265 = #Ref!
•-2146826273 = #Value!

For example, your code could look like this:
enum CVErrEnum : Int32
{
    ErrDiv0 = -2146826281,
    ErrNA = -2146826246,
    ErrName = -2146826259,
    ErrNull = -2146826288,
    ErrNum = -2146826252,
    ErrRef = -2146826265,
    ErrValue = -2146826273
}
```

http://docs.xlwings.org/en/stable/converters.html

`convert_errors_all_to=''`, or `convert_errors_all_to=None`
`convert_error_value_to=None,` would leave the other error values in place
 `convert_error_name_to=None`,  would take precedence for name errors if the all errors was specified

**Comment by fzumstein** [comment]
for now we'll handle errors the same as empty cells, see https://github.com/ZoomerAnalytics/xlwings/pull/1060
