### ISSUE TITLE
performing excel operation without opening excelsheet

### ISSUE THREAD

**Issue by sunilvd89** [ZoomerAnalytics/xlwings#507]
I tried to do some excel operation, all works smooth, but i couldn't able to perform operation while the excel being closed.(like the reading and writing csv file works --> basically the csv file won't open but it will write and read the data from the csv file) 

Each time i'm doing some operation the workbook will open and then the function works.

**Comment by fzumstein** [comment]
xlwings is specifically to *program* and *interact* with Excel, so yes, you do need to have the file opened by Excel.

If you want to cut Excel out of the equation, you should look at the reader and writer packages such as: xlrd, xlwt, openpyxl and xlsxwriter. At some point we might enable the use of these packages through the xlwings API, but that's still merely an idea.

**Comment by WeiDuan1985** [comment]
@fzumstein  I am having a problem here that my excel workbook is .xlsb format, it doesn't supported by openxl, xlrd or xlwt. The file is too big so I can't open it then save it to a compatible format. I was hoping to utilize xlwings package to save it into too small files without opening the big file.

**Comment by fzumstein** [comment]
as stated above, xlwings can't help here. Try https://github.com/wwwiiilll/pyxlsb to see if it works - I haven't used it so far.

**Comment by arachid1** [comment]
Hello, any update on this feature? can you open interact with an xlsx file without opening it?

**Comment by fzumstein** [comment]
You will need to use a different library, see here to check out which one: https://www.excelpython.org/
