### ISSUE TITLE
[xlwings] @func problem

### ISSUE THREAD

**Issue by luizmauricio000** [ZoomerAnalytics/xlwings#508]
Hello everybody, i use xlwings addin and python 2.7. I'm trying to create a excel-function by python and this function OPENS ANOTHER WORKBOOK. 

The function should recieve as arguments a excel file path, a sheet and a column that we want to copy the first cell (line 1).

Lets show in steps:

1) I put the formula in excel with this arguments
`=COL_FROM_OTHER_EXCEL("C:\\teste_folder\\teste.xlsm"; "Sheet1"; 2)`

It means that we want to copy column 2 from sheet1 of C:\\teste_folder\\teste.xlsm

2) Show this error in the cell where i put the formula of the step 1

```
"AttributeError: 'NoneType' object has no attribute 'Name'
    return xl_workbook.Name
  File ""C:\Python27\lib\site-packages\xlwings\_xlwindows.py"", line 174, in get_workbook_name
    self.name = xlplatform.get_workbook_name(self.xl_workbook)
  File ""C:\Python27\lib\site-packages\xlwings\main.py"", line 183, in __init__
    wb_2 = xw.Workbook(file_path, app_visible = False)
  File ""C:\\Fundamentais.py"", line 15, in COL_FROM_OTHER_EXCEL
    ret = func(*args)
  File ""C:\Python27\lib\site-packages\xlwings\udfs.py"", line 179, in call_udf
    res = call_udf(script, fname, args, this_workbook)
  File ""C:\Python27\lib\site-packages\xlwings\server.py"", line 189, in CallUDF
    return func(*args)
  File ""C:\Python27\lib\site-packages\win32com\server\policy.py"", line 585, in _invokeex_
    return S_OK, -1, self._invokeex_(dispid, lcid, wFlags, args, None, None)
  File ""C:\Python27\lib\site-packages\win32com\server\policy.py"", line 282, in _invoke_
    return self._invoke_(dispid, lcid, wFlags, args)
  File ""C:\Python27\lib\site-packages\win32com\server\policy.py"", line 277, in _Invoke_"
```

Here is the python code
```
import xlwings as xw

# ===========================================================
# GET FIRST LINE OF SOME COLUMN FROM OTHER WORKBOOK
@xw.func
def COL_FROM_OTHER_EXCEL(file_path, sheetname, col_number):

	# ABRE O OUTRO WORKBOOK (2) E SETA A SHEET DE TRABALHO
	wb_2 = xw.Workbook(file_path, app_visible = False)
	sh_2 = xw.Sheet(sheetname, wkb = wb_2)

	# CASO TENHA SIDO SETADO UM INTERVALO
	return xw.Range(sh_2, (1, col_number))
```

I tryed everything. Any suggestions?

**Comment by fzumstein** [comment]
You must not return a Range, but values, i.e. `Range.value`. Also note that `app_visible=False` will hide all workbooks in that app, i.e. most probably also the one you're calling from (that part will be improved with the next version). Last, make sure you are calling the book with the correct path. In doubt, hardcode the path to test it out and make sure it opens properly.

**Comment by luizmauricio000** [comment]
@fzumstein Sure, i forgot to put .value after range. Anyway, its not the problem ;(
Path is correct. I dont know if it helps, but when i run from PyCharm it works weel, i.e., when in pycharm i call
```
 x = COL_FROM_OTHER_EXCEL("C:\\teste_folder\\teste.xlsm", "Sheet1", 2)
print(x)
```

it works right. When I call from excel (as my original post) the error occour.

**Comment by fzumstein** [comment]
You're right, this only works when the workbook is already open: this is an Excel UDF limitation, see: http://stackoverflow.com/a/7971112/918626
