### ISSUE TITLE
xlwings.Workbook.save() not working properly?

### ISSUE THREAD

**Issue by AshleyJackson** [ZoomerAnalytics/xlwings#509]
It comes back an error:

`TypeError: unbound method save() must be called with Workbook instance as first argument (got unicode instance instead)
`

Is this because I am attempting to save to a mapped network? Or is this something else?

**Comment by fzumstein** [comment]
Pleae post a minimial snippet that allow us to replicate the issue

**Comment by AshleyJackson** [comment]
I couldn't strip it any further than this without the issue disappearing.
[testing.txt](https://github.com/ZoomerAnalytics/xlwings/files/348879/testing.txt)

**Comment by fzumstein** [comment]
You can't use `xw.Workbook.save()`, you'll need to use `save` on a workbook object, e.g. 

```
wb = xw.Workbook(...)
wb.save(...)
```

**Comment by AshleyJackson** [comment]
I now see what I was doing wrong.
It now works perfectly.

Thank you.
