### ISSUE TITLE
Question: UDFs and large imports

### ISSUE THREAD

**Issue by avonmoll** [ZoomerAnalytics/xlwings#510]
I'm writing a fairly complicated plotting function and I'm importing some major modules (`numpy`, `pandas`, and `matplotlib`, iteself). Will these modules have to be loaded every time I want to generate this plot? In other words, does the Python kernel persist between calls to the UDF?

**Comment by fzumstein** [comment]
Yes, UDFs use a COM server that persist between calls, let us know if you experience any issues with your function!

**Comment by avonmoll** [comment]
A followup: is there a way to freeze a UDF or otherwise deploy this function to somebody who doesn't have Python? If I'm planning on freezing the Python, do I even need to be concerned with speed? (In other words, does freezing the Python into an executable relieve any slowness from importing modules since they get built with the .exe)? I apologize if the wording of my question is confusing!

**Comment by denfromufa** [comment]
related: https://github.com/ZoomerAnalytics/xlwings/issues/481

**Comment by fzumstein** [comment]
Feezing for UDFs is currently not supported, but freezing as such doesn't change anything how Python works under the hood, i.e. you shouldn't expect any changes in speed.
