### ISSUE TITLE
UDF won't return whole pd.DataFrame, only one value

### ISSUE THREAD

**Issue by chfischer** [ZoomerAnalytics/xlwings#511]
Hi
I am trying to return a pandas.DataFrame from an UDF.
I would expect it to return the whole dataframe.
Issue: I only returns the first value.

Reproduction Steps (minimal):
    
    import xlwings as xw
    import pandas as pd
    @xw.func
    def dfudf1():
        df = pd.DataFrame(np.random.randn(4, 4), columns=list('ABCD'))
        return df.values

The screenshot shows the (slightly modified) code, printed df from in python window, excel result (just one cell with data).
![2016-07-07 23_05_51-excel1 xlsm - excel](https://cloud.githubusercontent.com/assets/533865/16669932/373a826a-4498-11e6-92eb-5b4cbb0d0298.png)

**Comment by fzumstein** [comment]
You need to use an array formula, see [here](http://docs.xlwings.org/en/stable/udfs.html#array-formulas-get-efficient)

**Comment by spex66** [comment]
Is it necessary to know the size of the dataframe first?
I try the same as @chfischer , and I don't know how many rows my DF will return.
And I don't want to care about the column width too.

Is this possible?
@chfischer did you found a solution?
@fzumstein Felix do you have a hint?

thx
Peter
(=PA=)

**Comment by fzumstein** [comment]
Currently yes, you'd need to know the size, forced by Excel's design. We're currently working on an autoexpansion feature though that will work around this.

**Comment by WaylonWalker** [comment]
Has the autoexpansion feature been implemented?

**Comment by fzumstein** [comment]
http://docs.xlwings.org/en/stable/whatsnew.html#dynamic-array-formulas

**Comment by WaylonWalker** [comment]
Thanks.  I was using that same example from the UDF tutorial, but was only returning one cell.  Didnt realize that I had not updated xlwings in quite awhile.   Its working now.

Thanks!
