### ISSUE TITLE
How to obtain text from Text Box?

### ISSUE THREAD

**Issue by pybokeh** [ZoomerAnalytics/xlwings#520]
Hello.  I need to obtain text contained within an Excel text box.  I know how to obtain value/text from an Excel cell, but I need to obtain text from a text box.  Is this possible using xlwings?  Maybe use COM objects?  The problem is, I don't know how to identify the actual text box object that contains the text I want.  I can try to use Excel VBA or ask an Excel VBA expert to identify or provide me the name of that text box object.  If I have that, then how do I use xlwings to regerence the text box object name and obtain the text it contains?  Thanks in advance!

**Comment by fzumstein** [comment]
You can always fall back to the underlying packages as described [here](http://docs.xlwings.org/en/stable/missing_features.html).

In your case, this would look something like: `xw.Sheet(1).xl_sheet.TextBoxes("TextBox 1").Text`

**Comment by pybokeh** [comment]
Thanks, but I get this error:

https://gist.github.com/anonymous/778e850f74a6537877f0f557ea81eb00

**Comment by pybokeh** [comment]
From the VBA editor, I can do:

?Activesheet.textboxes("Text Box 1").text

So I did:
wb.active_sheet.xl_sheet.TextBoxes("Text Box 1").Text

or
wb.active_sheet.xl_sheet.TextBoxes("TextBox 1").Text

and still get errors.

Also tried:
wb.active_sheet.xl_sheet.TextBoxes(1).Text

or wb.active_sheet.xl_sheet.TextBoxes("1").Text

**Comment by pybokeh** [comment]
OK got it to work by accident.

If I add this line:
excel = win32.gencache.EnsureDispatch('Excel.Application')

Then it works.  I don't know why.

import win32com.client as win32
excel = win32.gencache.EnsureDispatch('Excel.Application')

**Comment by fzumstein** [comment]
Can you please paste a full snippet that works for you? thanks. You def. shouldn't need that win32com call

**Comment by pybokeh** [comment]
Here's my full script:
https://gist.github.com/anonymous/53f89239787da4ec693b37c06c638ae0

I can omit the call to:
win32.gencache.EnsureDispatch('Excel.Application')

and my script will still work.

**Comment by fzumstein** [comment]
Ok fair enough so it was only a name issue.

**Comment by rajappra** [comment]
Does it work in linux based machines?
