### ISSUE TITLE
open 2 files at a time

### ISSUE THREAD

**Issue by xxxspy** [ZoomerAnalytics/xlwings#535]
wb=xw.Book('C:/mygits/xlwings tutorial/data/05/example.xlsx')
this statment opens `C:/mygits/xlwings tutorial/data/05/example.xlsx` ,at the same time opens a file not saved .

**Comment by xxxspy** [comment]
xlwings.version : 0.9
platform:win7
python :2.7

**Comment by fzumstein** [comment]
duplicate #531
