### ISSUE TITLE
xw.Book() and xw.books.open() raise different error if file does not exist

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#540]
should be aligned

**Comment by Eupraxis** [comment]
xw.books.open("Test.xlsx") should open up this file if it isn't open. Right now just returning AttributeError. 
xw.Book("Test.xlsx") opens up Test.xlsx as expected.

**Comment by Eupraxis** [comment]
I cloned this to my Git and rand the unit tests. They work fine and now so does xw.books.open("Test.xlsx"). Seems something was causing my previous calls to xl.books.open() to attempt to reference a None object.

**Comment by fzumstein** [comment]
`xw.books` is the collection of the active app. If there's no Excel instance running, i.e. there's no app, it will not work. `xw.Book` is a convenience class that takes care of instantiating a new app if there isn't one yet.
