### ISSUE TITLE
Mac: Issue with mbcs with PY 2.7

### ISSUE THREAD

**Issue by lewis-jeffery** [ZoomerAnalytics/xlwings#544]
I have converted my existing code to xlwings v0.9.1 without problem, except for:

wb = xw.Book.caller()

I get "LookupError: unknown encoding: mbcs" in all cases, including the mpl example.   (Screen shot attached).

mac running 10.11.6 and Anaconda python 2.7

As an inelegant hack to get it running I have commented out a line in xlwings/main.py (fragment attached) and it works.

Appreciate your advice.

![screen shot 2016-08-08 at 7 47 07 am](https://cloud.githubusercontent.com/assets/20893322/17465589/87b9b878-5d3e-11e6-8ff7-73f75160877d.png)

main.py, from line 464

    def __init__(self, fullname=None, impl=None):
        if not impl:
            if fullname:
                if not PY3 and isinstance(fullname, str):
#
#                  fullname = unicode(fullname, 'mbcs')
#
                    fullname = unicode(fullname)
                fullname = fullname.lower()

**Comment by fzumstein** [comment]
Thanks for reporting! This is another little bug that sneaked during the rewrite - will be fixed with next release

**Comment by lewis-jeffery** [comment]
Felix,

Thanks for your quick response.

Regards,
Lewis

*Lewis Jeffery*
mobile:  +61 401 296 105
office:    +61 7 3102 4640

On 8 August 2016 at 8:14:18 AM, Felix Zumstein (notifications@github.com)
wrote:

Thanks for reporting! This is another little bug that sneaked during the
rewrite - will be fixed with next release

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZoomerAnalytics/xlwings/issues/544#issuecomment-238111939>,
or mute the thread
