### ISSUE TITLE
Mac: v0.9 cell referencing (accesses column instead of named range)

### ISSUE THREAD

**Issue by lewis-jeffery** [ZoomerAnalytics/xlwings#545]
I do not know if this is the intended behaviour, but it is different behaviour...

In v0.7
xw.Range(Sheetname, 'x').options(transpose=True).value = x
writes a column below the cell with the name 'x'

In v0.9 
xw.Range('x').options(transpose=True).value = x
writes column below the cell X1

Appreciate your advice...

Regards

**Comment by fzumstein** [comment]
It's a mac-specific bug, should also be fixed in the next release

**Comment by lewis-jeffery** [comment]
Thanks.   Look forward to it…

regards.

*Lewis Jeffery*
mobile:  +61 401 296 105
office:    +61 7 3102 4640

On 8 August 2016 at 4:38:17 PM, Felix Zumstein (notifications@github.com)
wrote:

It's a mac-specific bug, should also be fixed in the next release

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZoomerAnalytics/xlwings/issues/545#issuecomment-238153045>,
or mute the thread
