### ISSUE TITLE
Question: Excel Tables with some groups hidden

### ISSUE THREAD

**Issue by avonmoll** [ZoomerAnalytics/xlwings#552]
![image](https://cloud.githubusercontent.com/assets/4260850/17821459/c9d41ba6-661f-11e6-99f8-2393aec626fd.png)

Is there any way (either Excel VBA or within xlwings) to only import data which is actually visible? In the above example, I have an Excel table where I've un-selected "dog" from `Column1` and thus I'm only viewing rows 2, 4, and 5. When I load this data in xlwings I still get ALL the data, including row 3, which contains "dog" in `Column1`. I'd like my Python code to only consider only those items which are still in view.

I feel like this could be a VBA solution, but I'm not familiar enough with Excel's API.

**Comment by fzumstein** [comment]
You can fall back to pywin32 and check for each row if it is hidden or not, e.g. :

```
import xlwings as xw

sht = xw.sheets.active

for i in range(10):
    print(sht.api.Rows(i + 1).EntireRow.Hidden)
```

**Comment by avonmoll** [comment]
Perfect! Exactly what I was hoping for -- thank you!
