### ISSUE TITLE
can't copy one single column correctly [BUG]

### ISSUE THREAD

**Issue by weigalion** [ZoomerAnalytics/xlwings#553]
codes as following
`wbook.sheets[1].range((1,1), (3,1)).value = wbook.sheets[0].range((1,1), (3,1)).value`

you got the right data, but the data on sheet[1] were not in the single same column but in the single same row.

**Comment by fzumstein** [comment]
That's actually a feature, not a bug, see here: http://docs.xlwings.org/en/stable/datastructures.html#lists

to preserve orientation for 1d arrays use:

```
wbook.sheets[1].range((1,1), (3,1)).value = wbook.sheets[0].range((1,1), (3,1)).options(ndim=2).value
```
