### ISSUE TITLE
Expand: don't work when table has empty row 

### ISSUE THREAD

**Issue by sragons** [ZoomerAnalytics/xlwings#557]
hello,
I try to export an excel table to csv file.
I use expand function but when the table has an empty cell the function don't return all the lines.

Ex: In excel I have this table

```
col1   	col2
1		a
		b
3		a
```

The code 
`vals = sh.range(table_name).expand().value`

Return only the first line

**Comment by ericremoreynolds** [comment]
In xlwings table expansion is currently defined by expanding vertically until an empty space is found in the first column, and horizontally until an empty space is found in the first row. This reflects what Excel does using Ctrl+Shift+Down and Ctrl+Shift+Left.

As a workaround I can suggest selecting the current region instead:

    vals = sh.range(table_name).current_region.value

**Comment by sragons** [comment]
Thank you for your response. I didnt know ctrl+* fonctionnality.
And sorry my mistake.
Sebatien
