### ISSUE TITLE
Not able to retrieve caller cell address after 0.9.3 upgrade

### ISSUE THREAD

**Issue by prateek99** [ZoomerAnalytics/xlwings#558]
Am not able to get this working

    @xw.func
    @xw.arg('xl_app', vba='Application')
    def get_caller_address(xl_app):
        return xl_app.Caller.Address

Before the upgrade, i use to just say `Application(Workbook.caller()).Caller.Address` to get the details of the cell calling the udf.How is this done now , with application class no longer available?

**Comment by ericremoreynolds** [comment]
Hello,

Your code works just fine for me - perhaps you just need to re-click 'Import Python UDFs' to regenerate the VBA wrapper code.

Alternatively, your legacy code is equivalent to the following in version >=0.9

    xw.Book.caller().app.api.Caller.Address

The caller range is actually passed by default (under the surface) to all xlwings UDFs, and in future version we will improve the API to allow you to access that information more easily.

**Comment by prateek99** [comment]
Hey Eric - 

xw.Book.caller().app.api.Caller.Address - sails through neatly.Isn't there any documentation on this?

But out of curiosity, I wonder if my earlier usage would work "Application(Workbook.caller()).Caller.Address"

I don't see the application class defined anymore, so if i do a "from xlwings import Application, Workbook" now , it righty gives me an error

**Comment by ericremoreynolds** [comment]
Sure there is,

* [Book.app](http://docs.xlwings.org/en/stable/api.html#xlwings.Book.app)
* [App.api](http://docs.xlwings.org/en/stable/api.html#xlwings.App.api)

and also various new features are documented in the [migrate to v0.9 guide](http://docs.xlwings.org/en/stable/migrate_to_0.9.html).

The `Application` class has been renamed `App`, but it's true that this isn't explicitly mentioned in the migration guide.
