### ISSUE TITLE
app_target

### ISSUE THREAD

**Issue by surfmaverick** [ZoomerAnalytics/xlwings#560]
I use XLWINGS on a mac and need the app_target option so that I can specify the version on the mac to run -- otherwise it tries to run the version in parallels, which is wrong. Is this feature still available?

**Comment by surfmaverick** [comment]
P.S. Here is the error I am getting.  Just upgraded with Anaconda Navigator. P.M. me for envrionment specs if needed.

appscript.reference.CommandError: Command failed:
		OSERROR: -2710
		MESSAGE: OS error
		OFFENDING OBJECT: k.workbook
		COMMAND: app(pid=1637).make(new=k.workbook)

**Comment by surfmaverick** [comment]
!never midn -- figured out that it is now in xlwings.App(spec = ...)

**Comment by fzumstein** [comment]
Right, searching here helps: http://docs.xlwings.org/en/stable/migrate_to_0.9.html#cheat-sheet
