### ISSUE TITLE
Particular arg name causing RuntimeError -2147467259 (80004005) on ImportPythonUDFs

### ISSUE THREAD

**Issue by su79eu7k** [ZoomerAnalytics/xlwings#563]
```
>>> xlwings.__version__
'0.10.0'
```

**udf.py**

```
import xlwings as xw

@xw.func
@xw.arg('currency')
def arg_name_test(currency):
    return "arg name currency Success"
```

**udf.xlsm**

And then when I try to run ImportPythonUDFs macro, I got runtime error like below screenshot.

![image](https://cloud.githubusercontent.com/assets/6040191/18716876/427aa478-8059-11e6-8f7c-1c60cb7a65fe.png)

Tested on both Excel2016/Win10 & Excel2010/Win7.

I found arg name 'currency' only. Could you please check this whether it's intended or not? Couldn't find any documentation related to this. Many thanks for great library by the way.

**Comment by fzumstein** [comment]
You're right, `currency` is a reserved name in VBA and can therefore not be used. This topic has come up before and we might at some point add a check, see #384. I am closing this, if you have any additional comment, please continue directly in the other issue. thanks.
