### ISSUE TITLE
Automation Error while importing UDF into Excel

### ISSUE THREAD

**Issue by vineethbabu4424** [ZoomerAnalytics/xlwings#566]
i created a file using the "xlwings quickstart" command and added the following function in the python file

```
@xlw.func
def add(x,y):
     return 2 * (x+y)
```

when i try to import this udf into the excel file, i get a Runtime error 440 Automation error

I am using Python 3.5.2 (32 bit )
![error message](https://cloud.githubusercontent.com/assets/13961736/19107352/d8f33cbe-8afc-11e6-928b-72cc9ca179fd.jpg)
![vba line in error](https://cloud.githubusercontent.com/assets/13961736/19107351/d8f32166-8afc-11e6-95c7-cc1d11b2e8f9.jpg)

 my excel is 32 bit pro plus

**Comment by fzumstein** [comment]
When you download the Fibonacci sample from the homepage, does that work?

**Comment by vineethbabu4424** [comment]
Hi Felix,

yes, this works

Vineeth

**Comment by fzumstein** [comment]
ok what about the UDF sample then? if you open it and hit `Alt-Ctrl-F9`?

**Comment by vineethbabu4424** [comment]
hi,

when i use Alt-Ctrl-F9, i can see the numbers recalculating, but in the same UDF book, if i click on Import Python UDF, i get the same Automation Error message

vineeth

**Comment by fzumstein** [comment]
If you hit `Alt-F8` and run `ImportPythonUDFs` from the menu instead of from the addin, do you get the same error? If yes, can you type `?Err.Description` into the VBA Immediate window when the code breaks?

**Comment by vineethbabu4424** [comment]
Hi
 Running the macro using Alt-F8 produces the same error, ?Err.Description on immediate pane outputs "Automation error"

**Comment by ayemjay** [comment]
I received same error when my sheet had an existing named range assigned with same name as my function.

**Comment by su79eu7k** [comment]
Please check  trust access to the VBA project object model option (File > Options > Trust Center > Trust Center Settings > Macro Settings). In my case, even though functions in cell(excel) works well, similar thing happened from above case when I try to execute macro. Or also similar error occurs when you are using function/arg name reserved by excel.

**Comment by vineethbabu4424** [comment]
hi,

that works, thank you for your support

vineeth

**Comment by fzumstein** [comment]
Which version of Excel are you using, @vineethbabu4424 ? That error should be shown explicitly.

**Comment by vineethbabu4424** [comment]
i'm using Excel 2013 pro plus 32 bit

vineeth

**Comment by fzumstein** [comment]
were you ever able to make it work?

**Comment by ilrico** [comment]
I had this message for various reasons:
- check as stated here that your Trust center policies are ok. For me checking "Trust access to the VBA object model" usually solves the issue
- check that your python functions/subs do not interfere with Excel reserved keywords in the signature (for instance def my_function(id=None, date=None) would fail since date is XL keyword. def my_function(id=None, dt=None) would be ok...)

**Comment by fzumstein** [comment]
Closing this issue as I assume one of the suggestion by ilrico solved it. Feel free to reopen.

**Comment by SvenneRag** [comment]
Hi 

I experience this problem when I add a controlformat object (a dropdown box) in my code and I reference that in my py-code. Example:

testDropDown = xw.Book('LineLimitViewer.xlsm').sheets("Front").api.Shapes("TestDropDown").ControlFormat

Do you have an example (or reference to your course material ;-)) which can guide me?

(Before I add the reference to the dropdown there is no problems?

Thx in advance

**Comment by lucaspenna00** [comment]
> Please check trust access to the VBA project object model option (File > Options > Trust Center > Trust Center Settings > Macro Settings). In my case, even though functions in cell(excel) works well, similar thing happened from above case when I try to execute macro. Or also similar error occurs when you are using function/arg name reserved by excel.

I had the same issue. I used an argument called "date" in my UDF function. I suppose it's a reserved name by Excel. I changed the argument name and it worked. Thks a lot.
