### ISSUE TITLE
ImportPythonUDFS throws a run-time error '53'

### ISSUE THREAD

**Issue by Faseeh16** [ZoomerAnalytics/xlwings#579]
Hello there,

I have 32 bit Windows XP, with Python27 and I am using Notepad++ to compile my code (No anaconda).

I recently insetalled xlwings and it is giving runtime error 53 when i try to import udf. I have searched the forum and found that i need to check the local of xlwings32.dll and xlwings64.dll file and i have found that they are in the same folder as python.exe. Another suggestion was to uninstall and delete both dll files and remaing files/folder of xlwings from site-packages, I have also tried that and uninstalled and delted the left-over folders, and reinsetalled. But it is still giving me the samek error. I have also checked the size of dll file and it is 336kb. 

Kindly help me solve this issue.

(Pardon my ignorance with the rules of this community, if i have violated one : ) 
![untitled_3](https://cloud.githubusercontent.com/assets/23115342/19798340/d3d3c77a-9d09-11e6-9a78-7f768e9dd104.JPG)

Thank you. 
Faseeh

**Comment by fzumstein** [comment]
Can you go through the 5 bullet points in my comment here? https://github.com/ZoomerAnalytics/xlwings/issues/574

**Comment by Faseeh16** [comment]
Thank you for replying. I have checked it one by one:
- writing import xlwing does work.
-I downloaded fibaconni file from the website and it gives the following error message: "python is not recognized as an internal or exeternal command, operable program or batch file" when i press whether i press Lite button or standalone button.
- both files xlwings64.dll and xlwings32.dll  are in same folder (please see picture in last post)
-I have changed the setting of PYTHON_WIN to where my phthon.exe is located. it is "C:\Python27\python.exe but it is not working.

Please see if i am doing something wrong. Thank you

**Comment by fzumstein** [comment]
what is the error msg you get when pointing to the python interpreter (last bullet point in your answer above)?

**Comment by Faseeh16** [comment]
when i run the code in VBA it gives Run-time error '-2147467259' Import error: No module named book2.

**Comment by Faseeh16** [comment]
I get this error Run-time error -2147467259, Import Error: No module named Book2

**Comment by fzumstein** [comment]
what's the version of xlwings you're using? (`import xlwings` and `xlwings.__version__`)

**Comment by Faseeh16** [comment]
It is 0.10.0

**Comment by Faseeh16** [comment]
Hello sir

**Comment by Faseeh16** [comment]
Update2: 
All of the stated issues has been resolved. I needed to press the import udf button twice. Thank you very much for support. This thread can be closed.
