### ISSUE TITLE
macros need an argument to execute properly?

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#580]
See http://stackoverflow.com/questions/40201831/possible-bug-xlwings-cannot-run-an-excel-macro/40244945?noredirect=1#comment67769320_40244945

**Comment by Brad-eki** [comment]
This is working. There is a miscommunication in the stackoverflow report.

The stackoverflow reporter is not catching the macro method and then running it and the explanation only uses an example with an argument.

stackoverflow question:
```python
import xlwings

wb = xlwings.Book('C:\\Book.xlsm')
wb.macro('Test')
print('done.')
```

Doco in code (main.py):
```python
import xlwings as xw
wb = xw.books.active
my_sum = wb.macro('MySum')
my_sum(1, 2)
```

To settle the stackoverflow:
```python
import xlwings

wb = xlwings.Book('C:\\Book.xlsm')
test_macro = wb.macro('Test')
test_macro()
print('done.')
```

**Comment by Brad-eki** [comment]
I just signed up to stackoverflow so I can't put that comment on the issue.
