### ISSUE TITLE
v0.10+Canopy 1.7.4: Crash on pictures.add() with new Canopy version

### ISSUE THREAD

**Issue by ssclift** [ZoomerAnalytics/xlwings#581]
I get a crash in the Python "kernel" when I call pictures.add() with a Matplotlib object.  This was working under a previous version of Canopy with XLWings 0.10.

The Windows help files are fairly unhelpful, no stack trace that I can identify.  I've not attached it since it contains some sensitive info. The error returned to Excel is "Run-time error '6' Overflow".

The crash occurs both when run from Excel and run from a standalone ipython session.  The update=True or False makes no difference.  Picture names and options don't seem to affect the crash, I stripped it down to:

        th_fig = p3nb.barplot_fig( mc.sim['total'], 'Total', mc.O_scen )
        th_plot = rsh.pictures.add( th_fig )

and the crash occurs on the pictures.add() statement.  To this point in the script numerous individual cells are updated, suggesting xlwings is behaving as expected to that point _(and xlwings has been great to this point, super product, BTW :-) )_.

This seems to be associated with the current 1.7.4 version of Canopy, and did not occur with an older version.  This vaguely suggests, to me, a linking issue with an associated library.  The only requirement I've seen that might be different is SciPy 0.18, which ships with the current Canopy, where I was using 0.17 before, but that's just a guess.

Environment is:

   * Windows 7 and 10,
   * Canopy Python 1.7.4.3348 (32-bit and 64-bit)
   * Excel 16.0 (Office 365 local install)
   * XLWings 0.10.

**Comment by fzumstein** [comment]
Can you please provide a small self contained example so I can try to replicate the issue? thanks

**Comment by ssclift** [comment]
Gruezi!

The script in test.txt attached fails for me as illustrated by the screenshot.  The string "Result" does get written to cell A2 as expected, but the pictures.add() statement triggers a Python crash.

Vielen Dank,
-- Simon

[test.txt](https://github.com/ZoomerAnalytics/xlwings/files/578722/test.txt)
![xlwings_bug](https://cloud.githubusercontent.com/assets/2293884/20107245/c581df8c-a5a5-11e6-9f16-2ccb0b6c3a94.png)

**Comment by fzumstein** [comment]
I can't duplicate it so I guess it's a Canopy issue and I suggest you take it up with them (or switch to Anaconda). The only other thing I can imagine is that there's an issue with the tempfile where the matplotlib figure is saved:

```
import tempfile
temp_dir = os.path.realpath(tempfile.gettempdir())
```

By the way, you should adjust your code to follow the redesign (i.e. don't import `Sheet`):

```
wb  = Book( ... )
rsh = wb.sheets("Sheet1")

rsh.range( 'A2' ).value = "Result"
```

**Comment by fzumstein** [comment]
closing this issue as I think it's a Canopy issue. Feel free to reopen if you think differently.
