### ISSUE TITLE
Error 1000 when importing UDFs

### ISSUE THREAD

**Issue by apdiazv** [ZoomerAnalytics/xlwings#583]
I am experiencing a similar problem to the one discussed on ImportPython UDFs Error #494. I see that in that case the issue was solved but there's no hint as to how to proceed. I am getting the following error when I try to import a UDF in Python (I am running Excel 2010 on WIn 10):
<img width="383" alt="captura de pantalla 2016-11-14 a las 9 08 02 a m" src="https://cloud.githubusercontent.com/assets/9203706/20264423/3fb345fe-aa4a-11e6-98d8-2509308bb236.png">

Any help would be much appreciated.

**Comment by fzumstein** [comment]
Can you go through the 5 bullet points in my comment here? #574

**Comment by apdiazv** [comment]
The problem is solved when I do bullet point #5. I have in fact a Python3 installation (not Anaconda) which happens to be the default on my system. Thanks a lot.
