### ISSUE TITLE
Save matplotlib picture as a file

### ISSUE THREAD

**Issue by aglove2189** [ZoomerAnalytics/xlwings#584]
The below script works outside of an xlwings call, but inside of one it does not save the file:

```
import matplotlib.pyplot as plt

X = [1,2,3,4,6]
Y = [1,5,8,2,9]

plt.plot(X,Y)
plt.savefig('Test.png')
plt.show()

```

**Comment by fzumstein** [comment]
I think you need to set the backend explicitly, can you try something like this:

```
import matplotlib as mpl    
canvas = mpl.backends.backend_agg.FigureCanvas(myfigure)
canvas.draw()
myfigure.savefig('myfilename', format='png')
```

**Comment by aglove2189** [comment]
Appreciate the quick reply, this is what I ended up using. It was saving the picture file into 'C:\users\username\Documents' even when specifying a different location, so I changed the working directory back to where the python file sits. If you have other suggestions please let me know and thanks again!

```
from matplotlib.backends.backend_agg import FigureCanvas
import matplotlib.pyplot as plt
import os

py_path = os.path.dirname(os.path.abspath(__file__))
os.chdir(py_path)

X = [1,2,3,4,6]
Y = [1,5,8,2,9]

fig = plt.figure()
plt.plot(X,Y)

canvas = FigureCanvas(fig)
canvas.draw()
fig.savefig(os.getcwd() + '\\test.png', format='png') 
```

**Comment by fzumstein** [comment]
Yeah makes sense, as we currently don't handle the working directory when called from Excel.
