### ISSUE TITLE
after upgrade from version 0.7 to 0.10, xlwings has become slow (1 min to 10 minutes)

### ISSUE THREAD

**Issue by kaiaeberli** [ZoomerAnalytics/xlwings#585]
Hi,

I recently upgraded from version 0.7 to 0.10, and noticed my code execution time moved from 1 min to about 10 minutes. I tried the "raw" option but no impact.

I run a loop in excel, checking for every row if some criteria is met.

```
while rgRef.value != None:
   if rgRef.offset(0,1).value != rgRef.offset(-1,1).value:
      # do sth
```

There are a few criteria like this.

Any ideas?

Many thanks,
Kai

**Comment by fzumstein** [comment]
Can you post a self-contained example that allows us to replicated the difference with 0.7 and 0.10? On the other hand, you should always read in the whole range into python in one go, the loop over it on the python side and write back the whole result range again in one go.

**Comment by fzumstein** [comment]
closing this as it's a duplicate of #568 , please continue there if you want to post a self contained sample that shows the differences described.
