### ISSUE TITLE
import module from path in RunPython

### ISSUE THREAD

**Issue by pmesgari** [ZoomerAnalytics/xlwings#586]
I want to import my module from a different directory than ActiveWorkbook resides, the reason is I want to use xlwings in my Excel add-in which resides in `C:\Users\MyName\AppData\Roaming\Microsoft\AddIns`
my add-in is used globally in Excel, so when I open an Excel file from `C:\MyExcel\MyWorkbook.xlsx` the import fails unless the python file is also in the same folder as Excel file, but I want to keep it in the same location as the add-in so that I don't have to copy the python file everywhere I use Excel. I  tried this solution but did not workout, the line becomes red in VBA and can not run:
```
RunPython ("importlib.util;spec=importlib.util.spec_from_file_location("'world'", "'C:\Users\Payam\AppData\Roaming\Microsoft\AddIns'";foo=importlib.util.module_from_spec(spec);spec.loader.exec_module(foo);foo.world()")
```

**Comment by fzumstein** [comment]
You need to either place your module on somewhere on Python's search path, .e.g on in `site-packages` or you need to add the path with your source file in the VBA settings under `PYTHONPATH`, see: http://docs.xlwings.org/en/stable/vba.html#settings

**Comment by fzumstein** [comment]
closing this. feel free to reopen if you need more assistance.
