### ISSUE TITLE
OSError: [Errno 22] Invalid argument on call to pywintypes.Time(0)

### ISSUE THREAD

**Issue by Colin-b** [ZoomerAnalytics/xlwings#592]
Hi,

The following line within _xlwindows.py is failing with Python 3.6.
`time_types = (dt.date, dt.datetime, type(pywintypes.Time(0)))`

Here is the issue:

Python 3.6.0b4 (default, Nov 22 2016, 05:30:12) [MSC v.1900 64 bit (AMD64)] on win32

`import pywintypes`

`pywintypes.TimeType`

> <class 'pywintypes.datetime'>

`pywintypes.Time(0)`

> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
> OSError: [Errno 22] Invalid argument

I am not sure what to do here exactly, the comment before this line of code is saying the following:

> Time types: pywintypes.timetype doesn't work on Python 3

Is it a known issue? 
If so should we use pywintypes.TimeType instead? 
Only for Python3? 
Or only in case of failure?

Anyway this issue is preventing to use xlwings on my setup with Python 3.6

Best Regards

**Comment by fzumstein** [comment]
`pywintypes.TimeType` seems indeed to be the correct solution, I fixed it on develop
