### ISSUE TITLE
[improvement] Import UDFs from directory and subdirectories

### ISSUE THREAD

**Issue by ymzkala** [ZoomerAnalytics/xlwings#594]
Hi,

The current setup allows me to specify specific .py files (in one folder) to import UDF's from. I would like to import all .py files from a directory and its sub-directories using just the parent directory path. I have been able to write a VBA function to get all the .py files in the parent directory, but I need to be able to import from sub-directories as well. That is where I will need help, either with an update or some guidance on how to tweak the module.

My function (listfiles) basically gets the names of the .py files in the parent directory, concatenates them (without the extensions) in a single string, and then I assign that value to "UDF_MODULES" variable in the "Settings" Function. Dealing with sub-directories would have to involve me changing other functions.

Function listfiles(ByVal sPath As String)
    ' Get list of .py files and concatenate into a single string for xlwings settings
    ' UDF_MODULES variable

    Dim vaArray     As Variant
    Dim i           As Integer
    Dim cc          As Integer
    Dim oFile       As Object
    Dim oFSO        As Object
    Dim oFolder     As Object
    Dim oFiles      As Object
    Dim cnt         As Integer
    Dim vaArray2    As Variant
    Dim num1        As Integer
    Dim num2        As Integer
    Dim vaArray3    As Variant

    Set oFSO = CreateObject("Scripting.FileSystemObject")
    Set oFolder = oFSO.GetFolder(sPath)
    Set oFiles = oFolder.files

    ReDim vaArray(1 To oFiles.Count)
    i = 1
    For Each oFile In oFiles
        vaArray(i) = oFile.Name
        i = i + 1
    Next
    num1 = i - 1 ' length of array 1
    
    ' Get list of files with .py extension
    cnt = 1
    For cc = 1 To num1
        If InStr(vaArray(cc), ".py") > 0 Then
            cnt = cnt + 1
        End If
    Next
    num2 = cnt - 1 ' length of array 2
    
    ReDim vaArray2(1 To cnt - 1)
    cc = 1
    cnt = 1
    For cc = 1 To num1
        If InStr(vaArray(cc), ".py") > 0 Then
            vaArray2(cnt) = Left(vaArray(cc), Len(vaArray(cc)) - 3)
            cnt = cnt + 1
        End If
    Next
    
    ' Concatenate strings
    cc = 1
    cnt = 1
    For cc = 1 To num2
        If cc = 1 Then
            vaArray3 = vaArray2(1)
        Else
            vaArray3 = vaArray3 & ";" & vaArray2(cc)
        End If
    Next
    
    listfiles = vaArray3
End Function

Thanks!
Yahia

**Comment by Colin-b** [comment]
Hi,

Did you tried using import statements within the init Python file in your
module folder?

Best Regards

**Comment by fzumstein** [comment]
This would have been my suggestion, too: do it on the Python side.

**Comment by ymzkala** [comment]
That works for me. Thanks!
