### ISSUE TITLE
Import Python UDFs failed

### ISSUE THREAD

**Issue by vincent-trupin-SG** [ZoomerAnalytics/xlwings#596]
After creating the quickstart "myproject" and clicking on "import Python UDFs", I get the error below :

![image](https://cloud.githubusercontent.com/assets/24523302/21098766/a7c15234-c062-11e6-894f-914a9211db37.png)

I followed the five resolution steps from the issue https://github.com/ZoomerAnalytics/xlwings/issues/574

1. import of xlwings is working.

2. UDF sample is not working. I get the error : 
![image](https://cloud.githubusercontent.com/assets/24523302/21098931/8ccb33f4-c063-11e6-978b-4c9dbc0e9a2a.png)

3. Trust access to the VBA project object model under File > Options > Trust Center > Trust Center Settings > Macro Settings is enabled

4. xlwings64.dll and xlwings32.dll in the same folder as the interpreter (python.exe)

5. Setting the full path to the interpreter in the Setttings Function in the VBA code doesn't solve the issue. 

I am using Excel Pro Plus 2013 on windows 7 and xlwings 0.10.1 installed with anaconda

**Comment by vincent-trupin-SG** [comment]
I finally managed to have it working by using the an admin account. 
Is there any specific right required to activate the RPCserver ?

**Comment by fzumstein** [comment]
It shouldn't require admin rights.

How exactly were you doing it? using an own windows account with admin rights?

**Comment by vincent-trupin-SG** [comment]
No it is two separate account. user account on the computer is not working. 
With a normal user account I got the error reported above. 
I finally install xlwings and run the myproject excel file with an admin account and only then it is working for us.

**Comment by vincent-trupin-SG** [comment]
hum... It even stranger than I thought. If we elevated the user account to be local admin on the computer, it is still not working for the user. But it is also not working when running excel with an admin account.

**Comment by vincent-trupin-SG** [comment]
Just an update on this as it might help somebody.

Our issue was related to the Application Management service being disabled for user account. 
Issue was resolved just by enabling the service.
