### ISSUE TITLE
caller no longer available?

### ISSUE THREAD

**Issue by simonm3** [ZoomerAnalytics/xlwings#598]
I had a logging handler that writes the log to sheet in the calling workbook. This was working with xlwings version 0.7. However having recently upgraded 0.10 it no longer worked. I changed Workbook to Book. However I get error "Workbook.caller must not be called directly. Call through Excel". I am calling it through an excel macro so what am I doing wrong? How can I access the calling workbook.

**Comment by simonm3** [comment]
Somehow got it working......but not sure how so I won''t elaborate!

**Comment by fzumstein** [comment]
0.9 changed the syntax for mock caller, check out the at the bottom of the cheat sheet in the migration guide: http://docs.xlwings.org/en/stable/migrate_to_0.9.html#cheat-sheet
