### ISSUE TITLE
import error in python 3.6.0 and suggested correction

### ISSUE THREAD

**Issue by koontzreader** [ZoomerAnalytics/xlwings#601]
From Python 3.6.0 IDLE session, same error in PowerShell, to check why I am receiving error while trying to import xlwings 0.10.1:

Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.

>>> import xlwings
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python36\lib\site-packages\xlwings\__init__.py", line 22, in <module>
    from . import _xlwindows as xlplatform
  File "c:\Python36\lib\site-packages\xlwings\_xlwindows.py", line 44, in <module>
    time_types = (dt.date, dt.datetime, type(pywintypes.Time(0)))
OSError: [Errno 22] Invalid argument

>>> import pywintypes

>>> pywintypes.Time(0)
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    pywintypes.Time(0)
OSError: [Errno 22] Invalid argument

>>> help(pywintypes.Time)
Help on built-in function Time in module pywintypes:

Time(...)

>>> pywintypes.Time((0,))
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    pywintypes.Time((0,))
TypeError: function takes at least 9 arguments (1 given)

Try tuple with 2 args

>>> pywintypes.Time((0,0))
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    pywintypes.Time((0,0))
TypeError: function takes at least 9 arguments (2 given)

That's the answer: Need 1 tuple with 9 arguments

>>> pywintypes.Time((0,0,0,0,0,0,0,0,0))
pywintypes.datetime(1999, 11, 30, 0, 0)

>>> pywintypes.Time(0,0,0,0,0,0,0,0,0)
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    pywintypes.Time(0,0,0,0,0,0,0,0,0)
TypeError: function takes exactly 1 argument (9 given)

Must be tuple -> takes exactly 1 argument (9 given)
 
Correction applied -->
Line 44 from Python36\Lib\site-packages\xlwings\_xlwindows.py
	time_types = (dt.date, dt.datetime, type(pywintypes.Time(0)))
Replaced with
	time_types = (dt.date, dt.datetime, type(pywintypes.Time((0,0,0,0,0,0,0,0,0))))

Result in IDLE -->
>>> import xlwings as xw
>>> xw.__version__
'0.10.1'
>>> 

---------------
Additional Info
---------------

The pywin32 I installed is from
Unofficial Windows Binaries for Python Extension Packages
by Christoph Gohlke, Laboratory for Fluorescence Dynamics, University of California, Irvine.
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pywin32
file: pywin32-220.1-cp36-cp36m-win_amd64.whl
(Extremely simple compared to the SourceForge file.)

After install, ran from PowerShell prompt
python.exe Scripts\pywin32_postinstall.py -install
as instructed in the listing description.
(Actually: PS C:\python36> .\python .\scripts\pywin32_postinstall.py -install)
 
Windows 10 Home Edition
64-bit operating system, x64-based processor
Version 1607
OS Build 14393.576

**Comment by fzumstein** [comment]
Hi, this is a duplicate from https://github.com/ZoomerAnalytics/xlwings/issues/592 and should have been fixed on the develop branch. I will release a new version this weekend! Sorry for the delay.

**Comment by fzumstein** [comment]
done
