### ISSUE TITLE
Choosing the Python backend installed on the Linux Subsystem of a Windows 10 machine.  Possible?

### ISSUE THREAD

**Issue by xjdeng** [ZoomerAnalytics/xlwings#612]
I've installed Tensorflow using the Linux subsystem on my Windows 10 machine  Is there any way I can specifically use this python backend and not a native Windows python backend?  

I'm interested in launching some programs that use Tensorflow from inside Excel, but Tensorflow cannot be installed natively in Windows (though I hear it may work for python 3.5.)

**Comment by fzumstein** [comment]
No, you can only talk to a windows hosted Python installation. My suggestion is to use miniconda or Anaconda on Windows and install tensorflow from here: https://anaconda.org/conda-forge/tensorflow
