### ISSUE TITLE
Value for ranges retrieved with expand should always be lists

### ISSUE THREAD

**Issue by tosiabunio** [ZoomerAnalytics/xlwings#614]
`xw.Range("A1").expand("down").values` returns either single value or a list of values depending on the sheet content. 

For that reason, it's advisable to retrieve Range first, then depending on` RangeRows.count` (or `RangeColumns.count`) retrieving a single value or a list and process it further.

This could be simplified if values always were returned as a list, thus a simple `len()` operation could be used to get the number of entries or the values could be iterated over without any additional checks.

**Comment by fzumstein** [comment]
You can force that by doing `xw.Range("A1").options(expand="down", ndim=1).value`
