### ISSUE TITLE
Documentation; wrong file extension

### ISSUE THREAD

**Issue by DougAJ4** [ZoomerAnalytics/xlwings#622]
Perhaps a minor point, but it cost me too much wasted time.

In the docs for debugging the example has the line:
xw.Book('myfile.xlsxm').set_mock_caller()

If you copy and paste this for use with myfile.xlsm you get a file not found error, for no obvious reason, until you notice the "xlsxm" in the code.

**Comment by fzumstein** [comment]
thanks, will be fixed in 0.10.3
