### ISSUE TITLE
insert equation in cell?

### ISSUE THREAD

**Issue by retsyo** [ZoomerAnalytics/xlwings#631]
I mean literal equation in the cell, not a formula for calculation. Both a picture and a Design Science MathType's equation are ok

for example, $\sum_{k=1}^nkx $ which is rendered by Latex

Thnaks.

**Comment by fzumstein** [comment]
You can do `Insert > Equation` in Excel, but I am not aware of it being scriptable, i.e. you can't do it from xlwings.
