### ISSUE TITLE
Docstrings for UDFs not shown

### ISSUE THREAD

**Issue by dalito** [ZoomerAnalytics/xlwings#636]
I tested the example from the [documentation](http://docs.xlwings.org/en/stable/udfs.html#docstrings) but neither the docstring of the UDF nor of the ones for the arguments show up in the function wizard.

OS: Win 7 Pro, 64 bit
Excel-version: 14.0.7177.5000 (German)
Python: 2.7.13 (32bit)
xlwings: 0.10.4

**Comment by Colin-b** [comment]
For reference I am able to see the documentation using the following setup:

Microsoft Excel 2010 (14.0.7140.5002) 32-bit.
Microsoft Windows 7 Enterprise
Python 2.7, 3.5 and 3.6
xlwings 0.10.3

**Comment by fzumstein** [comment]
It's possible that they are still old and you would need to rerun the import UDFs after downloading. Will check tonight and fix it.

**Comment by fzumstein** [comment]
Sorry, misread your question in the morning. There might be something going on with the German decimal point in the version number. Can you try the following while Excel is running and paste the result here?

```
In[5]: xw.apps[0].api.Version
Out[5]: '16.0'
In[6]: xw.apps[0].version
Out[6]: VersionNumber('16.0')
```

**Comment by dalito** [comment]
Ok. Here you are:
```
>>> xw.apps[0].api.Version
u'14.0'
>>> xw.apps[0].version
VersionNumber('14.0')
```
So the German version has also dots in the version number.

**Comment by dalito** [comment]
I did not correctly understand what xlwings will provide for udfs. A tool tip is not shown as can be seen here
![no_tooltip](https://cloud.githubusercontent.com/assets/2648874/23514723/762387ca-ff68-11e6-93ed-29f6bb4bedd6.png)

but the function wizard (opened by clicking in the "f" symbol) does show the arguments and the function description. So this is not a bug. I was just expecting to have the information also in the tooltip. 

Displaying the tooltip seems to be complicated according to http://stackoverflow.com/questions/4262421/how-to-put-a-tooltip-on-a-user-defined-function

Sorry for the noise.
