### ISSUE TITLE
Xlwings format_number

### ISSUE THREAD

**Issue by RamonGuixa** [ZoomerAnalytics/xlwings#638]
If excel settings for decimal and thousands are different that US ones, format_number does not work.
For instance if settings in Excel are: decimals = "," and thousands = "." as is done in Spain, you have issues in format_number.
A fast and early solution is to give a warning in documentation paragraph: Range, format_number. I spent more 10 hours to find the issue.

**Comment by fzumstein** [comment]
Can you paste some sample code and error message?

**Comment by RamonGuixa** [comment]
Hello Felix,
The code does not give an error message.
You can try to set Excel to Spanish number notation. You go to Excel,
Archive,  Options, Advanced and change "." by "," and "." by ",". In
Spanish one tthousand and zero cents is 1.000,00 instead as in US 1,000.00.
if you use, for instance, xw.Range('A1').number_format = '0.00' you will
have problems with the Spanish settings. With US settings is OK.
Attached code. Problem is in: def grabar_datos_excel(....), number_format
expresions
Regards
Ramón

2017-03-04 15:16 GMT+01:00 Felix Zumstein <notifications@github.com>:

**Comment by fzumstein** [comment]
You can only attach something from GH directly, not in email replies, i.e. I didn't get your attachement. Anyhow, I have no problems using `number_format` after changing the settings to use `,` as Decimal seperator and `.` as Thousands serparator. Obviously you then also need to change the instructions in something like `wb.sheets[0]['A1'].number_format = '0,000%'` i.e. you need to use the correct seperator.

**Comment by RamonGuixa** [comment]
Thanks for your fast response.
Anyway, I have changed Excel settings.
Perhaps will be good to give a warning because the program does not give
any error.
Regards
Ramón Guixá

2017-03-05 12:51 GMT+01:00 Felix Zumstein <notifications@github.com>:

**Comment by fzumstein** [comment]
I would say it's an Excel gotcha and as such not really an issue from
xlwings point of view. but if you have a vba snippet to proof me wrong I am
more than happy to look into i more.

Am 05.03.2017 1:26 nachm. schrieb "RamonGuixa" <notifications@github.com>:

**Comment by RamonGuixa** [comment]
Yes, I agree with you is a gotcha of Excel.
Rgards
ramón

2017-03-05 13:29 GMT+01:00 Felix Zumstein <notifications@github.com>:
