### ISSUE TITLE
Multiprocessing in UDF 

### ISSUE THREAD

**Issue by Dudey007** [ZoomerAnalytics/xlwings#641]
Hi,

I find that when I call an@xw.sub function from excel which is calling multiprocessing on another function I in my code, the code doesn't execute and is perpetually stuck? Is this a known issue?

I have set OPTIMIZED_CONNECTION = True so that the same python interpreter is used

**Comment by fzumstein** [comment]
Yeah kind of, we never really made any effort to support it, see also #199 and #115.

**Comment by Dudey007** [comment]
Is this something that you will look to support- it would be very very handy to have this

**Comment by fzumstein** [comment]
I am not saying never, but it's definitely not at the top of the list...

**Comment by Dudey007** [comment]
so for now there is no way to use multiprocessing in xlwings?

**Comment by fzumstein** [comment]
I guess not, but if you can post a mini self contained sample then it might help us look into what the actual issue is.

**Comment by fzumstein** [comment]
Closing this as multiprocessing is resolved when calling from python, see #1008. I understand this is a slightly different setup (called from UDF),  so will be happy to reopen when you add a small sample to reproduce.

**Comment by xjdeng** [comment]
I was able to use multiprocessing with xlwings using concurrent.futures

**Comment by fzumstein** [comment]
@xjdeng do you mind adding a code sample? thanks

**Comment by xjdeng** [comment]
Unfortunately, it's gonna be a while before I can cook up a code sample.  I only have Excel installed at work and it ran successfully on a confidential notebook.  However, I followed the instructions [here](https://medium.com/@ageitgey/quick-tip-speed-up-your-python-data-processing-scripts-with-process-pools-cf275350163a) to utilize concurrent.futures and then saw all CPUs firing up in the task manager when running the script from Excel (this was a Windows 7 machine which had a separate graph for each CPU, making it easier to confirm they were all being utilized.)
