### ISSUE TITLE
Loading functions from a .xla file

### ISSUE THREAD

**Issue by ja-smith** [ZoomerAnalytics/xlwings#644]
I have two third-party add-ins for excel - one in a .xll file, and one in .xla.
I need to load them into an Excel book, opened using xlwings.

Following the neat solution in http://stackoverflow.com/questions/33125610/xlwings-wipes-out-my-excel-addin I can load the functions from the .xll file successfully.

However, I cannot work out the equivalent way to load in an .xla/.xlam add-in.
Is there also a neat way to do this in python?

**Comment by fzumstein** [comment]
You should be able to open it using the standard xlwings way:

`xw.Book('yourfile.xlam')` or `xw.books.open('yourfile.xlam')`

**Comment by ja-smith** [comment]
Wow, didn't realise that loaded books could access each other's VBA functions!
Thanks for your fast response, needless to say, it works!
