### ISSUE TITLE
automation error, when trying to write to a range in the calling sheet

### ISSUE THREAD

**Issue by ja-smith** [ZoomerAnalytics/xlwings#645]
I am trying to write a UDF to follow the below steps
- open an existing Excel book,
- copy a sheet from that book, and
- insert the copy into the calling book

When I call this UDF from inside my open Excel instance, I get an automation error (I have tried several ways). 
Is it true that UDFs cannot have permission to set ranges and values within the calling sheet, except directly for their return statement?

**Comment by fzumstein** [comment]
Yes, this is true. What you are trying to do is typically achieved with a macro, either using the `xw.sub` decorator or `RunPython`.
