### ISSUE TITLE
Cannot feed Float values into Panda via xlwings?

### ISSUE THREAD

**Issue by kiann00** [ZoomerAnalytics/xlwings#648]
Hi, I am trying to replicate a simple Technical-Analysis indicator using xlwings. However, the list/data seems not to be able to read Excel values. Below is the code 

```
import pandas as pd
import datetime as dt
import numpy as np

@xw.func
def EMA(df, n):  
    EMA = pd.Series(pd.ewma(df['Close'], span = n, min_periods = n - 1), name = 'EMA_' + str(n))  
    df = df.join(EMA)  
    return df
```

When I enter a list of excel data : EMA = ({1,2,3,4,5}, 5}, I get the following error message
TypeError: list indices must be integers, not str   EMA = pd.Series(pd.ewma(df['Close'], span = n, min_periods = n - 1), name = 'EMA_' + str(n))

(Expert) help much appreciated! Thanks.

**Comment by fzumstein** [comment]
see http://stackoverflow.com/questions/43204365/excel-xlwings-data-input-for-python-technical-indicators
