### ISSUE TITLE
Xlwings inside Docker container

### ISSUE THREAD

**Issue by rkpatel33** [ZoomerAnalytics/xlwings#651]
I have a bit of a non-standard use case I wanted to run by you guys. I have a local dev environment for a Django app that uses Docker on OSX, so basically, I have my web app running in a Docker container, which is running on a VM (Docker Machine), which is running on OSX (host system). Standard setup for using Docker on Mac.

I would like to be able to interact with the database from the Django `shell_plus` prompt (could be pointing to local dev dbase or production) running inside a container, and using xlwing to read/write data to Excel running on the host OSX system.

Is there any way this can be done? I realize I could get the Django app running on the host system and run Django `shell_plus` there as a last resort, but its just a bit difficult to maintain and get all the libs set up correctly. But def could be done.

Any thoughts appreciated. I'm guessing in the end you would need some sort of server set up to relay commands from the container to the host system, kind of like running Postgres on the host system and accessing it from a container by pointing at a port on `mac_host_ip`.

Thx.

**Comment by fzumstein** [comment]
We're huge fans of docker ourselves but I am not sure that's technically possible. xlwings needs to connect to AppleScript on a Mac and I am not aware of how you can access it from within a container. So for now, the only way that will work for sure is to install it locally on your mac to use xlwings. If you use conda in connection with a requirements.yml then it's not even such a pain...

**Comment by rkpatel33** [comment]
Ok, thanks, that's what I figured. Xlwings was easy to install, its my app that's a pain. Anyway, will figure it out!

**Comment by fzumstein** [comment]
Docker on Windows might work: http://vunvulearadu.blogspot.ch/2016/10/windows-docker-containers-ca-make-win32.html

**Comment by rladeira** [comment]
Currently, is it possible to build a dockerized solution with xlwings on windows? I mean, the excel in the docker host machine would be communicating with a python environment inside a docker container, without a python installation in the docker host machine itself.

Any references for someone looking for accomplish this task? As far as i understand xlwings, i suspect it is not possible.

Thanks in advance.

**Comment by fzumstein** [comment]
I've never tried it out, but have you looked at the link?

**Comment by rladeira** [comment]
Yes, I wasn`t able to accomplish the integration with xlwings though. It seems like a overly low level integration, which could generate subtle bugs afterwards. I will probably continue using a conda environment instead. Just wanted to know if there was an out-of-box known solution.

Thanks anyway!

**Comment by fzumstein** [comment]
Note that it's now possible to use xlwings via Docker by using the remote interpreter of the PRO package: https://docs.xlwings.org/en/stable/remote_interpreter.html

**Comment by Charan5772** [comment]
Hi @fzumstein, 
This link does not open https://docs.xlwings.org/en/stable/remote_interpreter.html

**Comment by fzumstein** [comment]
This is now xlwings Server: https://server.xlwings.org
