### ISSUE TITLE
Issue with running VBA macro via xlwings compared to lower version

### ISSUE THREAD

**Issue by kikidunk** [ZoomerAnalytics/xlwings#655]
Hello everybody,

As I updated my anaconda package, I couldn't use anymore my script to launch a VBA macro. with the new version of xlwings.
I tried to follow what Felix wrote, but it didn't work:
http://stackoverflow.com/questions/40044090/how-do-i-call-an-excel-vba-script-using-xlwings-v0-10

My code was:

```
wb = xw.Workbook(fullname='my_excel_file.xlsx',
                 app_visible=True,
                 app_target='/Applications/Microsoft Excel')
xw.Sheet('sheet1').activate()
xw.Application(wb).xl_app.run_VB_macro("'Personal Macro Workbook'!my_macro")
xw.Sheet('sheet1').activate()
wb.save('/Documents/my_excel_file.xlsx')
wb.close()
```
The code above could launch my macro::

```
wb = xw.Book('my_excel_file.xlsx')
sht = wb.sheets['sheet1']
sht.activate()
macro1 = wb.macro("'Personal Macro Workbook'!my_macro")
macro1()
sht = wb.sheets['sheet1']
sht.activate()
wb.save()
```
Do you know how I could tackle this issue?
I couldn't come back to a lower version of xlwings.

**Comment by fzumstein** [comment]
Your `macro` call shouldn't include the Sheet name but (potentially) the Module name, see: http://docs.xlwings.org/en/stable/api.html#xlwings.Book.macro

Try to remove the part before the `!`.

**Comment by kikidunk** [comment]
Hello Felix,

Thanks for the reply. Your solution is not working for me. Running the code doesn(t raise error, but doesn't run anything.
I replaced 'Personal Macro Workbook'!my_macro with:
'Personal Macro Workbook'.my_macro
Personal_Macro_Workbook!my_macro
my_macro

Is it working for you?

Does Budd have his issue fixed in the stackoverflow link I sent in the original message?

**Comment by fzumstein** [comment]
feel free to attach a sample so I can show you where the error is.

**Comment by kikidunk** [comment]
Thanks Felix

I replace the previous code with what you said:
```
wb = xw.Book('my_excel_file.xlsx')
sht = wb.sheets['sheet1']
sht.activate()
macro1 = wb.macro("my_macro")
macro1()
sht = wb.sheets['sheet1']
sht.activate()
wb.save()
```

The part `macro1()` doesn't run any VBA code.
Did I do wrong?

Thanks,

**Comment by fzumstein** [comment]
looks ok (the `sht.activate()` seem useless though). Attach a zip file with both the Excel file and the source code here to the issue and I have a look.

**Comment by kikidunk** [comment]
Hello Felix,

Please find a sample of the code, with an Excel Sheet. I couldn't include the macro inside the spreadsheet, as my Excel was crashing when I tried to save into .xlsm, so I put it in a txt file. You will just have to include it into a macro.
I also put the python script in order for you to see what I ran.

[Sample.zip](https://github.com/ZoomerAnalytics/xlwings/files/928854/Sample.zip)

I am looking forward to hearing from you

**Comment by fzumstein** [comment]
Once saved as xlsm, I have no issues running the code. Use attached files.
[SampleFixed.zip](https://github.com/ZoomerAnalytics/xlwings/files/929049/SampleFixed.zip)

**Comment by kikidunk** [comment]
Are you running it on Windows?
It raises error :(
I am currently using macOS.

**Comment by kikidunk** [comment]
It is working if I run the macro, if this one is saved inside the workbook.
But if I run the macro of the Personal Macro Workbook, it is not working anymore.
Have you tried to include my macro inside your Personal Macro Workbook?

**Comment by fzumstein** [comment]
Well, mentioning Personal Macro would have helped, as that's a whole different issue and there's already an open issue for it: https://github.com/ZoomerAnalytics/xlwings/issues/204

**Comment by kikidunk** [comment]
Thank you. I will see that post

**Comment by kikidunk** [comment]
I didn't understand everything about what was written on this post. I reverted to lower version of xlwings and it is working again.
Thank you Felix.
Hope that if the solution is found, we will be keep updated :)

**Comment by RyanBacastow** [comment]
This was extremely useful.
