### ISSUE TITLE
Multiple executables within a workbook

### ISSUE THREAD

**Issue by lahut13** [ZoomerAnalytics/xlwings#656]
Hello all,

I developed my xlwings application using the RunPython function. Depending on inputs on the workbook itself, (checkboxes, data presence, etc) it passes the imported python script (my main.py file) various parameters to call the appropriate function.

Now that I have frozen my project so I can distribute, the parameter functionality no longer works - due to the fact that you simply pass in the executable. 

One ugly workaround I thought of was to build my project multiple times to create multiple executables, but I am not sure how to specify multiple frozen python paths - as they will all have different build folders.

Is there any way to pass your executable parameters?

Or even more simply - how do I access checkboxes with xlwings?

Thanks all!

**Comment by fzumstein** [comment]
For now you'd have to use the underlying pywin32 library to access checkboxes: 

```
sheet = xw.books[0].sheets[0]
sheet.api.OLEObjects("ComboBox1").Object.Value
```

**Comment by fzumstein** [comment]
see also: https://github.com/ZoomerAnalytics/xlwings/issues/8

**Comment by lahut13** [comment]
Ah great! Thanks!

**Comment by fzumstein** [comment]
I assume this is resolved so closing the issue.
