### ISSUE TITLE
Example of accessing Django model data from a function called by RunPython()

### ISSUE THREAD

**Issue by rkpatel33** [ZoomerAnalytics/xlwings#659]
It would be great if you guys could post an example to https://www.xlwings.org/examples of interacting with Django models from a function called by `RunPython` command.

I have a function that dumps data to Excel (it resides in a module inside my Django project) by setting up the whole Django environment and accessing models. 

It works fine when run from command line (along the lines presented here: https://www.stavros.io/posts/standalone-django-scripts-definitive-guide/) but when I call the same function from `RunPython` it fails because it doesn't see the whole Django project path when run that way. The script also can not access env variables set up in a `.bash_profile`.

I think part of this can be fixed by setting PATH or PYTHONPATH but seems like a hacky solution. Of course also does not address the env variable issue.

Thx.

**Comment by rkpatel33** [comment]
Sorry, I have figured this one out, it basically revolved around not being able to access env variables that were exported in my `bash_profile`.  Hard coding them or storing them somewhere else so they are alway accessible without relaying on the shell being set up properly solves the issue.

**Comment by fzumstein** [comment]
xlwings loads `~/.bash_profile`, so there must be something going wrong on your side...

**Comment by rkpatel33** [comment]
I should have been saying `.zshrc` since I actually use Zsh. Should it be loading that as well, and if not could it be added?

**Comment by fzumstein** [comment]
right, that's not loaded. I think you can include a line in your `.bash_profile` to load your `.zshrc`:

    source ~/.zshrc

**Comment by rkpatel33** [comment]
Thanks, that solved all my problems :)


_________________________
Rishi Patel | mail@rishinyc.com
