### ISSUE TITLE
matplotlib figures in excel - any way to clear all pictures with a udf?

### ISSUE THREAD

**Issue by kaiaeberli** [ZoomerAnalytics/xlwings#670]
is there any way to clear all pictures created with matplotlib in excel, using a udf? I couldn't find anything in the documentation. Also, is it possible to plot these pictures in higher resolution, they look a bit pixelated.
But don't get me wrong: I love that i can create graphs with an udf, this is so helpful!

**Comment by fzumstein** [comment]
No, UDFs are only supposed to manipulate the cell they belong to. You'd need to use a macro/Sub to do this.

**Comment by kaiaeberli** [comment]
i see - how about getting higher resolution images?

**Comment by fzumstein** [comment]
yup, there's an open issue for that: #665

**Comment by kaiaeberli** [comment]
ah perfect thanks
