### ISSUE TITLE
Document how to use UDFs from VBA

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#672]

**Comment by DougAJ4** [comment]
Could we have some background on this one?

How are UDFs not useable from VBA at the moment?

**Comment by fzumstein** [comment]
If you call the autogerated wrapper code from another VBA function/sub, then it'll fail with some `caller` errors. Our planned way to resolve that is to provide an alternative wrapper something like `xlwingsFunctions.my_function()`, along the lines of VBA's `WorksheetFunctions`.

**Comment by DougAJ4** [comment]
OK, I have mostly been calling my Python functions directly from my own VBA code, rather than using the auto-generated code, but certainly it will be useful to be able to call the auto-generated functions from VBA ( I didn't know you can't).
