### ISSUE TITLE
RunFrozenPython .exe

### ISSUE THREAD

**Issue by burrowsclayton** [ZoomerAnalytics/xlwings#673]
# Here is what I am running....

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\clayton.burrows>python
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32

I am getting the following error ONLY when I run I try to call a frozen python script.  Calling VBA scripts that are not frozen is working just fine.

The frozen executable is called "CO2_Recylce_Fitting.exe".

# Here is my error
Error
'CO2_Recylce_Fitting.exe' is not recognized as an internal or external command,
operable program or batch file.

# Here is my VBA code:

Sub TestThis()
' Runs a Python executable that has been frozen by cx_Freeze or py2exe. Call the function like this:
' RunFrozenPython("frozen_executable.exe"). Currently not implemented for Mac.

RunFrozenPython ("CO2_Recylce_Fitting.exe")

End Sub

**Comment by fzumstein** [comment]
You need to make sure that `PYTHON_FROZEN = ThisWorkbook.Path & "\build\exe.win32-2.7"` in your VBA settings is pointing to the folder where `CO2_Recylce_Fitting.exe` is (make sure there are no typos), see http://docs.xlwings.org/en/stable/vba.html#settings
