### ISSUE TITLE
AEM module not found - I'm operating in Miniconda

### ISSUE THREAD

**Issue by MichJim** [ZoomerAnalytics/xlwings#680]
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-147-20169b6105b7> in <module>()
----> 1 import xlwings as xw

~/miniconda3/lib/python3.6/site-packages/xlwings/__init__.py in <module>()
     22     from . import _xlwindows as xlplatform
     23 else:
---> 24     from . import _xlmac as xlplatform
     25 
     26 time_types = xlplatform.time_types

~/miniconda3/lib/python3.6/site-packages/xlwings/_xlmac.py in <module>()
      8 
      9 import psutil
---> 10 import aem
     11 import appscript
     12 from appscript import k as kw, mactypes, its

ModuleNotFoundError: No module named 'aem'
```

**Comment by fzumstein** [comment]
`aem` is part of `appscript`, so make sure it is installed by doing `conda install appscript`. Conda is taking care automatically of that dependency when you install xlwings, but maybe something went wrong.

**Comment by MichJim** [comment]
thanks

**Comment by Joilence** [comment]
macOS 10.14.2
conda 4.6.8

No matter I run `conda install appscript` alone and then run `conda install xlwings` or I just run `conda install xlwings`, the problem remains.

**Comment by fzumstein** [comment]
can you try to pip install appscript? We've recently uploaded binary wheels

**Comment by Joilence** [comment]
> can you try to pip install appscript? We've recently uploaded binary wheels

I tried `pip3 install appscript`. Problem solved. Thanks!

**Comment by kaschbacher** [comment]
didn't work for me

**Comment by fzumstein** [comment]
@kaschbacher what python version and distro are you using?

**Comment by fazola** [comment]
I am using Python 3.7.6, I created an environment for the first time today and now I'm trying to run xlwings and having this issue. I tried installing appscript via conda/pip/pip3 and it says either all packages already installed or could not find a version that satisfies requirement appscript

**Comment by fzumstein** [comment]
Can you please post the command you're running including stacktrace?

**Comment by fazola** [comment]
I closed down everything and reloaded so I could write the steps for you, and now it actually works. Not sure what it was, but I also installed command line xcode command line tools.

**Comment by dbiswas** [comment]
> I closed down everything and reloaded so I could write the steps for you, and now it actually works. Not sure what it was, but I also installed command line xcode command line tools.

Yes, that's exactly what I did and it worked for me too.
Thanks

**Comment by fzumstein** [comment]
The command-line tools aren't necessary anymore no matter whether you install appscript via conda or pip. pip currently has binary wheels built for python 3.6-3.9 and conda is always in line with the conda xlwings releases. it's obviously possible that for whatever reason, an installation is messed up at some point, but then a normal re-installation should solve it.
