### ISSUE TITLE
Using xlwings with Anaconda python environments.

### ISSUE THREAD

**Issue by stanleyng8** [ZoomerAnalytics/xlwings#681]
I can't find this documented but I would like to use xlwings with an Anaconda python environment. I tried:
1) xlwings quickstart myproject (using my Anaconda environment py27) and this created the directory containing the xlsm and py file.
2) Within Excel, I tried Import Python UDFs.
This gives a runtime error 53. File not found: xlwings32.dll
My system has multiple Python distributions. The default one does not have xlwings and I want it to remain clean. Presumably the macro in the myproject.xlsm is looking for xlwings in the default python distribution. Is there a way to configure the file to look for the xlwings package within my Anaconda environment?

**Comment by fzumstein** [comment]
You need to set `PYTHON_WIN` to the full path of your interpreter, see: http://docs.xlwings.org/en/stable/vba.html#settings
