### ISSUE TITLE
breakpoint in pycharm does not work

### ISSUE THREAD

**Issue by damian123** [ZoomerAnalytics/xlwings#683]
I can't get the breakpoint to work when I call python code from xlwings.

testme.py:

    import xlwings as xw
    
    def add(n):
        result = []
        while len(result) < n:
            result.append(1+4)
        return result
        
    def xl_add():
        sht = xw.Book.caller().sheets[0]           
        n = sht.range('B1').options(numbers=int).value
        seq = add(n)
        sht.range('C1').expand('vertical').clear_contents()
        sht.range('C1').options(transpose=True).value = seq
    
    if __name__ == "__main__":
        xw.serve()

I saved an XL sheet in the same directory with this VBA code:

    Sub CallTestMe()
        RunPython ("import testme; testme.xl_add()")
    End Sub

in xlwings.bas I change the settings to:

    PYTHON_WIN = "D:\Anaconda3\python.exe"
    UDF_DEBUG_SERVER = True

I then started pycharm and set a breakpoint inside of add(n), and started the debugger.

    D:\Anaconda3\python.exe "D:\Program Files\JetBrains\PyCharm Community Edition 2017.1.4\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 18601 --file D:/sletmig/xlwings/testme.py
    pydev debugger: process 8684 is connecting
    
    Connected to pydev debugger (build 171.4694.38)
    xlwings server running, clsid={506E67C3-55B5-48C3-A035-EED5DEEA7D6D}

I call the VBA code and it returns a row of 5s in column C **but no breakpoint was hit**. In cell B1 I have a number 10.

Versions of software<br/>
Pycharm Community Edition 2017.4<br/>
xlwings v0.10.4<br/>
Python 3.6.1 :: Anaconda 4.4.0 (32-bit)<br/>
Office 2010 32 bit<br/>
Windows 10, 64 bit<br/>

Also posted on SO:
[SO](https://stackoverflow.com/questions/44613365/breakpoint-in-pycharm-when-called-from-xlwings)

**Comment by fzumstein** [comment]
This works only for UDFs, i.e. if you use decorators, as pointed out here: http://docs.xlwings.org/en/stable/debugging.html

An alternative for RunPython is also described there.

**Comment by damian123** [comment]
Thank you! That explains it!
I will try the same with an UDF function.
It also turns out I used XL 64 bit so were mixing 32 and 64 bit!

**Comment by fzumstein** [comment]
xlwings can handle all bitness combinations as it runs out of process.

**Comment by damian123** [comment]
It failed to load xlwings32.dll in the VBA code line
LoadLibray("d:\anaconda\xlwings32.dll")

dependency walker was of little help.

>dir d:\Anaconda3\xlwings32.dll
 Volume in drive D is 1G
 Volume Serial Number is 3EF5-D560

 Directory of d:\Anaconda3

02/23/2016  07:51 PM           276,480 xlwings32.dll
               1 File(s)        276,480 bytes
               0 Dir(s)  111,495,946,240 bytes free

**Comment by fzumstein** [comment]
the code checks for the excel bitness and loads the xlwings32.dll or xlwings64.dll accordingly. Not sure why that would have failed on your system.

**Comment by damian123** [comment]
Yes, I can see that and it tries to load xlwings64.dll even when I am using
XL 32 bit now, I use Windows 10 64 bit so it tried to load xlwings64.dll.
I changed the code a bit but it still fails. XL 64 but should be able to
load the 32 bit dll.

I remember that declare function is VBS can cause problems when the excel
sheet is not in the same directory as the .dll file
i.e. these lines of VBA code: Private Declare PtrSafe Function ... Lib
"xlwings32.dll"
I tried to place udf.xlsm in d:\anaconda3 where the xlwiings32.dll is.
I even selected file open in XL to make sure it would change it current
directory to d:\anaconda3

I am testing this separately on a VM with XL 32 bit.

**Comment by fzumstein** [comment]
the only relevant part is this, here as a simple function for testing:

```
Sub TestXLBitness()
#If Win64 Then
     Debug.Print "on Excel 64bit"
#Else
     Debug.Print "on Excel 32bit"
#End If
End Sub
```

It only checks the bitness of Excel, the underlying OS has nothing to do with it. If that code returns the wrong info, then it's something to do with your system.

**Comment by damian123** [comment]
OK, good point! When run LoadLibrary I get error code 193 which seems to
suggest that I am trying to load a 32 bit from 64 bit.

Do I moved anaconda to 64 bit like my XL.
*Now the UDF works but I still can't hit the breakpoint.*
When I stop the debug server in Pycharm it stops working so I can see I am
using the correct python process.

Lars

**Comment by fzumstein** [comment]
Make sure to run PyCharm in debug mode (the bug, not the play symbol)

**Comment by damian123** [comment]
Gruzi,

Yes, I did that... here is the output in pycharm to show that.

D:\Anaconda3-x64\python.exe "D:\Program Files\JetBrains\PyCharm Community Edition 2017.1.4\helpers\pydev\pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 10068 --file D:/sletmig/xlwings/testme.py
pydev debugger: process 3208 is connecting

Connected to pydev debugger (build 171.4694.38)
xlwings server running, clsid={506E67C3-55B5-48C3-A035-EED5DEEA7D6D}

**Comment by damian123** [comment]
Here is image showing the breakpoint I have set.
![image](https://user-images.githubusercontent.com/727816/27260396-9062054a-542b-11e7-8b29-1744d9fc8113.png)

**Comment by damian123** [comment]
I got it working now in my vm which is pure 32 bit
