### ISSUE TITLE
opening workbooks with mapped network drives

### ISSUE THREAD

**Issue by ericremoreynolds** [ZoomerAnalytics/xlwings#69]
Hello Felix,

The following code does not behave as I expect when the workbook is on a network drive mapped to a letter and it is already open in Excel:

```
wb = Workbook(r"W:\MyWorkbook.xlsm")
```

The following error message is shown

![image](https://cloud.githubusercontent.com/assets/5197585/4390623/995c3836-43fe-11e4-9956-1080896f309e.png)

I am assuming the correct behaviour should be that if the workbook is already open then xlwings connects to it silently?

Best regards,

Eric.

**Comment by fzumstein** [comment]
This looks as if it was the same issue as #10. It's resolved when called from Excel and #137 is still open for the case when it is being called from Python directly.
