### ISSUE TITLE
Unable to install xlwings 0.11.0

### ISSUE THREAD

**Issue by slishak** [ZoomerAnalytics/xlwings#693]
On Windows 7 with Python 2.7 x64, using `pip install xlwings`:

```
 copying xlwings\tests\sample_picture.png -> build\lib\xlwings\tests
 copying xlwings\quickstart.xlsm -> build\lib\xlwings
 copying xlwings\quickstart_standalone_mac.xlsm -> build\lib\xlwings
 error: [Errno 13] Permission denied: 'xlwings\\quickstart_standalone_mac.xlsm'

  ----------------------------------------
  Failed building wheel for xlwings
```

**Comment by slishak** [comment]
Same error with that command. No problems if I force it to install 0.10.4.

**Comment by fzumstein** [comment]
do you have a previous version installed? then you should add `--upgrade`. by force you mean `pip install xlwings==0.11.4`?

**Comment by slishak** [comment]
I get the same message for 0.11.0 whether I'm using `--upgrade` or from a clean install. And yes, I meant `pip install xlwings=0.10.4`. From what I can tell the `quickstart_standalone_mac.xlsm` file didn't exist in that version so I think it's something specific to that (my colleague is having the same issue so I don't think it's a one-off). Thanks!

**Comment by fzumstein** [comment]
Can you try: `pip install xlwings --no-binary :all:`

**Comment by slishak** [comment]
Same again:

```
C:\Users\slishak>pip install xlwings --no-binary :all:
Collecting xlwings
  Using cached xlwings-0.11.0.tar.gz
Requirement already satisfied: comtypes in c:\python27_x64\lib\site-packages (from xlwings)
Skipping bdist_wheel for xlwings, due to binaries being disabled for it.
Installing collected packages: xlwings
  Running setup.py install for xlwings ... error
    Complete output from command c:\python27_x64\python.exe -u -c "import setuptools, tokenize;__fil
e__='c:\\users\\slishak\\appdata\\local\\temp\\pip-build-1v66hd\\xlwings\\setup.py';f=getattr(tokeni
ze, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file_
_, 'exec'))" install --record c:\users\slishak\appdata\local\temp\pip-tpfghw-record\install-record.t
xt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\xlwings
    copying xlwings\command_line.py -> build\lib\xlwings
    copying xlwings\constants.py -> build\lib\xlwings
    copying xlwings\expansion.py -> build\lib\xlwings
    copying xlwings\mac_dict.py -> build\lib\xlwings
    copying xlwings\main.py -> build\lib\xlwings
    copying xlwings\server.py -> build\lib\xlwings
    copying xlwings\udfs.py -> build\lib\xlwings
    copying xlwings\utils.py -> build\lib\xlwings
    copying xlwings\_xlmac.py -> build\lib\xlwings
    copying xlwings\_xlwindows.py -> build\lib\xlwings
    copying xlwings\__init__.py -> build\lib\xlwings
    creating build\lib\xlwings\tests
    copying xlwings\tests\common.py -> build\lib\xlwings\tests
    copying xlwings\tests\test_active.py -> build\lib\xlwings\tests
    copying xlwings\tests\test_app.py -> build\lib\xlwings\tests
    copying xlwings\tests\test_book.py -> build\lib\xlwings\tests
    copying xlwings\tests\test_conversion.py -> build\lib\xlwings\tests
    copying xlwings\tests\test_names.py -> build\lib\xlwings\tests
    copying xlwings\tests\test_range.py -> build\lib\xlwings\tests
    copying xlwings\tests\test_shape.py -> build\lib\xlwings\tests
    copying xlwings\tests\test_sheet.py -> build\lib\xlwings\tests
    copying xlwings\tests\__init__.py -> build\lib\xlwings\tests
    creating build\lib\xlwings\conversion
    copying xlwings\conversion\framework.py -> build\lib\xlwings\conversion
    copying xlwings\conversion\numpy_conv.py -> build\lib\xlwings\conversion
    copying xlwings\conversion\pandas_conv.py -> build\lib\xlwings\conversion
    copying xlwings\conversion\standard.py -> build\lib\xlwings\conversion
    copying xlwings\conversion\__init__.py -> build\lib\xlwings\conversion
    copying xlwings\tests\test book.xlsx -> build\lib\xlwings\tests
    copying xlwings\tests\macro book.xlsm -> build\lib\xlwings\tests
    copying xlwings\tests\sample_picture.png -> build\lib\xlwings\tests
    copying xlwings\quickstart.xlsm -> build\lib\xlwings
    copying xlwings\quickstart_standalone_mac.xlsm -> build\lib\xlwings
    error: [Errno 13] Permission denied: 'xlwings\\quickstart_standalone_mac.xlsm'

    ----------------------------------------
Command "c:\python27_x64\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\slishak\
\appdata\\local\\temp\\pip-build-1v66hd\\xlwings\\setup.py';f=getattr(tokenize, 'open', open)(__file
__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --r
ecord c:\users\slishak\appdata\local\temp\pip-tpfghw-record\install-record.txt --single-version-exte
rnally-managed --compile" failed with error code 1 in c:\users\slishak\appdata\local\temp\pip-build-
1v66hd\xlwings\
```

**Comment by fzumstein** [comment]
I can't really see what's causing this as I can't replicate it. Can you try to unpack the `tar.gz`, then install manually doing: 

    cd xlwings
    python setup.py install

**Comment by slishak** [comment]
I still get the same error. However, I also get some permission errors with `quickstart_standalone_mac.xlsm` and `quickstart_standalone_win.xlsm`. Once extracted, I can delete/rename/move them, but I can't copy and paste them to another location. 

First I get this prompt:
![image](https://user-images.githubusercontent.com/12515343/27863770-f10234f2-618b-11e7-8c68-38f34e921536.png)
And then when I click "Continue" (I'm an administrator and the referenced account is my own one - and the different font quality to the above image is not just a product of uploading it here, it's visible on-screen):
![image](https://user-images.githubusercontent.com/12515343/27863808-18840b7c-618c-11e7-8c01-ec57ad93c405.png)

When I try and open them in Excel I get this:
![image](https://user-images.githubusercontent.com/12515343/27863836-3b5df798-618c-11e7-99b2-4e8efa12738f.png)

There are no problems with `quickstart.xlsm`.

**Comment by fzumstein** [comment]
I will release a new version tonight that hopefully get's around this.

**Comment by fzumstein** [comment]
give 0.11.2 a try, I hope that this resolves it....

**Comment by slishak** [comment]
Thanks, but unfortunately none of the above issues are any different with 0.11.2.

**Comment by fzumstein** [comment]
too bad. running out of ideas...

**Comment by fzumstein** [comment]
One idea would be to delete the pip cache : `c:\users\slishak\appdata\local\temp\pip-*` before you try again. Or wait for the conda package.

**Comment by slishak** [comment]
Even if I download the latest `quickstart_standalone_win.xlsm` or `quickstart_standalone_mac.xlsm` from GitHub, I get the same access denied errors when I try and open it. I can't even open it as a text file or compressed archive. So I don't think it's related to the packaging or installation process, it's just something about the files.

**Comment by fzumstein** [comment]
Ok fair enough. I'll add new versions of them here a bit later to test before I repackage.

**Comment by fzumstein** [comment]
Can you please check if you can open the attached files @slishak ?

[standalone_files.zip](https://github.com/ZoomerAnalytics/xlwings/files/1128371/standalone_files.zip)

**Comment by slishak** [comment]
I can't open them (still get access denied), but I can at least now copy and paste them (I couldn't before). So I imagine at least the installation issue will be fixed with these.

**Comment by fzumstein** [comment]
well slightly better then, yay. Can you try to install the attached dev package with `pip install xlwings-0.11.3.dev0.tar.gz` ?
[xlwings-0.11.3.dev0.tar.gz](https://github.com/ZoomerAnalytics/xlwings/files/1129214/xlwings-0.11.3.dev0.tar.gz)

**Comment by slishak** [comment]
Unfortunately 0.11.3.dev0 still doesn't work, I get the same issue as before. When I extract the Excel files I still can't copy and paste them, like I could with the standalone files you sent.

**Comment by fzumstein** [comment]
these are the very same files, so really not sure what the issue is.

**Comment by fzumstein** [comment]
please give it another try with the released version of 0.11.3. I packaged it as zip so it should be easier to remove the offending files in the worst case before you install.

**Comment by fzumstein** [comment]
alternatively please try to install it with conda: https://anaconda.org/conda-forge/xlwings

**Comment by slishak** [comment]
I just happened to check my antivirus program (Kaspersky) and it looks like it's unhappy with something in the Excel macros, which could have been causing all of the above:

![image](https://user-images.githubusercontent.com/12515343/29553334-0ebfb488-871b-11e7-9bb5-1f92f6082838.png)

**Comment by fzumstein** [comment]
Ok thanks, yeah that makes sense. Try if there's a mechanism to white list these files.

**Comment by wkschwartz** [comment]
Ideas to avoid this problem going forward:

- Have the template `.xlsm` files be generated at installation time on Windows. I don't think this is possible on Mac, but you could modify the [`build_standalone_files.py`](https://github.com/ZoomerAnalytics/xlwings/blob/master/scripts/build_standalone_files.py) script to work with `setup.py`. This way, the installer does not copy binary Excel files at all, at least on Windows.
- Alternatively, package xlwings as a [Wheel](https://pythonwheels.com/).

**Comment by slishak** [comment]
Just tried updating xlwings to 0.11.7 and no longer have the problem above. I didn't add any specific rules to my antivirus program.
