### ISSUE TITLE
Installing latest add-in

### ISSUE THREAD

**Issue by m-marian** [ZoomerAnalytics/xlwings#694]
Hello, I installed the xlwings add-in on my machine for the first time yesterday using the instructions from the following link: http://docs.xlwings.org/en/stable/addin.html . 
However, instead of seeing this in the xlwings Excel ribbon as per the instructions:
![image](https://user-images.githubusercontent.com/26982898/27819049-56a3e0fa-6090-11e7-886b-77f127395e70.png)
I am seeing this: 
![image](https://user-images.githubusercontent.com/26982898/27819091-86c88a24-6090-11e7-89a6-c02cbb8cd801.png)
Did anything go wrong with my installation or has the latest version of the add-in not become available yet?
Thanks!

**Comment by fzumstein** [comment]
You are seeing the previous version of the add-in.

When you do

    import xlwings
    xlwings.__version__

does it give you `0.11.0?

**Comment by m-marian** [comment]
It gives me 0.10.4. I tried "conda install xlwings" and "conda update xlwings" in the command line. Both don't go any further than telling me "All requested packages are installed":
![image](https://user-images.githubusercontent.com/26982898/27838899-7308b52c-60e5-11e7-88ae-c9eb414ea12a.png)
The library works well otherwise so I'm not too fussed.

**Comment by fzumstein** [comment]
the conda package hasn't been upgraded yet. It usually takes them a few days. You can always use pip in the meantime even in a conda environment.

**Comment by m-marian** [comment]
Got it, done. Thank you!
