### ISSUE TITLE
Addin Installation Problem

### ISSUE THREAD

**Issue by Tooblippe** [ZoomerAnalytics/xlwings#700]
HI,

I have the latest version of xlwings installed. I have installed the addin using:

> xlwings addin install

and then create a workbook using

> xlwings quickstart testsproject

The ribbon looks like this

![image](https://user-images.githubusercontent.com/805313/27852248-bec829c4-615e-11e7-8907-a5696aeb1712.png)

and when I click Import I get this message

![image](https://user-images.githubusercontent.com/805313/27852254-c6550ee6-615e-11e7-8b72-559764e27f34.png)

Any help to get this working will be appreciated.

**Comment by denfromufa** [comment]
you probably need to enable vba object model:

http://docs.xlwings.org/en/stable/udfs.html#one-time-excel-preparations

xlwings should just really run this .reg file upon installation:

`VBA_object_model.reg`

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Excel\Security]
"AccessVBOM"=dword:00000001

[HKEY_CURRENT_USER\Software\Microsoft\Office\14.0\Excel\Security]
"AccessVBOM"=dword:00000001

[HKEY_CURRENT_USER\Software\Microsoft\Office\12.0\Excel\Security]
"AccessVBOM"=dword:00000001
```

**Comment by fzumstein** [comment]
The experience of installing/upgrading the addin needs to be improved. however, for the moment try to follow this guide here: http://docs.xlwings.org/en/stable/migrate_to_0.11.html

It has installed the previous version of the addin in your case

**Comment by Tooblippe** [comment]
Thanks. That seems to have enabled it, but the ribbon still does not have anything else in it and still looks like the picture above. Is that normal?

**Comment by Tooblippe** [comment]
PS - The reference does not seem to be set when I go to Tools - Reference in VBA editor. Xlwings do not show up in the list, the file was created using quickstart so it should be set?

**Comment by fzumstein** [comment]
Naww, when you see the picture above, you're still on the old addin. If everything else fails, uninstall the current one, find the new one where xlwings is installed, copy it to some place and install it via `File > Options > Add-ins > Mange: Excel Add-ins - Go`. Then Browse for it.

**Comment by fzumstein** [comment]
You can now also download the addin as part of the release: https://github.com/ZoomerAnalytics/xlwings/releases/tag/v0.11.2
