### ISSUE TITLE
SQL extension doesnt work？

### ISSUE THREAD

**Issue by 26awen** [ZoomerAnalytics/xlwings#712]
![xlwings-sql](https://user-images.githubusercontent.com/13186663/28243937-11f23d26-6a0e-11e7-9c16-1b5b19733a34.PNG)
Is there anything wrong with my code?

**Comment by fzumstein** [comment]
sure, you're missing the from clause `SELECT a.name FROM a`

**Comment by 26awen** [comment]
Thanks @fzumstein .  Please close this issue！
