### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by totry16** [ZoomerAnalytics/xlwings#715]
Hi. 
Just 48 hrs experience with xlwings.
Examples like fibonacci works fine. However, importing  even a blank excel workbook sheet creates the error copied below (i.e copy-or moving- one sheet from an other workbook). Removing the copied sheet, problem solved. (Creating a new sheet within the main workbook, of cause works fine. My future task is to copy sheets from other workbooks (tables), and joining/merging them within one single workbook doing some selection and filtering). PS: There is no workbook names in the example.
Kind regards
totr

```
---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "e:\google drive\it-data\python\test\fibonacci.py", line 34, in xl_fibonacci

    seq = fibonacci(n)

  File "e:\google drive\it-data\python\test\fibonacci.py", line 17, in fibonacci

    while len(result) < n:

TypeError: '<' not supported between instances of 'int' and 'NoneType'

Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------
```

**Comment by fzumstein** [comment]
Have a look at the sample code: it expects the n on the first sheet. If you put a blank sheet there, n will be None and so the error makes obviously sense.
