### ISSUE TITLE
UDFs should be "per excel" and not "per spreadsheet" in some cases

### ISSUE THREAD

**Issue by chfischer** [ZoomerAnalytics/xlwings#719]
To make "xlwing udf libraries" available to a group of business users, it should be as easy as possible for them, to use python UDFs within all their excel files..
How is it possible to make UDFs available independent of the currently open sheet / file.
How could the UDF vba wrappers be stored in a "central" add-in like module, which makes the UDFs available without connecting / importing UDFs via xlwings addin?

**Comment by fzumstein** [comment]
It's currently under documented and not fully automated yet, but you need to add them as custom extensions, see the sql sample: http://docs.xlwings.org/en/stable/extensions.html

To make it work for now, you'll need to add another VBA module to the xlwings addin (pw: xlwings) to put the VBA wrappers that you've imported previously into a workbook. You ll need to replace `ThisWorkbook` with `ActiveWorkbook`.

Obviously, the python modules/packages that the wrappers rely on need to be available on the target computers.
