### ISSUE TITLE
Installing latest version from Anaconda

### ISSUE THREAD

**Issue by DougAJ4** [ZoomerAnalytics/xlwings#721]
I have Anaconda Python 2.7 installed.
When I run conda update xlwings it tells me that version 0.10.4 is already installed.
I have now installed with pip, which installed version 0.11.3, but will I now get conflicts between the two versions?

**Comment by fzumstein** [comment]
Usually it works ok to overwrite a conda installation with a pip installation. But to be sure, better uninstall the conda version first and then install the pip version.
Or use the conda-forge channel which is more up to date than the official anaconda channel, see: https://anaconda.org/conda-forge/xlwings (i ll add a note about that on the next release)

**Comment by fzumstein** [comment]
xlwings 0.11.4 is now available via conda-forge as mentioned under the installation docs, so I'll close this issue.
