### ISSUE TITLE
Reading a excel file opens excel

### ISSUE THREAD

**Issue by pinq-** [ZoomerAnalytics/xlwings#727]
Hi,
I was reading that this was a issue before, but then it was fix. 
When I read excel file like this:
`example = xw.Book("file.xlsx")`
it also opens excel program with the file. Before it didn't to that. Funny thing is that I didn't update xlwings or python so maybe it is because excel? Now I installed latest version of xlwings and it still does it. 
Is this a bug or my mistake?

**Comment by fzumstein** [comment]
that's how xlwings works, it's always going to do things via Excel, so you must either mistake it with another library or you may have set `App(visible=False)` so it opens Excel hidden.

**Comment by pinq-** [comment]
Ok. Thank you for this info.
