### ISSUE TITLE
webroot not happy with the 64bit dll of 0.11.4 (was happy with 0.10.4)

### ISSUE THREAD

**Issue by stonebig** [ZoomerAnalytics/xlwings#731]
I don't know how to clear the alarm from a given anti-virus motor (1 out of 64 motors) : https://www.virustotal.com/fr/file/de4190d83b7d51d324b025ad070053d3e1ee472d4cdabbcba346758ff98030af/analysis/1501253570/

can anyone confirm that "xlwings64.dll" SHA256 is  de4190d83b7d51d324b025ad070053d3e1ee472d4cdabbcba346758ff98030af ?

(as if ever it's not a false positive, my PC can be the infection point)

**Comment by fzumstein** [comment]
the sha256 is correct, yes

**Comment by fzumstein** [comment]
Hey @stonebig I've seen a few of your issues in the Python in Excel repo asking for pymoo, duckdb, etc. These are all supported by the new and free xlwings Lite (https://lite.xlwings.org). This will also get around all anti-virus issues.
