### ISSUE TITLE
Not all numpy types are numeric

### ISSUE THREAD

**Issue by ludaavics** [ZoomerAnalytics/xlwings#732]
When switching back and forth between lists and ndarrays, `np.string_` sneak in, tricking `xlwings` into trying to convert strings to floats.

```python
data = np.array(['foo', 'bar'])
data = list(data)
sh.range('A1').value = data
```

```
  File "E:\Dev\WinPython\python-2.7.10.amd64\lib\site-packages\xlwings\_xlwindows.py", line 1027, in prepare_xl_data_element
    return float(x)
ValueError: could not convert string to float: foo
```

Fixed by changing `np.generic` to `np.number` in [prepare_xl_data_element](https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/_xlwindows.py#L1022), as per [Numpy hiearchy of types](https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html):

```python
def prepare_xl_data_element(x):
    if isinstance(x, time_types):
        return _datetime_to_com_time(x)
    elif np and isinstance(x, np.generic):
        return float(x)
    elif x is None:
        return ""
    elif np and isinstance(x, float) and np.isnan(x):
        return ""
    else:
        return x
```

![image](https://user-images.githubusercontent.com/1891756/28984975-6b8f539e-792e-11e7-8541-f10c124fa927.png)

**Comment by fzumstein** [comment]
Note, however, that you should probably be using `data.tolist()` instead of `list(data)` and you won't have the issue.

**Comment by ludaavics** [comment]
👍 indeed!
Knowing / thinking of that could have saved me some time down the rabbit hole, thanks :)
