### ISSUE TITLE
Unexpected Python error when running UDF

### ISSUE THREAD

**Issue by DeltaW7** [ZoomerAnalytics/xlwings#738]
Hi
I'm passing a text string to Python to do some stuff, and get the following error back in excel:

Unexpected Python   Error: TypeError: Objects of type 'Add' can not be converted to a COM VARIANT   (but obtaining the buffer() of this object could)
--
UDF: '=testint(eq) Where eq is a text string e.g. "x**3+5"

VBA code:
```
Function testint(eq)
If TypeOf Application.Caller Is Range Then On Error GoTo failed
        testint = Py.CallUDF("test", "symbint", Array(eq), ThisWorkbook, Application.Caller)
        Exit Function
failed:
        testint = Err.Description
End Function
```
Python code:
```
import xlwings as xw
import sympy as sp
from sympy import integrate

@xw.func
def symbint (eq):
    x = sp.symbols('x')
    return sp.integrate(eq)
```
The code works in python. "eq" is a text string

I've tested just passing a text string to python and returning it, that works

So what is the problem here?

**Comment by DeltaW7** [comment]
Ok solved the problem.
Seems that the return type was the issue. I converted the return to be a string, that solved the problem.
e.g. last line of python code:

return str(sp.integrate(eq))

**Comment by fzumstein** [comment]
You're right, xlwings doesn't have a built-in converter for `<class 'sympy.core.add.Add'>`, so you do need to convert it into something that xlwings can handle.
