### ISSUE TITLE
Bad DLL calling convention

### ISSUE THREAD

**Issue by Exceluser** [ZoomerAnalytics/xlwings#739]
Ok, so I did precisely the following steps:

- Downloaded Anaconda (I did add it to my Path in the installation wizard)
With the command prompt:
 - conda update conda
- conda update anaconda
- conda update python
- conda update xlwings

Then i opened a new spreadsheet and tried to run some UDF. The function gets correctly imported as I can use it in Excel, but when I call it, the output is "Object required", e. g. an error message.
Does someone know how to fix this?

The function is really simple:
import xlwings as xw

@xw.func
def tripplesum(x, y):
    return 3*(x+y)

(Im sorry for posting so much in this forum lately, but i really would like to get xlwings to work properly on my work pc)

**Comment by fzumstein** [comment]
Can you try to run a `RunPython` example and see what the error message is? maybe double click on the xlwings addin and type in the password `xlwings`. The fibonacci sample should work for example.

**Comment by Exceluser** [comment]
I did the following, I hope that is what you had in mind. Unfortunately, I am not very good with this kind of IT stuff...

![image](https://user-images.githubusercontent.com/31079954/29453685-cb2ae534-840a-11e7-9728-7cd3cc4aa9f4.png)

**Comment by fzumstein** [comment]
can you download fibonacci and try to run that? RunPython has to go into your workbook, not into the addin. if the error pops up, click on debug and see where it stops.

**Comment by Exceluser** [comment]
Oh, so that was due to my other function still, sorry. I stopped that and did run it again:
![image](https://user-images.githubusercontent.com/31079954/29453803-3698e2c6-840b-11e7-9984-ea029bb97c05.png)

which brings me then here:
![image](https://user-images.githubusercontent.com/31079954/29453826-4d4814b0-840b-11e7-81c3-ed87fcf241bc.png)

And pressing OK brings up this:

![image](https://user-images.githubusercontent.com/31079954/29453839-5e7b59d6-840b-11e7-8723-9c9973666aea.png)

**Comment by fzumstein** [comment]
can you screenshot your ribbon?

**Comment by Exceluser** [comment]
There you go:
![image](https://user-images.githubusercontent.com/31079954/29453926-ac4260d8-840b-11e7-9a5a-e07a246e1491.png)


Where do I get the Fibonacci? I cannot find it with the search function on docs.xlwings.org

**Comment by fzumstein** [comment]
https://www.xlwings.org/examples 

download fibonacci lite and unzip it

**Comment by Exceluser** [comment]
I opened the spreadsheet and pressed on the "lite" button: 
![image](https://user-images.githubusercontent.com/31079954/29454157-6e2648a4-840c-11e7-9a3c-0870c37d5eaf.png)

**Comment by Exceluser** [comment]
I managed to solve the problem! It was only the reference xlwings, that was missing. Sorry to take up so much of your time with this simple mistake. 
Thank you alot!

**Comment by vipuljee** [comment]
How had you solved this? I am struggling with same problem "object required". Could you please suggest?
