### ISSUE TITLE
Printing pd.DataFrame in the spreadsheet

### ISSUE THREAD

**Issue by andreicrisan11** [ZoomerAnalytics/xlwings#744]
I have a method that returns a dataframe. Namely I have the following: 

`@xw.func
def test_function():
    df = pd.Series(index = [1,2], data = ['a', 'b'])
    return df`

When I go on the excel sheet and call `=test_function()` from a cell I only get `1` which would be the top left corner of the series. What do I need to do to be able to have the whole series printed?

**Comment by DougAJ4** [comment]
Select a range large enough to hold the entire output, with the function in the top left corner.
Press F2 
Press Ctrl-Shift-Enter
You should get the whole series.

Also look in the docs for auto-resizing output arrays.

**Comment by fzumstein** [comment]
described here: http://docs.xlwings.org/en/stable/udfs.html#array-formulas-get-efficient
