### ISSUE TITLE
xlwings in linux

### ISSUE THREAD

**Issue by aarchsk** [ZoomerAnalytics/xlwings#746]
Can we read single excel without modifying other sheets with pivot and charts?

I have excel with multiple worksheets. I would want to write dataframe in one sheet (data)but not modify anyother sheet which has pivot tables and charts.Other sheets with pivot table reference  data sheet.
I am able to do this with xlwings but this does not work in linux.
Can someone please help.
import xlwings as xw
app=xw.App(visible=False)
sht=xw.books.open(r'C:\WorkSpace\Data\Inc\DamageReport_SC.xlsx')
sht.sheets['Data'].range('A1').options(expand='table').value=df_sc
sht.sheets['Daily'].range('A1').options(expand='table').value=df_daily_sc
sht.save(r'C:\WorkSpace\Data\Inc\DamageReport_SC.xlsx')#Local
app.quit()

**Comment by fzumstein** [comment]
xlwings doesn't work on Linux. You need to try one of the following packages: xlrd/xlwt, openpyxl, xlsxwriter

**Comment by fzumstein** [comment]
Also you can use pandas directly: https://pandas.pydata.org/pandas-docs/stable/io.html#excel-files
