### ISSUE TITLE
Update values in Range that includes filtered rows results in incorrect update

### ISSUE THREAD

**Issue by bklaas** [ZoomerAnalytics/xlwings#747]
If you have a worksheet that includes filtered rows (for example, Data->Filter->hide rows with blank cells in Col A), when performing a Range() update of cells that include filtered rows result in an unexpected update.

In this example, the sheet referenced starts with a value 1 in cell A1, a value 4 in cell A4, and a value of 5 in cell A5.

sample code:

```
EXCEL = xw.App()
sheet = EXCEL.books[0].sheets[0]
change_me = [[5], [4], [3], [2], [1]]
sheet.range((1,1)).value = change_me

```
Without a row filter in place on this sheet, the last line of this code properly rewrites the range to read 5, 4, 3, 2, 1 down the first 5 cells of col A.

However, if there is a filter in place on the sheet to hide rows without data (thus hiding rows 2 and 3 in this example), the range gets rewritten as 5 in A1, 5 in A4, and 5 in A5 (and nothing in A2 and A3). In other words, it drops the first element of change_me into every non-hidden cell.

I am working around this by poking into the .api method and explicitly removing all data filters first with:
`sheet.cells.api.AutoFilter()`

This works to get around the bug, but this is definitely a bug. I'd recommend at a minimum throwing an exception when filters are in place on a sheet and .value is trying to be executed across the filter.

**Comment by fzumstein** [comment]
Duplicate, see #679
