### ISSUE TITLE
I am trying to use sql function getting the following error

### ISSUE THREAD

**Issue by boazdori** [ZoomerAnalytics/xlwings#749]
1 | 2 | 3 |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
3 | 4 | 5 |   |   |   |   |   |   |   |   |   |  
6 | 7 | 8 |   |   |   |   |   |   |   |   |   |  
9 | 10 | 11 |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
SELECT   Table1.* |   |   |   |   |   |   |   |   |   |   |  
sqlite3.OperationalError:   no such table: Table1         c.execute(query)       File   "C:\Users\user\Anaconda3\lib\site-packages\xlwings\ext\sql.py",   line 53, in sql         ret = func(*args)       File   "C:\Users\user\Anaconda3\lib\site-packages\xlwings\udfs.py", line   250, in call_udf         res = call_udf(script, fname,   args, this_workbook, FromVariant(caller))       File   "C:\Users\user\Anaconda3\lib\site-packages\xlwings\server.py", line   190, in CallUDF         return func(*args)       File   "C:\Users\user\Anaconda3\lib\site-packages\win32com\server\policy.py",   line 586, in _invokeex_         return S_OK, -1,   self._invokeex_(dispid, lcid, wFlags, args, None, None)       File   "C:\Users\user\Anaconda3\lib\site-packages\win32com\server\policy.py",   line 283, in _invoke_         return self._invoke_(dispid,   lcid, wFlags, args)       File   "C:\Users\user\Anaconda3\lib\site-packages\win32com\server\policy.py",   line 278, in _Invoke_
  |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |

**Comment by fzumstein** [comment]
Try to replicate the example on the screenshot: http://docs.xlwings.org/en/stable/extensions.html

You're using the wrong syntax. The tables are called `a`, `b` etc.

**Comment by boazdori** [comment]
got it working thanks
