### ISSUE TITLE
File not found: xlwings32.dll 53 when try import function

### ISSUE THREAD

**Issue by lmielke** [ZoomerAnalytics/xlwings#750]
Hello there,

i just installed xlwings in a new conda environment. When I klick "Import Functions" I receive the error message File not found: xlwings32.dll 53
One thing I noticed is, that adding the xlwings reference selection in the VBA project is not saved by the workbook. Instead, when I save and close the workbook, I receive a excel message telling, that the workbook does not respond anymore. When I restart the workbook, the xlwings reference is not selected anymore. 
NOTE: The import to python (via. jupyter notebook) using xw.Range works well. However, I would prefer if I could also use the import function module.

Here is what I did so far:
-check settings below
-uninstall/reinstall xlwings
-reinstall excel with language english US
-set PYTHONPATH

![image](https://user-images.githubusercontent.com/30799530/30002870-f85b5434-90b3-11e7-9bb9-88aae51f67cd.png)

**Comment by lmielke** [comment]
maybe related to my first issue: When I try to run the VBA SUB RunPython in Excel, I receive an error saying 'No module named xlwings'. However, xlwings is installed and when I run the python file from the cmd it runs through without errors.

**Comment by fzumstein** [comment]
Try to set the full path to your interpreter in the addin and see if that resolves the issue.

**Comment by lmielke** [comment]
I set the full path but unfortunately no change. Tried path to end with folder name and also with pythonw file name. 
The VBA reference is now kept by excel. However, this was already the case before I tried changing the path.

**Comment by lmielke** [comment]
ok, looks like the problem was sitting infront of the monitor. It looks like xlwings doesnt like Anaconda environments to much. After reinstalling everything using the regular command prompt it now works well.

**Comment by fzumstein** [comment]
xlwings is meant to work with conda envs. I will look into it.

**Comment by def-mycroft** [comment]
had same issue here

**Comment by pferrarezi** [comment]
This solved here:
`pip uninstall xlwings
pip install xlwings==0.9`

**Comment by ermai** [comment]
I suffer the same problem with xlwings-0.11.7

**Comment by fzumstein** [comment]
This means that your excel add-in must be out-of-sync. What version does it display? In doubt, download xlwings.xlam from the release page under v0.11.7: https://github.com/ZoomerAnalytics/xlwings/releases and reinstall it

**Comment by ermai** [comment]
Thank you .It works!!!

**Comment by AJP4** [comment]
Same issue

**Comment by fzumstein** [comment]
upgrade your xlwings addin to the same version as your python package

AJP4 <notifications@github.com> schrieb am Mi., 28. März 2018, 18:46:

**Comment by RaoTianlong** [comment]
execute ‘xlwings addin install' to upgrade xlwings, and this problem will be solved.

**Comment by mahazkhan** [comment]
error: option --single-version-externally-managed not recognized for installing xlwings

**Comment by fzumstein** [comment]
see: https://stackoverflow.com/questions/14296531/what-does-error-option-single-version-externally-managed-not-recognized-ind

**Comment by gregor-taube** [comment]
This may help someone who has problems with `xlwings` on Anaconda.

Anaconda does not add Python to the **PATH** by default(you have to go through anaconda prompt, typing python in Powershell does not work). So in the `xlwings` addin, it works if **interpreter** is set with an absolute path.
