### ISSUE TITLE
'Workbook' object has no attribute 'fullname'

### ISSUE THREAD

**Issue by datasaur** [ZoomerAnalytics/xlwings#76]
Simple fix perhaps: 'fullname' -> 'name' (https://github.com/datasaur/xlwings/commit/318d889df2573940372fb461ad8b5595d560b920)

I combined that change with an additional example in database.py, and don't want to combine both into a single PR.

**Comment by fzumstein** [comment]
I've troubles converting the HFS path as returned by `wb.xl_workbook.properties().get(k.full_name)` into POSIX path. This would be needed if the Worbook is created with an xl_workbook object instead of with a fullname.

**Comment by fzumstein** [comment]
This seems to work:
```
from xlwings import Workbook
from appscript import k, mactypes

wb = Workbook('/path/to/file.xlsx')
path = wb.xl_workbook.properties().get(k.full_name)
url = mactypes.convertpathtourl(path, 1)  # kCFURLHFSPathStyle = 1
print mactypes.converturltopath(url, 0) # kCFURLPOSIXPathStyle = 0
```
