### ISSUE TITLE
xlwings.Book.save() can't save the updated xlsx to the existing file without promoting in Excel 2016

### ISSUE THREAD

**Issue by WonderDream** [ZoomerAnalytics/xlwings#779]
![xlwings-save-problem](https://user-images.githubusercontent.com/12297368/32980996-e60a81f4-ccab-11e7-9ead-1340b0e392c2.PNG)
As illustrated in the figure above, the save method can't save the xlsx to the existing file without promoting.

**Comment by fzumstein** [comment]
Have a look at the docs: http://docs.xlwings.org/en/stable/api.html#xlwings.Book.save

you must not provide a path when you want to overwrite the current book.
