### ISSUE TITLE
passing a workbook as an argument in macro call

### ISSUE THREAD

**Issue by BricksBurg** [ZoomerAnalytics/xlwings#784]
I am trying to call an external macro in a workbook which requires the workbook as a parameter although I get the following error:
"TypeError: Objects of type 'Book' can not be converted to a COM VARIANT (but obtaining the buffer() of this object could)"

Here is the code:
import xlwings as xw
...
wb = xw.Book(FILEPATH)
macro1 = wb.app.macro("libraryfunctions.xlam!Function1")
macro1(wb)

**Comment by fzumstein** [comment]
can you paste the function definition of Function1?

**Comment by BricksBurg** [comment]
Sure it's:
Public Function Function1(oWorkbook As Workbook) As Boolean

**Comment by skasi7** [comment]
A wild guess, check if passing wb.api instead of wb fixes your problem. Maybe wb.api can be passed as COM VARIANT.
