### ISSUE TITLE
Feature: Add docs-section for permanent "Run Python" buttons in Excel ribbon

### ISSUE THREAD

**Issue by ankostis** [ZoomerAnalytics/xlwings#79]
I'm suggesting to add a section in the docs on how to modify the Excel-ribbon by adding a new button that will invoke python code present in selected cells
(:menuselection"`Right-click on the desired ribbon (ie Home) --> Customize Ribbon ...`).
First you must have created the following VBA function into your personal workbook
(:menuselection"`View --> Unhide --> 'PERSONAL.XLSB'` and then open VBA-editor with :kbd:`Alt-F11`):

.. code-block:: vba

```
Sub InvokePython(python_body As String)
    '' Modify the default imports, below.

    Dim python_prefix As String
    Dim python_code As String
    Dim wb_name As String

    wb_name = ActiveWorkbook.FullName
    python_prefix = "from xlwings import Workbook, Range; wb = Workbook(r'" & wb_name & "'); " & vbCr

    python_code = python_prefix & python_body

    Debug.Print ("PYTHON_EXEC: " & python_code)
    Call RunPython(python_code)
End Sub


Sub RunCellAsPython()
  '' Uses `xlwings` library to run the active-cell as Python code.

    Call InvokePython(ActiveCell.Value)
End Sub


Sub RunSelectionAsPython()
    '' Uses `xlwings` library to run the active-selection as Python code.

    Dim python_body As String
    Dim wb_name As String

    python_body = ""
    For Each c In Selection
        python_body = python_body & c.Value & ";" & vbCr
    Next c

    Call InvokePython(python_body)
End Sub
```

Then you can install 2 new buttons corresponding to the 2 subprocedures above:

_Run Python Cell_ --> `RunCellAsPython()`
    Runs the active-cell of the selection as python code.

_Run Python Selection_ --> `RunSelectionAsPython()`
        Concatanates all cells of the current-selection and runs them as python code.

**Comment by fzumstein** [comment]
closing this as the suggested way is to go via extensions/udfs: http://docs.xlwings.org/en/stable/extensions.html
