### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by jimhoranjr** [ZoomerAnalytics/xlwings#801]
I'm trying to replicate the hello example in the documentation but the the following error 
---------------------------
Error
---------------------------
  File "<string>", line 1

    import sys, os; sys.path.extend(os.path.normcase(os.path.expandvars(r'C:\Users\Jim Horan\.spyder-py3;c:\Python_Jim\')).split(';')); import hello; hello.world()

                                                                                                                                  ^

SyntaxError: invalid syntax

I'm the Excel workbook and hello are both save in Python_Jim

Any Thoughts

Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

**Comment by skasi7** [comment]
You are scaping the final ' in the string with the paths. Remove the final \ after Python_Jim (it's useless anyway) and you're good to go.

**Comment by jimhoranjr** [comment]
Thank You that got me to the following error . I have done a pip install pypiwinn32 that appears to have been successful . I also tried copying win32 from the \site-packages\win32 dir to the site-packages\xlwing dir but that didn't help 
What am I missing?

---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\python_jim\hello.py", line 9, in <module>

    import xlwings as xw

  File "C:\Users\Jim Horan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlwings\__init__.py", line 23, in <module>

    from . import _xlwindows as xlplatform

  File "C:\Users\Jim Horan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\xlwings\_xlwindows.py", line 10, in <module>

    import win32api

ImportError: DLL load failed: The specified module could not be found.



Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

**Comment by fzumstein** [comment]
If conda/anaconda is not a possibility, can you try the package (with instructions) from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pywin32 I've never really looked into the pypi version as it's not official and used to be behind.

**Comment by jimhoranjr** [comment]
Found the answer see below
Thanks

I have the same problem for days, but one day I solved it.
After you installed the pywin32 libs, there is a directory "Lib/site-packages/pywin32_system32", which including three dll libs, copy them to the "/Lib/site-packages/win32" directory, which including the win32api.pyd or win32api.pyc.
There will be no ImportError Exception any more
