### ISSUE TITLE
ImportError: DLL load failed: 1% is not a valid win32 app

### ISSUE THREAD

**Issue by jimhoranjr** [ZoomerAnalytics/xlwings#807]
I'm tryng to get the new version of xlwings .11.6 running on my laptop. When I try xlwings addin remove to get rid of the old addin (ver .10.4)  I get the below error.
C:\Python_Jim\Scripts>xlwings addin remove
Traceback (most recent call last):
  File "C:\Python_Jim\Scripts\xlwings-script.py", line 3, in <module>
    import xlwings.command_line
  File "C:\Python_Jim\lib\site-packages\xlwings\__init__.py", line 22, in <module>
    from . import _xlwindows as xlplatform
  File "C:\Python_Jim\lib\site-packages\xlwings\_xlwindows.py", line 10, in <module>
    import win32api
ImportError: DLL load failed: %1 is not a valid Win32 application.

running windows 10 
excel13 32 bit 
python 3.6 64bit 
Any thoughts

**Comment by fzumstein** [comment]
just try to install the new version without uninstalling the old one first. Also note that you should use 0.11.7 as it fixes a bug that was introduced in 0.11.6

**Comment by jimhoranjr** [comment]
Thanks I got it working
