### ISSUE TITLE
Referencing rows instead of columns

### ISSUE THREAD

**Issue by SpencerC** [ZoomerAnalytics/xlwings#812]
https://github.com/ZoomerAnalytics/xlwings/blob/709322ed808cdae243d2cc1977eb2dd2c504bc83/xlwings/_xlmac.py#L669

Should be: `for i in range(self.shape[1])`

**Comment by fzumstein** [comment]
fixed this but we're actually not using it anywhere in the code, i think this was replaced by RangeColumns in main.py
