### ISSUE TITLE
app.quit() does not quits excell application 

### ISSUE THREAD

**Issue by Razmaniak** [ZoomerAnalytics/xlwings#814]
After run following script in process list there are still an excel application instance, but it is in invisible mode.

```
import xlwings as xw
app = xw.App()
app.quit()
xw.apps
```
returns Apps([])

I am using further psutil and signal libraries to find and close excel instance.
Win10 64 bit
xlwings '0.11.7'
Python 3.6.4 32 bit

**Comment by fzumstein** [comment]
COM, the technology that xlwings/pywin32 uses under the hood, only releases the Excel process if there are no more references to it from Python. This means, you'd either need to `del app` at the end of your code or use `app.kill()` instead.

**Comment by gflores87** [comment]
What happens if you have Excel already open for something else? I understand xw.App() creates a new instance but can we be sure that xw.kill() will not interfere with the other Excel instances?

**Comment by fzumstein** [comment]
Before you do anything to app, you can check what files are open and react accordingly. See also: https://stackoverflow.com/questions/56045634/excel-application-window-not-closing-on-workbook-close

**Comment by wkschwartz** [comment]
Note for anyone who winds up here: #1397 should fix this under normal usage
