### ISSUE TITLE
installation problem using excel 2016 64bit

### ISSUE THREAD

**Issue by boazdori** [ZoomerAnalytics/xlwings#820]
Had xlwings running on a excel 365 32 bit changed to 64 bit and cant get xlwings to work.
went through the full remove and reinstall still now joy.
xlwing 64.dll in anaconda3 directory
ran xlwings addin install
on the riben i have 11.7
referenced xlwings 
when i press the import functions i get error 53 for 64dll
when i try to run cod using 
Sub import()
    RunPython ("import")
End Sub
i get
---------------------------
Error
---------------------------
'python' is not recognized as an internal or external command,

operable program or batch file.
i put the path in the system variabel path
C:\Users\user\Anaconda3\python
still no joy 
I can converse with excel using xlwings from the python ide
thanks for the help
Boaz

**Comment by fzumstein** [comment]
Please see No. 2 here: http://docs.xlwings.org/en/stable/troubleshooting.html

**Comment by boazdori** [comment]
I ran “where python” in cmd and copied the link to the pythonpath window in xlwings ribbon and still behaves the same I also tried changing the path in the windows system path with the same result.

Boaz

 

My xlwings config looks like this

"UDF MODULES",""

"INTERPRETER","pythonw"

"PYTHONPATH","C:\Users\user\Anaconda3\pythonw.exe"

**Comment by fzumstein** [comment]
what you under python path needs to be under Interpreter.

**Comment by boazdori** [comment]
Felix hi,

 

"UDF MODULES",""

"INTERPRETER","pythonw"

"PYTHONPATH","C:\Users\user\Anaconda3\pythonw.exe"

 

From the xlwings config file

 

C:\Users\user\Anaconda3\pythonw.exe

In the system veriables path 

 

Still the same 

 

If I try running 

Sub import()

    RunPython ("import")

End Sub

 

I get the following

---------------------------

Error

---------------------------

'python' is not recognized as an internal or external command,

operable program or batch file.

 

 

Press Ctrl+C to copy this message to the clipboard.

---------------------------

OK   

 

If I try to import function from the ribbon I get 

 

---------------------------

Error

---------------------------

File not found: xlwings64-0.11.7.dll 53

---------------------------

OK   

 

Sorry for being a pain and thanks for the help

Boaz

**Comment by boazdori** [comment]
Also checked office up to date and ran a windows update still no change

**Comment by boazdori** [comment]
Felix hi,
adding the path to the interpreter sorted it out.
thnx agian
Boaz
