### ISSUE TITLE
Bad DLL calling convention

### ISSUE THREAD

**Issue by JulienNic0las** [ZoomerAnalytics/xlwings#822]
Hi,

Even if the title is the same as [#739](https://github.com/ZoomerAnalytics/xlwings/issues/739), I think this is not a duplicate.

I get `Bad DLL calling convention` error in Excel cells when using UDFs, even for provided examples (like `double_sum`).

I've juste made a fresh install of `xlwings` using the conda package manager (Anaconda, Python 3.5). I installed the add-in using `xlwings addin install`.  I used the `xlwings quickstart` command to create en empty project.  In order to make `RunPython` working properly I needed to specify the Python interpreter (I have several Python version on my PC).  I then noticed that the xlwings ribbon was almost empty. I means that I had just the _Import Functions_ icon, and that's it. To get the full ribon I needed to load the add-in from Excel (Excel options, Add-Ins, Excel Add-Ins, and pointing to the .xlsam in site-packages\xlwings\addin). After reboot, the ribbon is complete and the import functions mechanism seems to work as intented as I can call the `double_sum` function. However the result is `Bad DLL calling convention` as mentioned earlier. Not in a pop-up window but directly in the cell.

I guess I have an issue with the location of one or several DLL used by xlwings. But which one(s) and how to fix that?

For the sake of completness:

- Python 3.5 (Anaconda)
- Fresh install of xlwings (no upgrade)
- Python not referenced in Windows registry (meaning typing `python` in console does not call the Python version I use)
- Excel 2007

Thanks in advance.

Ciao

J

**Comment by fzumstein** [comment]
what is your xlwings version (`import xlwings` and `xlwings.__version__`) and what are the names of the xlwings dlls (same dir as your python interpreter)?

**Comment by JulienNic0las** [comment]
What reactivity!

I'm using version `0.11.4`. Same version in when calling `xlwings.__version__` and in the ribbon by the way. I have two dlls files named `xlwings32.dll` and `xlwings64.dll`, both at root of the Anaconda install directory.

**Comment by JulienNic0las** [comment]
Hi there. I abandonned for a while this issue and when I came back for a new try I managed to use UDFs. I just reinstall the add-in. I'm not sure the issue came from that, but it works so I close the issue.
