### ISSUE TITLE
Excel automation error

### ISSUE THREAD

**Issue by theodormunteanu** [ZoomerAnalytics/xlwings#823]
Hello to everybody

I encounter the error 440, automation error, when I use Import UDF.

Input data:
Windows 10, Microsoft Excel 2016
xlwings: 0.11.5
Python used: 3.6.4 (anaconda 5.1)
I have the DLL's of xlwings 0.11.5 and 0.11.7 in the root of Anaconda3 (32 bit and 64 bit)

I have tried with xlwings 0.11.7 but to no success.
The interpreters I have tried to use are python and pythonw.

When I use python(without w) it opens the cmd console and says there is a COM error, and the last line is: MacroOptions method of Application class failed.

I have C:\Anaconda3 (along with python and pythonw) inside path in System environment variables.
I do not have to mention I have followed all the steps:
1. Same name of excel file(macro enabled) and python module
2. Trust access to the VBA project object model
3. Add-ins add the default xlwings package from Anaconda to Excel Addins
4. Add to references in VBA.
5. Restart UDF server
6. Python Path = empty, Interpreter: C:\Anaconda3\python.exe (I tried also with pythonw.exe, python, pythonw, or empty) but without any success.
7. Import functions

**Comment by fzumstein** [comment]
Can you check if you get the same error on a file that has been created via quickstart? 

```
xlwings quickstart testproject
```

**Comment by theodormunteanu** [comment]
When I try to add in VBA --> References -->xlwings it gives me an empty error 400.

**Comment by theodormunteanu** [comment]
I don't know how to do that.

**Comment by theodormunteanu** [comment]
Update: Now the update works for the classic double_sum function but when I add a new function 
def sum1(x,y): return x+y+3, save it, restart UDF server, IMPORT FUNCTIONS it gives again automation error 440 but the function sum1 is recognized, giving a REF error as a result.

What should I do in the continuation?

**Comment by theodormunteanu** [comment]
Update: It appears the automation ERROR is generated by a conflict of name in functions.
If I rename sum1 to sum_1, the program works.
That problem persisted even in 0.11.7.

Anyway, I am glad this problem was solved. Perhaps you could fix this bug in the next release. 
Cheers.

**Comment by gnyuan** [comment]
> Update: It appears the automation ERROR is generated by a conflict of name in functions.
> If I rename sum1 to sum_1, the program works.
> That problem persisted even in 0.11.7.
> 
> Anyway, I am glad this problem was solved. Perhaps you could fix this bug in the next release.
> Cheers.

Cheers, Thank you. I am in the same situation.

"Automation Error" is confusing.
