### ISSUE TITLE
Excel Hangs and consumes high resources when python running in background and a cell is selected

### ISSUE THREAD

**Issue by jvaldiviezo9** [ZoomerAnalytics/xlwings#824]
Hi! this is somewhat related to: https://github.com/ZoomerAnalytics/xlwings/issues/587
but in this case I'm wondering if there is a best way to handle events when a python script is running in the background and excel is being used to make formulas or writing contantly in a cell.

For example, I have the following code: 

```
import xlwings as xw
import time
count = 0

wb = xw.Book("Book1")
sht = wb.sheets["Sheet1"]
while(1):
    count += 1
    try:
        sht.range("A1").value = count
    except:
        print("Excel is busy")
    time.sleep(.8)
```
and this increments the value of the cell A1 every .8 seconds. The problem arises when I double click and activate another cell, Excel hangs and the program stop, it's like xlwings was desperately trying to communicating with excel and excel is executing background tasks. What I want is to know if there is a way to try for, let's say 2 seconds, and if the connection with the workbook doesn't resume, the exception occurs and my program continues.
I would like this because excel is not usable at all. Is there a way to set a timeout? or something I can do to make excel usable or completely pause the communication with xlwings while I'm using excel?

Thanks in advance!

**Comment by fzumstein** [comment]
Closed as #965 is the same issue, let's continue discussions there.
