### ISSUE TITLE
Does xlwings support on Win10?

### ISSUE THREAD

**Issue by ermai** [ZoomerAnalytics/xlwings#825]
I follow the instructions to enable excel access vba project module , however it works around on win7 but on win10 it always shows DLL error 49  "Make sure you are trusting access to the VBA project object module" .

**Comment by fzumstein** [comment]
sure, that must be something else that's going wrong. From the error message you're using an older version?

**Comment by jvaldiviezo9** [comment]
@ermai I think you need a mix of:
1.- http://docs.xlwings.org/en/stable/migrate_to_0.11.html
2.- http://docs.xlwings.org/en/stable/addin.html#addin-installation
3.- Excel Options - Trust Center - Trust Center Settings - Macro Settings - Trust Access to the VBA Project object model.
