### ISSUE TITLE
ModuleNotFoundError: No module named 'win32api' 

### ISSUE THREAD

**Issue by sdementen** [ZoomerAnalytics/xlwings#827]
when installing xlwings 0.11.7 on windows via pip, only comtypes-1.1.4 is installed (besides xlwings).
importing xlwings lead to the error message `ModuleNotFoundError: No module named 'win32api' `
i guess pywin32 should be added to the dependencies on windows...

**Comment by fzumstein** [comment]
I see they finally managed to release an official pip package since this year. so yes, that is now possible to include https://github.com/mhammond/pywin32#installing-via-pip

**Comment by raaghulr** [comment]
Hi, I am trying to run xlwings module in pypy, but facing hard time, "No module named ''win32api", tried cmd : "pypy -m pip install pywin32", it returned error: Could not find a version that satisfies the requirement pywin32, No matching distribution found for pywin32
![pypy](https://user-images.githubusercontent.com/26132550/120013454-5e529180-bffe-11eb-980c-5271f2a1e96b.JPG)
