### ISSUE TITLE
Access to Xltrail

### ISSUE THREAD

**Issue by Colin-b** [ZoomerAnalytics/xlwings#831]
Hi,

I have some pull requests that involve modification of the xlwings.xlam file: #832 , #833 , #834 

For you (and public) to be able to see those differences I would like to know if I could have access to the public xltrail repository (on xlwings project only of course)?

I don't really know how this works so feel free to reject my request if sending the modified xlam file on Github PR is enough.

Thanks

**Comment by fzumstein** [comment]
very good idea: just setup your fork: https://public.xltrail.com/#/?path=github.com%2FColin-b%2Fxlwings.git&branch=master

We're very happy to track any public project you have, not just xlwings ones. It's just not automated yet and also we just haven't advertised it yet.
