### ISSUE TITLE
using a returned custom object as input in UDF call

### ISSUE THREAD

**Issue by jkbgbr** [ZoomerAnalytics/xlwings#845]
Consider a UDF call returning a custom object. 
Is it possible to reuse this object in a subsequent UDF call somehow? In other words: can the Python object that is returned by the UDF be directly accessed and used as an input parameter in another UDF function?

When calling a UDF that returns a custom object I get the error saying "Unexpected Python Error: TypeError: Objects of type 'Vessel' can not be converted to a COM VARIANT (but obtaining the buffer() of this object could). Note: I did not try to define a custom converter, but then, the aim is not to have a nice printout.

**Comment by sdementen** [comment]
would this be the same as #555  ?

**Comment by jkbgbr** [comment]
Not necessarily the same but as far as I understand, similar. I have a Python custom object that I'd like to access similarly as if it was some COM-convertable variable.

**Comment by jkbgbr** [comment]
As a workaround I'm considering the following:
* create a UDF that uses xlrd to get the input and write it in an external file e.g. picke. This returns a bool as status report.
* when calling any UDF that needs the custom object the status is checked and if OK, the object can be constructed based on the values stored  in the external file.

**Comment by sdementen** [comment]
you could also look at https://github.com/ZoomerAnalytics/xlwings/pull/803 to see if it fits your bill

**Comment by jkbgbr** [comment]
this certainly looks good but if I understand correctly, the way to solve this issue is using another package?

**Comment by jkbgbr** [comment]
OK so the problem seems to be the following:
* I have a tree structure (using the anytree module) where I wanted to define the nodes by subsequent calls from excel - as one would do in a normal python session.
* by using a global variable for the root of the tree it is possible to avoid the problem of not having the possibility to reuse a returned object - all objects are persistent in the tree.
* however, the UDF server by default disconnects after each call(?); this can be disabled ([link](https://stackoverflow.com/questions/37923483/xlwings-use-global-variable)), but the resulting behaviour of xlwings is said to be experimental - possibly resulting in zombie processes etc.

We'll see later how this works out.

**Comment by jkbgbr** [comment]
So in the end it turns out that xlwings is not the tool for my problem as it is not suited for more complex problems like those where a program state is to be followed. For those you need a GUI if interactivity is needed. 
So the idea to use excel as a GUI replacement thus solving issues with versioning, control elements etc. and avoiding to learn a GUI framework etc. was not that good but still a nice learning experience.
