### ISSUE TITLE
auto recalculate udfs when open a excel file

### ISSUE THREAD

**Issue by yangxuesong** [ZoomerAnalytics/xlwings#847]
I defined some UDFS on some sheets range and also used some excel internal functions such as NOW().
When I open the excel file, the area which references the excel internal functions will auto recalculate(refresh), but the xlwings UDFS do not.
Are there some kind of settings I should aware to make xlwings UDFS auto recalucate on startup?

**Comment by DougAJ4** [comment]
You can do this in VBA.  In the VB editor, go to the ThisWorkbook object in the Project window, then in the edit window select Open from the right hand drop down box.  You can then create a short macro that will run on open like:

Private Sub Workbook_Open()
    Application.CalculateFull
End Sub

**Comment by yangxuesong** [comment]
It works! Thanks a lot.

One more question: 
when I use DCOM to open(render) a xlsm file and save as a xlsx file with the following code(c# or python comtype, there is no difference). After executing the code below, the Excel Process is still in windows process manager. This scenario doesn't happen on excel file without xlwings enabled.
 
            Application xlApp = new Application();          
            Workbook xlWorkbook = xlApp.Workbooks.Open("myproject.xlsm");
            xlApp.DisplayAlerts = false;
            xlApp.Visible = false;
            xlWorkbook.SaveAs("out.xlsx", XlFileFormat.xlOpenXMLWorkbook);
            xlWorkbook.Close();
            Marshal.ReleaseComObject(xlWorkbook);
            xlApp.Quit();
            Marshal.ReleaseComObject(xlApp);
