### ISSUE TITLE
Run-time error '62' - Input past end of file

### ISSUE THREAD

**Issue by mitevpi** [ZoomerAnalytics/xlwings#850]
Trying to install xlwings and the Excel addin, but no matter what I do, I get this error:

![image](https://user-images.githubusercontent.com/25568566/38624330-d4e851ae-3d75-11e8-90bd-07b9b77cf7fe.png)

Any idea what this could be?

**Comment by fzumstein** [comment]
Can you unlock the xlwings addin by typing the password `xlwings` and see where it fails? Maybe check also how your `xlwings.conf` file looks under `.xlwings\xlwings.conf`

**Comment by mitevpi** [comment]
Perfect! Thanks so much, this seemed to do it!
