### ISSUE TITLE
Setting Cell Color Doesn't Work

### ISSUE THREAD

**Issue by mitevpi** [ZoomerAnalytics/xlwings#851]
I'm trying to set the interior color fill of some cells, and going off your online documentation:

![image](https://user-images.githubusercontent.com/25568566/38898829-25a1c3da-4264-11e8-8b66-95e95e7adcee.png)

When I attempt to get the color, it works just fine. However when I attempt to set the color, the entire Excel application freezes and crashes. I've tried several workarounds as documented across StackOverflow, but to no avail:
![image](https://user-images.githubusercontent.com/25568566/38898801-13d4b7ca-4264-11e8-84cb-d45ae34ca2f3.png)

**Comment by DougAJ4** [comment]
Are you running this as a UDF?

If I run your code from Python it works OK, but if I enter it as a UDF in Excel it locks up at the line you indicated.

UDFs are only supposed to return values, not change properties of other worksheet cells.  I don't know why the .api.Font.Color works, but I doubt that you will get the others to work from a function.

If you call the function from a VBA subroutine it should work.

**Comment by mitevpi** [comment]
I see, thanks for letting me know!
