### ISSUE TITLE
deleting comment from a cell

### ISSUE THREAD

**Issue by pisteps** [ZoomerAnalytics/xlwings#856]
is it possible to delete a comment from a cell?

i managed to create a comment and read a comment, but can't delete it.

```
import xlwings as xw
wb = xw.apps[0].books[ 'test.xlsx']
```

#write a comment
`wb.sheets['sheet1'].range('a1').api.AddComment('Some Text')`

#read a comment
`test = wb.sheets['sheet1'].range('a1').api.Comment.Text()`

i tried this one to delete the comment but i get a "com_error":
`wb.sheets['sheet1'].range('a1').api.DeleteComment()`

**Comment by fzumstein** [comment]
Just use `Delete()` instead of `DeleteComment()`

**Comment by pisteps** [comment]
thanks. is there anything that deletes just the comment and not the content of the cell?

**Comment by fzumstein** [comment]
I meant off course `wb.sheets['sheet1'].range('a1').api.Comment.Delete()`

**Comment by pisteps** [comment]
right. thanks a lot!

**Comment by pisteps** [comment]
in case i want to delete all comments from a range is there something i can use?
i tried this but gives an error:
`wb.sheets['sheet1'].range('a1:b100').api.Comment.Delete()`
