### ISSUE TITLE
quick question to xlwings runpython install and run on mac

### ISSUE THREAD

**Issue by steveycchen** [ZoomerAnalytics/xlwings#882]
Hi, 
I am new to python and mac. When I run hello.py and helloword.xlsm, it failed and tell me the following message.
sh: /Users/cameron/Environments/xlwings/bin/python: no such file or directory

Is there any missing of my setting for python or xlwings? I am running mac office 2016 and use conda to install xlwings.

**Comment by fzumstein** [comment]
did you run `xlwings runpython install` as mentioned in the blue box here? http://docs.xlwings.org/en/stable/installation.html

**Comment by steveycchen** [comment]
I did run xlwings runpython install once and came with message "Successfully installed RunPython for Mac Excel 2016!". 

I am wondering if it was caused my installation of Anaconda using pyenv and conda install -c anaconda xlwings.

Here is my some information.

path of python (by which python) and xlwings (by xlwings.__path__):
/Users/steve/.pyenv/shims/python
/Users/steve/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/xlwings

~/.bash_profile:
export PYTHON_MAC=/Users/steve/.pyenv/shims/python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

Please have a look and further advice. Thank you.

**Comment by fzumstein** [comment]
without changing the settings, xlwings will use the python interpreter/env that you get when you type `which python` at your Terminal. If that is not where xlwings is installed, make sure to add the path to that env to the Interpreter setting in the addin: http://docs.xlwings.org/en/stable/addin.html#global-settings

**Comment by steveycchen** [comment]
Do you mean to add the python installed location to "interpreter" textbox in xlwings addin Ribbon?
In my case, add  /Users/steve/.pyenv/shims/python to interpreter?

**Comment by fzumstein** [comment]
yes. Excel needs to know with which python interpreter you want to communicate. If you don't provide a specific one, it takes the one that is started by typing `python` at the Terminal.

**Comment by steveycchen** [comment]
Thank you. It works now!
