### ISSUE TITLE
How to set default value for an argument in UDF?

### ISSUE THREAD

**Issue by xkeecs** [ZoomerAnalytics/xlwings#884]
It seems xlwings does not support keyword argument in UDF. I wonder what's a recommended way of setting default values for an argument in xlwings? 

Suppose I have following function:

`@xw.func`
`def calculate(a, recalc):`
"Operations on a and cache the result"
     `return result`

It would be nice to set recalc to False so we don't recalculate it everytime but it also provides the option to recalculate if we set it to True.

I wonder what is a good way to do it? Thanks.

**Comment by DougAJ4** [comment]
You can assign default values to an argument:
