### ISSUE TITLE
xlwings not loading the intrepreter from ~/.xlwings.conf

### ISSUE THREAD

**Issue by spitfiredd** [ZoomerAnalytics/xlwings#885]
I get the following error when I try to boot up the xlwings add in.
![image](https://user-images.githubusercontent.com/2820827/40811269-8ecfc782-64fe-11e8-823b-1a805a465d50.png)

### ~/.xlwings.conf
```
"USE UDF SERVER","True"
"INTERPRETER","C:\Anaconda3\envs\data_science"
"PYTHONPATH","C:\Users\spitf\Documents\python-projects\xlwings\test"
```

Why is it not looking in the correct folders for the dlls?

**Comment by fzumstein** [comment]
the interpreter needs to include pythonw.exe

Daniel Donovan <notifications@github.com> schrieb am Fr., 1. Juni 2018,
00:18:

**Comment by thomasmortiz** [comment]
I am having the same problem, and I did include the full path to pythonw.exe in xlwings.conf.  The xlwings DLLs are in my venv folder next to pythonw.exe.

Error:
Run-Time error '1'
Could not load xlwings32.0.11.8.dll from either of the following folders:
"C:\Users\tortiz\AppData\Local\Continuum\anaconda3\envs\venv"
"C:\Users\tortiz\AppData\Local\Continuum\anaconda3\envs"

xlwings.conf (Worksheet in Workbook):
Interpreter | "C:\Users\tortiz\AppData\Local\Continuum\anaconda3\envs\venv\pythonw.exe"
PYTHONPATH | "T:\PETMIN\TOrtiz\projects\audit_tools\excel_audit_tools.py"
UDF Modules |  
Debug UDFs | FALSE
Log File |  
Use UDF Server | TRUE

Environment:
Windows 10 x64
Anaconda3 Python 3.6.5
xlwings 0.11.8
Excel 2016

**Comment by thomasmortiz** [comment]
I solved this problem by deleting my workbook-specific xlwings.conf sheet and correcting the global .xlwings/xlwings.conf file, which had some bad formatting in it initially.  I can only get my UDFs to execute if I rely on the global config file.
