### ISSUE TITLE
xw.arg for numpy polyfit doesn't work 'Object Required', for Excel ranges

### ISSUE THREAD

**Issue by kiann00** [ZoomerAnalytics/xlwings#899]
Below is the code, which looks to follow from the syntax advised in http://docs.xlwings.org/en/stable/udfs.html.

However, excel returns an error message 'object required'.

```
import xlwings as xw
import numpy as np

@xw.func
@xw.arg('x', np.array, ndim=1)
@xw.arg('y', np.array, ndim=2)
@xw.ret(expand='table')
def py_polyfit(x, y, degree):
    results = np.polyfit(x, y, degree)
    return results
```

**Comment by DougAJ4** [comment]
Try adding:
import numpy.polynomial.polynomial as poly

then: 
results =poly.polyfit(x, y, degree)

should work

Also  see:
https://newtonexcelbach.com/2018/05/24/more-numpy-with-excel-and-xlwings/

for open source code linking Excel to Numpy.

**Comment by fzumstein** [comment]
object required normally means that you forgot to set the reference to xlwings, see: https://docs.xlwings.org/en/stable/addin.html#installation
