### ISSUE TITLE
Sometimes xlwings works perfectly and other times it doesn't. Basically it can't restart UDF sever.

### ISSUE THREAD

**Issue by gaurav-kumar-isi** [ZoomerAnalytics/xlwings#900]
I have been able to run and use xlwings on some occasion without any glitch. So I don't think there is any issue with my code. But when I try to run the same code again it fails to run. 

Basically I am trying to import a function which I have defined in the corresponding python file. I have been able to run this file successfully in the recent past. I have set the path of interpreter and python correctly. But when I push "Restart UDF Server" nothing happens.  I have noticed that when the code is running perfectly there is a message saying "xlwings server is running" written in my python console. It is missing when the "Restart UDF Server" fails.

**Anyways, when I execute the function I get the error message saying "No command specified in the configuration, can't auto start the server 1000".**

I think all of this means that xlwings add-in is not able to establish contact with the python file. 

Is there a way I can circumvent this issue?

**Comment by RZachLamberty** [comment]
I see the same. excel 2013 (15.0.5045.1000), `xlwing-0.11.8` install via `conda`, windows 7 pro sp1.

**Comment by fzumstein** [comment]
were you ever able to replicate this reliably?
