### ISSUE TITLE
Reading drop down list values

### ISSUE THREAD

**Issue by rishir95** [ZoomerAnalytics/xlwings#901]
Is there any way I can extract all the options from drop down cell rather than just the selected value?

**Comment by mdigi** [comment]
You can use the api property:
`wb = xw.Book('test.xls')`
`sheet = wb.sheets[0]`
`options = sheet.range('A1').api.Validation.Formula1`

**Comment by jjiteshh** [comment]
I am trying to read the items in the drop down list. I tried using this above solution, but it gives me the name of the list and not the contents of the list.

**Comment by Dorongafsou** [comment]
any updates?

**Comment by shirishbhalekar** [comment]
any updates

**Comment by fzumstein** [comment]
this issue is closed. please open a new issue with a sample workbook attached. You can also look at the validation API in VBA to guess the syntax via `.api`: https://docs.microsoft.com/en-us/office/vba/api/excel.validation
