### ISSUE TITLE
File opens automatically after saving

### ISSUE THREAD

**Issue by cemremengu** [ZoomerAnalytics/xlwings#902]
I am on windows using the following snippet:

```
import xlwings as xw
wb = xw.Book('template.xlsx')
sht = wb.sheets['test']
sht.range('A1').value = [['Foo 1', 'Foo 2', 'Foo 3'], [10.0, 20.0, 30.0]]
wb.save('result.xlsx)
```

After the code terminates, the file opens automatically. Is this expected? If so, is there a way to turn it off?

**Comment by fzumstein** [comment]
`save` with a name is like `SaveAs` in Excel: it saves the current file under the new name. i.e. it renames the open file rather than opening after terminating. so yes, it's expected.
