### ISSUE TITLE
Cannot use xlwings in general

### ISSUE THREAD

**Issue by kylefoley76** [ZoomerAnalytics/xlwings#903]
hi,
thank you for building this software.  However, I cannot get it to work.  What I am trying to do is save an excel workbook from a python code.  To the best of my knowledge they do not yet have python code which can input data into an xlsm doc, though they have code which can get data from xlsm files. For this reason I've had to build two workbooks, one for macros and another for data entry. I'm trying to get the macro found in xlwings_w_macro to save the data in xlwings_wo_macro, so that python can then get the new updated data.  I have made a video that explains what I mean.  

https://drive.google.com/file/d/1fDX58ufxH0WyiEz-oXsWJYZqIM8-MRCQ/view?usp=sharing

[xlwings_temp2.xlsx](https://github.com/ZoomerAnalytics/xlwings/files/2129223/xlwings_temp2.xlsx)

Further, xlwings will cause a new Excel app to open and that simply will make things unworkable. 

Thanks in advance for your help.

**Comment by kylefoley76** [comment]
For some reason python and xlsm files cannot be uploaded which is strange since it seems that they are the most important ones.  in any case the other two files are available here:

https://drive.google.com/file/d/1SEVxEeiKz1ZFa0tab_aMsWu3n53NspZ7/view?usp=sharing

https://drive.google.com/file/d/1kfhwjY4lAHuBy3yGuDUrDHTdchV4cO8k/view?usp=sharing

**Comment by fzumstein** [comment]
You need to get the app object from your workbook via `w_macro_book.app` instead of instantiating a new one with `app = App()`
