### ISSUE TITLE
RunPython: multiple arguments not work on mac Excel

### ISSUE THREAD

**Issue by steveycchen** [ZoomerAnalytics/xlwings#905]
Hi,
I am trying to pass 2 more arguments to RunPython from mac Excel but not working. After executed the scripts, It simply has no writing results on Excel sheet and no error warning show up.

The same code does the work on windows Excel. Please help!

VBA code:
```
RunPython ("import hello; hello.world('arg1' , 'arg2')")
```

hello.py
```
def world(write_sht, base_url):
    wb = xw.Book.caller()
    wb.sheets[0].range('A1').value = 'Hello World!'
    wb.sheets[0].range('A2').value = 'This is write_sht: ' + str(write_sht)
    wb.sheets[0].range('A3').value = 'This is base_url:  ' + str(base_url)
```

Thank you.
Steve

**Comment by fzumstein** [comment]
It's a bug in the applescript helper file: https://github.com/ZoomerAnalytics/xlwings/blob/master/xlwings/xlwings.applescript#L5 that happens when you use multiple arguments
