### ISSUE TITLE
Simple Q: How are empty cells in a range (used in an xlwings UDF) handled by python lists?

### ISSUE THREAD

**Issue by bushidoji** [ZoomerAnalytics/xlwings#907]
In short, I'm wondering how blank cells are handled by xlwings UDF functions.  When compiled to a list in python on the backend, are blank cells represented by "None", "NA", "NaN"?

Take the simple example: 
Assume that every other cell in the range A1:A10 is blank (no contents), with the rest containing the number "1"...
If I call the range A1:A10 within "simpleUDF", as such: "=simpleUDF(A1:A10)"

How will this translate into a list in python?
Would it be something like [1,None,1,None,1... etc.] ?

---

For more color, my use case is as follows:

This UDF is intended to calculate the absoluteReturn of a stock over some time period:
@xw.func
def absoluteReturn(retList):
    retSeries = pd.Series(retList)
    return ((retSeries/100 + 1).prod() - 1 )*100

Example usage of this UDF would be as follows:
=absoluteReturn(A1:A12)

...where A1:A12 is a range of 12 monthly returns for a single stock. In this case an absolute return over 1-yr is calculated.

Everything works correctly, but I'd like to add some logic to detect if the input range contains any blank cells (typically at the beginning or end of the range - indicating not enough trading history to accurately calculate the metric), and to return "none" in that case.

Just trying to get a sense of what I should be looking for, and figured I'd ask here since debugging doesnt work in v.0.11.7 ... not sure how I can query this stuff 

Thx guys,
Bushidoji

**Comment by fzumstein** [comment]
UDFs and writing to the sheet via `range` object behaves the same, see here: http://docs.xlwings.org/en/stable/converters.html#default-converter

not sure why your debugger doesn't work ,but as a quick workaround you could switch the interpreter to `python` instead of `pythonw` and you'll be able to use print statements at least.

**Comment by fzumstein** [comment]
closing this, feel free to reopen if there's still something unclear.
