### ISSUE TITLE
xlwings running problems about pywin32 in windows 

### ISSUE THREAD

**Issue by wwcbitcoin** [ZoomerAnalytics/xlwings#911]
I got a trouble to run xlwings in Windows operating system. It gives me this error about no module named "win32.api". I already install pywin32 in Pycharm and I am confused about this error. I also attached the picture of the error.

Thanks,

Sincerely,

![xlwings](https://user-images.githubusercontent.com/40746495/42392036-5fa06a38-811f-11e8-9d66-b4092ccaf98b.png)

**Comment by fzumstein** [comment]
were you able to resolve the issue?

**Comment by wwcbitcoin** [comment]
Hi Felix,

I solve it by first search for python 3.7 (32-bit) and then right click to
select open file location, and then right click python 3.7 (32-bit) in the
folder to select open file location. Then it should be at the path similar
to picture "1".

After that, please click 'Script' folder and in the Script folder, please
press shift key and right click to select windows power shell. After that,
you could see the command window like picture "2". Then please input py
-3.7 -m pip install pypiwin32  and press enter. Finally you could see the
command window like picture "3". After that, the excel file "sample.xlsm"
should work. Please let me know if you have any questions.

Thanks,

Sincerely,

Wencheng

**Comment by fzumstein** [comment]
great, glad it works and sorry for slow reaction!
