### ISSUE TITLE
test/fix for python 3.7

### ISSUE THREAD

**Issue by fzumstein** [ZoomerAnalytics/xlwings#914]
maybe there's something going on: https://stackoverflow.com/questions/51351564/excel-datetime-objects-crash-my-python-3-7-shell

**Comment by aaroncle** [comment]
Had the same problem on python 3.7, just tried it on python 3.6 and it worked fine. It is almost definitely a 3.7 issue.

**Comment by fzumstein** [comment]
ok thanks for feedback, will look into it asap

**Comment by fzumstein** [comment]
It's an error in pywin32, I've opened an issue there: https://github.com/mhammond/pywin32/issues/1221

**Comment by fzumstein** [comment]
For now, you can use xlwings with python 3.7 by upgrading pywin32 to the version downloaded from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pywin32

**Comment by fzumstein** [comment]
this is now fixed with pywin32 224 from pypi
