### ISSUE TITLE
spyder UDF debug not working

### ISSUE THREAD

**Issue by cristipurdel** [ZoomerAnalytics/xlwings#915]
I am trying to debug python with the default Spyder ipdb from Anaconda but I cannot figure it out if I am doing something wrong or it is not working at all

Can somebody post a step by step guide on how to do it?

From [http://docs.xlwings.org/en/stable/debugging.html?highlight=Serve](url) it says to use PyDev or PyCharm but nothing about Spyder

Maybe this is related also to this:
[https://github.com/ZoomerAnalytics/xlwings/issues/790](url)

**Comment by fzumstein** [comment]
Can you describe what happens?

**Comment by cristipurdel** [comment]
If Debug UDFs = TRUE : 
No command specified   in the configuration, cannot autostart server

If Debug UDFs = FALSE : 
`RuntimeError:   input(): lost sys.stdin         line = input(self.prompt)       File   "C:\Users\aw004ng\Anaconda3\lib\cmd.py", line 126, in cmdloop         self.cmdloop()       File   "C:\Users\aw004ng\Anaconda3\lib\pdb.py", line 321, in   _cmdloop         self._cmdloop()       File   "C:\Users\aw004ng\Anaconda3\lib\pdb.py", line 352, in   interaction         self.interaction(frame,   None)       File "C:\Users\aw004ng\Anaconda3\lib\pdb.py",   line 261, in user_line         self.user_line(frame)       File   "C:\Users\aw004ng\Anaconda3\lib\bdb.py", line 69, in   dispatch_line         return   self.dispatch_line(frame)       File   "C:\Users\aw004ng\Anaconda3\lib\bdb.py", line 51, in   trace_dispatch         return 2 *++ (x + y)       File   "d:\share\documents\python\xlwings\myproject\myproject\myproject.py",   line 19, in double_sum         return 2 *++ (x + y)       File   "d:\share\documents\python\xlwings\myproject\myproject\myproject.py",   line 19, in double_sum         ret = func(*args)       File   "C:\Users\aw004ng\Anaconda3\lib\site-packages\xlwings\udfs.py",   line 250, in call_udf         res = call_udf(script, fname,   args, this_workbook, FromVariant(caller))       File   "C:\Users\aw004ng\Anaconda3\lib\site-packages\xlwings\server.py",   line 190, in CallUDF         return func(*args)       File   "C:\Users\aw004ng\Anaconda3\lib\site-packages\win32com\server\policy.py",   line 586, in _invokeex_         return S_OK, -1,   self._invokeex_(dispid, lcid, wFlags, args, None, None)       File   "C:\Users\aw004ng\Anaconda3\lib\site-packages\win32com\server\policy.py",   line 283, in _invoke_         return self._invoke_(dispid,   lcid, wFlags, args)       File   "C:\Users\aw004ng\Anaconda3\lib\site-packages\win32com\server\policy.py",   line 278, in _Invoke_`
--

I am not getting any VBA MsgBox nor anything happens with the default settings from Spyder
I have more complex UDFs that use xlwings that run fine, so I guess I am missing some xlwings/Spyder settings 


This is my code
`import xlwings as xw
import pdb



def hello_xlwings():
    wb = xw.Book.caller()
    wb.sheets[0].range("A1").value = "Hello xlwings!"


@xw.func
def hello(name):
    return "hello {0}".format(name)

@xw.func
def double_sum(x, y):
    """Returns twice the sum of the two arguments"""
    pdb.set_trace()
    return 2 *++ (x + y)

if __name__ == '__main__':
    xw.serve()`

**Comment by fzumstein** [comment]
You don't need to use `pdb.set_trace()` in Spyder as you set a breakpoint directly in the Spyder UI (double click on the line number). Then Run the file by going to `Debug > Debug`. 

Spyder console should output something along these lines:

```

debugfile('C:/Users/felix/Desktop/mytest/mytest.py', wdir='C:/Users/felix/Desktop/mytest')
> c:\users\felix\desktop\mytest\mytest.py(1)<module>()
----> 1 import xlwings as xw
      2 
      3 
      4 def hello_xlwings():
      5     wb = xw.Book.caller()


ipdb> xlwings server running, clsid={506E67C3-55B5-48C3-A035-EED5DEEA7D6D}
```

When you recalculate the `hello` function in Excel, it will stop in the Spyder debugger.

If you still get `cannot autostart server`, make sure that the python interpreter that you configure in the xlwings addin and the one that spyder uses, are the same.

**Comment by cristipurdel** [comment]
Thank you, 
I managed to get it working, with

Interpreter | pythonw
UDF Modules | differentfilename.py
Debug UDFs | TRUE

I would suggest for your next iteration to add more details to your debugging docs to make it easier to newcomers :)
- your previous explanations
-  better use xlwings.conf when dealing with different naming py/xlm files
- excel toolbar settings will change across all open excel files
- always write Interpreter filename (not sure if default is written or I just delete it by mistake )
- in vba xlwings_udfs try to add in addition to 
'Autogenerated code by xlwings - changes will be lost with next import!
a general function desciption for all arguments, since the samename.py / samename.xlsm is not the general case
