### ISSUE TITLE
FileNotFoundError when using RunPython macro.

### ISSUE THREAD

**Issue by tkoskinen1** [ZoomerAnalytics/xlwings#918]
I'm having a bit of a strange problem. I have a python script script.py that tries to open a file:

```
def open_file():
    open('filename.txt')
```

if I run this script from the command line the process finishes without error. However, in the same directory as the script I have an Excel workbook with a macro button with code:

```
Private Sub CommandButton1_Click()
    RunPython ("import script; script.open_file()")
End Sub
```

When I press this button I get FileNotFoundError: [Errno 2] No such file or directory: 'filename.txt'.
What could be causing this?

**Comment by fzumstein** [comment]
You need to use the full file path for `filename.txt` as the current working directory is currently not controllable.

**Comment by tusmo** [comment]
That seems to fix it but I'm pretty sure the macro worked without any problem yesterday and I haven't made any changes to it. How can that  happen?

**Comment by fzumstein** [comment]
the cwd is currently not guaranteed to be the same every time and might change depending on the python installation or the folder from where you start it from.

**Comment by xjdeng** [comment]
Duplicate of #842
