### ISSUE TITLE
xlwings python file handling issue

### ISSUE THREAD

**Issue by akashsharma03** [ZoomerAnalytics/xlwings#928]
Whenever I write a file using my python  script(simple file handling), and the script is run using RunPython command on vba, then no matter what path I give for my file, the file is always saved in my documents.

Has someone come across this issue or solved this?

**Comment by fzumstein** [comment]
which OS and Excel version are you on?

**Comment by akashsharma03** [comment]
Windows and Excel 2013,
BTW I figured it out. It was because I was getting os.cwd() which pointed to My Documents rather than the workbook's location when RunPython interpreter was executed through vba.
