### ISSUE TITLE
deleting comments from a range

### ISSUE THREAD

**Issue by pisteps** [ZoomerAnalytics/xlwings#930]
hello,
i know (thanks to @fzumstein ) that i can delete a comment from a cell that contains a comments by using:
`wb.sheets['sheet1'].range('a1').api.Comment.Delete()`

but if i need to quickly delete all comments from a range (that may or may not contain comments), is there anything i can use?
i tried the following but it does not work:
`wb.sheets['sheet1'].range('a1:b100').api.Comment.Delete()`

thanks

**Comment by fzumstein** [comment]
Use:

```
wb.sheets['sheet1'].range('a1:b100').api.ClearComments()
```

**Comment by pisteps** [comment]
thanks!
