### ISSUE TITLE
read persian characters in a excel file with “xlwings”

### ISSUE THREAD

**Issue by Mohsen62m** [ZoomerAnalytics/xlwings#932]
According to [read persian characters in a excel file with “xlwings”](https://stackoverflow.com/questions/52054295/read-persian-characters-in-a-excel-file-with-xlwings?noredirect=1#comment91083465_52054295), how to read persian characters in a excel file with “xlwings”?

[data.xlsx](https://github.com/ZoomerAnalytics/xlwings/files/2332863/data.xlsx)

Thank you

**Comment by fzumstein** [comment]
I can't replicate the issue, see screenshot from a jupyter notebook:
<img width="447" alt="screen shot 2018-08-29 at 22 47 18" src="https://user-images.githubusercontent.com/2265504/44814652-aa6a1080-abdd-11e8-9656-00f4f763ab5b.png">

**Comment by Mohsen62m** [comment]
Thank you.
I used "print(val)" and checked the result in command prompt. I expected to see "?" marks for persian chars, but I saw the error. Now, i save the results in a List and see the "Out[2]" result in the screenshot  above. 
But how to remove the "\u200f"?
Use "replace" or there is a best solution?

**Comment by fzumstein** [comment]
you shouldn't need to do anything special. what are you trying to achieve?

**Comment by Mohsen62m** [comment]
I need to show the persian word to the user.

**Comment by fzumstein** [comment]
where? on the side of Excel or Python?

**Comment by Mohsen62m** [comment]
Python

**Comment by Mohsen62m** [comment]
in command prompt? I see that error.

**Comment by fzumstein** [comment]
That is a limitation of the command prompt, it's not an issue with xlwings. Try to run it in a jupyter notebook or have a look at https://stackoverflow.com/questions/26162197/how-to-type-utf-8-characters-in-windows-7-command-prompt. Closing this as it's not an xlwings issue.

**Comment by Mohsen62m** [comment]
OK. Thank you a lot.
