### ISSUE TITLE
xlwings api is missing on fresh install

### ISSUE THREAD

**Issue by bobjoylove** [ZoomerAnalytics/xlwings#934]
I'm trying to access any and all of the xlwings api features like

`sht.api.Copy()` and  `rng.api.Validation.add()`

raises

> Traceback (most recent call last): File "/Applications/PyCharm CE 2018.2 EAP.app/Contents/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec exec(exp, global_vars, local_vars) File "", line 1, in File "/usr/local/lib/python3.6/site-packages/aeosa/appscript/reference.py", line 577, in getattr raise AttributeError("Unknown property, element or command: {!r}".format(name)) from e AttributeError: Unknown property, element or command: 'Copy'
and 
> AttributeError: Unknown property, element or command: 'Validation'

I don't see those Copy() Validation in the api. autocomplete

I tried` pip install appscript`

> Requirement already satisfied: appscript in /usr/local/lib/python3.6/site-packages (1.0.1)

I also used from Excel Tools/Addins added the file in /usr/local/lib/python3.6/site-packages/xlwings/addin

So now I'm stuck. Seeing this on two computers both with fresh installs of 0.11 but xlwings is working fine. I have not ever used or installed older versions of xlwings.

MacOS version 10.13.6. Excel 2016 for Mac V16.15 xlwings version 0.11.8

**Comment by bobjoylove** [comment]
I see this
`sht.api.copy()`

> AttributeError: Unknown property, element or command: 'copy'

**Comment by bobjoylove** [comment]
Would still love to fix this!

**Comment by isodownload** [comment]
hi,
 I am unable to replace "JAMES" "ALEX" using xlwings.

wb.sheets('OPEN').range('A2:A2000').api.Replace('JAMES', 'ALEX')
wb.sheets('OPEN').range('A2:A2000').api.replace('JAMES', 'ALEX')

tried both ways.
