### ISSUE TITLE
nested list assignment requires row lists to be same length

### ISSUE THREAD

**Issue by jasonsross** [ZoomerAnalytics/xlwings#935]
I'm trying to import data from a csv file that has inconsistent row dimensions. For example

```
1,2,3,4,5
1,2,3,4
```
Excel itself can open such a csv file that can have all sorts of different lengths of delimited row data with even empty rows without issue.

But when trying to input such data into an empty sheet with xlwings such as with 
```
x2 = [[1,2,3,4,5], [1,2,3,4]]
sheet.range('A1').value = x2
```
It doesn't insert anything meaningful into the sheets. I get blank cells with some #N/A

It only works when the rows of the list all have the same length (here 4) such as:
```
x = [[1,2,3,4], [1,2,3,4]]
sheet.range('A1').value = x
```

So what's the recommended way using xlwings to take data from a csv file that does not have consistent row dimensions and fill an active excel sheet? I've tried looping each row but it takes a couple seconds per row so this isn't practical for importing a lengthy csv file. I'm going to try padding my list rows with empty values so they all have the same length and I'm sure it will work but it seems like an odd solution.

**Comment by fzumstein** [comment]
Use pandas' read_csv method (https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) which gives you a dataframe that you can easily assign to a range.

**Comment by jasonsross** [comment]
Pandas cannot read a csv file who's first line has less row elements than the row with the most elements, such as a csv that looks like:

```
1,2,3,4
1,2,3,4,5
```

I get:
ParserError: Error tokenizing data. C error: Expected 4 fields in line 2, saw 5

Although if you do pass it a names list (column names), that has the length of the maximum row length, it can work...

So the solution for xlwings would then be read in csv as nested list, find the length of the maximum row, create some arbitrary list of column names with that length, reload the data into a DataFrame, then finally assign it to the excel sheet

This seems really cumbersome for something that xlwings seems like it should be able to handle directly with the sparse nested list itself.

**Comment by fzumstein** [comment]
you don't need to turn it into a dataframe if it's an equal length list of list. but yes, my suggestion would still be to be able to read it with pandas by providing a list of cols.

**Comment by fzumstein** [comment]
I am closing this as xlwings now throws an error when not all rows are of equal length.
