### ISSUE TITLE
'file not found xlwings32-dev.dll' when pressing restart UDF Server in the xlwings ribbon

### ISSUE THREAD

**Issue by Louis-Alexis** [ZoomerAnalytics/xlwings#948]
Hi,

I would like to install xlwings on windows 10.
I can't install it via conda or pip command because my company is using a proxy and a firewall so i've installed it via 'python setup.py install' command (as i did on another machine running on windows 7  and xlwings work really fine on it) Everything went fine then i runned the 'xlwings addin install' command and i've opened excel. 
The xlwings ribbon is well here but when i click on restart Udf server, i have the following message : Run-time error 53 : file not found xlwings32-dev.dll

config : 
windows 10 64 bits
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Excel 2016

thank you very much in advance

**Comment by fzumstein** [comment]
You can still use pip with the downloaded package from pypi: `pip install C:\path\to\your\xlwings-.....tar.gz`

**Comment by Louis-Alexis** [comment]
Okay, so i did xlwings addin remove
than pip uninstall xlwings
then i've tried with your command and it worked well
then i did xlwings addin install -> ok
i've launched excel and i still get this error

**Comment by fzumstein** [comment]
try to install the addin from the release page as suggested here: http://docs.xlwings.org/en/stable/addin.html#installation

**Comment by Louis-Alexis** [comment]
oh actually i've did that with the package from github, i've tried with pypi and it works i don't have this error anymore.
But one more thing, could it be possible that if i install the package from a location on another drive ( not C: ) it doesn't work ?

many thanks for your support, it is always a pleasure

**Comment by fzumstein** [comment]
no, the issue is that you can't use the packages from GitHub as they are just the packaged source code, not the built files.

**Comment by Louis-Alexis** [comment]
Okay ! really good to know ! thank you very much :)
