### ISSUE TITLE
Import Functions on the Ribbon does not load functions specified in UDFModule

### ISSUE THREAD

**Issue by somethingbeta** [ZoomerAnalytics/xlwings#950]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 7

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.11.8
Office 2010
Python 3.6
Anaconda 5.0.1

Pressing Import functions does not load functions in Py files specified 

Hi was wondering if anyone had any ideas as to why this could be happening. 

this is what is happening. 
1. Open Spreadsheet (*.xlsm) Hit import functions on the Ribbon.. all the UDF's are visible functions are annotated with @xw.func

2. Add new function (annotated ofcourse) hit Import Functions Ribbon the new function is not visible 

Have tried various options of this, i.e. Restart UDF Server then Import Functions etc .. but still nothing

Am at a loss as to what could be causing this

**Comment by fzumstein** [comment]
In `1.`, do you mean that the function wrappers are imported correctly the very first time?

**Comment by somethingbeta** [comment]
Yes that is correct

**Comment by fzumstein** [comment]
You can try debug this using the debug server: https://docs.xlwings.org/en/stable/debugging.html#udf-debug-server

**Comment by somethingbeta** [comment]
I can use those to debug the "import" ?  ok let me try i thought this was to be used to debug individual functions

**Comment by fzumstein** [comment]
it's for both

**Comment by somethingbeta** [comment]
solved by upgrading to 12.1
