### ISSUE TITLE
"Python has stopped working" - Windows 7 error pop-up with Python 3.7.0

### ISSUE THREAD

**Issue by pybokeh** [ZoomerAnalytics/xlwings#955]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 7

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings==0.12.1, Excel 2016, Python 3.7.0
#### Describe your issue (incl. Traceback!)
I run code in Jupyter notebook cell and I get a Windows dialog pop-up message that says "Python has stopped working".  Then my Jupyter notebook kernel dies.  I get no traceback, not even in my terminal console where I am running my Jupyter notebook server.  It just says kernel restarted.  But, if I run a Python 3.6.4 jupyter notebook server and run the exact same code, everything works fine.  So not sure if there is a problem with Python 3.7.0.  Here is my pip freeze output:

altair==2.2.2                               
asn1crypto==0.24.0                          
astroid==2.0.4                              
autopep8==1.4                               
backcall==0.1.0                             
beautifulsoup4==4.6.3                       
bleach==2.1.4                               
certifi==2018.8.24                          
cffi==1.11.5                                
chardet==3.0.4                              
colorama==0.3.9                             
colorlover==0.2.1                           
comtypes==1.1.7                             
cryptography==2.3.1                         
cufflinks==0.14.4                           
cycler==0.10.0                              
decorator==4.3.0                            
defusedxml==0.5.0                           
entrypoints==0.2.3                          
et-xmlfile==1.0.1                           
html5lib==1.0.1                             
idna==2.7                                   
ipdb==0.11                                  
ipykernel==4.9.0                            
ipython==6.5.0                              
ipython-genutils==0.2.0                     
ipywidgets==7.4.2                           
isort==4.3.4                                
jdcal==1.4                                  
jedi==0.12.1                                
Jinja2==2.10                                
jsonschema==2.6.0                           
jupyter==1.0.0                              
jupyter-client==5.2.3                       
jupyter-console==5.2.0                      
jupyter-contrib-core==0.3.3                 
jupyter-contrib-nbextensions==0.5.0         
jupyter-core==4.4.0                         
jupyter-highlight-selected-word==0.2.0      
jupyter-latex-envs==1.4.4                   
jupyter-nbextensions-configurator==0.4.0    
kiwisolver==1.0.1                           
lazy-object-proxy==1.3.1                    
lxml==4.2.5                                 
MarkupSafe==1.0                             
matplotlib==3.0.0                           
mccabe==0.6.1                               
mistune==0.8.3                              
nbconvert==5.4.0                            
nbformat==4.4.0                             
nose==1.3.7                                 
notebook==5.7.0                             
ntlm-auth==1.2.0                            
numpy==1.15.2                               
openpyxl==2.5.7                             
pandas==0.23.4                              
pandocfilters==1.4.2                        
parso==0.3.1                                
patsy==0.5.0                                
pickleshare==0.7.4                          
plotly==3.2.1                               
prometheus-client==0.3.1                    
prompt-toolkit==1.0.15                      
pycodestyle==2.4.0                          
pycparser==2.19                             
Pygments==2.2.0                             
pylint==2.1.1                               
pyodbc==4.0.24                              
pyparsing==2.2.1                            
python-dateutil==2.7.3                      
pytz==2018.5                                
pywin32==223                                
pywinpty==0.5.4                             
PyYAML==3.13                                
pyzmq==17.1.2                               
qtconsole==4.4.1                            
requests==2.19.1                            
requests-ntlm==1.1.0                        
retrying==1.3.3                             
scipy==1.1.0                                
seaborn==0.9.0                              
Send2Trash==1.5.0                           
simplegeneric==0.8.1                        
six==1.11.0                                 
statsmodels==0.9.0                          
terminado==0.8.1                            
testpath==0.3.1                             
toolz==0.9.0                                
tornado==5.1.1                              
traitlets==4.3.2                            
typing==3.6.6                               
urllib3==1.23                               
vega==1.4.0                                 
vega-datasets==0.5.0                        
wcwidth==0.1.7                              
webencodings==0.5.1                         
widgetsnbextension==3.4.2                   
wrapt==1.10.11                              
xlrd==1.1.0                                 
xlwings==0.12.1                             
```python
# Your traceback here
I don't get traceback, I just get a Windows pop-up error message that just says the dreaded "Python has stopped working", with no other information.

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
import xlwings as xw
from xlwings import Range,constants
import pandas as pd

app1 = xw.apps
wb = app1.active.books.active

wb.app.screen_updating = False

for x in Range('A1:BZ1'):
    if x.value == 'ORIG_CUST_CNTN_TXT':
        orig_contention = x.get_address()
    elif x.value == 'ENRICH_CUST_CNTN_TXT':
        enrich_contention = x.get_address()
    elif x.value == 'FUNC_CHK_NOTE_REC_TXT':
        func_check = x.get_address()
    elif x.value == 'SUPL_ANA_INFO_REX_TXT':
        supl_info = x.get_address()
    elif x.value == 'VISUAL_CHK_NOTE_REX_TXT':
        vis_check = x.get_address()
    else:
        continue

last_row = Range('A1').current_region.last_cell.get_address()
_null, orig_contention_column, orig_contention_row = orig_contention.split('$')
_null, enrich_contention_column, enrich_contention_row = enrich_contention.split('$')
_null, func_check_column, func_check_row = func_check.split('$')
_null, supl_info_column, supl_info_row = supl_info.split('$')
_null, vis_check_column, vis_check_row = vis_check.split('$')
_null, column, row = last_row.split('$')

# Delete all contents in those specific columns
Range(orig_contention_column + '2' + ':' + orig_contention_column + str(row)).value = ''
Range(enrich_contention_column + '2' + ':' + enrich_contention_column + str(row)).value = ''
Range(func_check_column + '2' + ':' + func_check_column + str(row)).value = ''
Range(supl_info_column + '2' + ':' + supl_info_column + str(row)).value = ''
Range(vis_check_column + '2' + ':' + vis_check_column + str(row)).value = ''

# Create pivot table
df = Range('A1').current_region.options(pd.DataFrame).value
columns = df.columns
df.columns = [column.replace(' ','_') for column in columns]

df_final = df.query("CONCLUSION_TXT in('CAUSE UNKNOWN','SUPPLIER MFG. DEFECT')")

pivot = pd.pivot_table(df_final, index=['RPLCD_PART','Year','MARKET','MODEL'], 
                       columns='FACTORY', values=['VIN', 'Supplier_Cost'], margins=True,
                       aggfunc={'VIN':'count', 'Supplier_Cost':'sum'})

wb.sheets.add('Voucher Pivot')

Range('A1').value = pivot
Range('A:Q').autofit()
Range('A:Q').current_region.api.HorizontalAlignment = constants.HAlign.xlHAlignCenter

for cell in Range('A1').current_region:
    for border_id in range(7,12):
        cell.api.Borders(border_id).LineStyle = 1
        cell.api.Borders(border_id).Weight = 2
        
wb.app.screen_updating = True
```

**Comment by fzumstein** [comment]
you need to upgrade pywin32 to 224 for python 3.7

**Comment by pybokeh** [comment]
@fzumstein Thanks Felix!  That was it.

**Comment by smohapatraa** [comment]
> you need to upgrade pywin32 to 224 for python 3.7

Upgradation is done but still same issue is repeating. Please suggest.

**Comment by darknightush** [comment]
.lder (2)\lib\site-packages): Parse error at "'-umpy==1'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -ip 20.0.2 (e:\new fold
er (2)\lib\site-packages): Parse error at "'-ip==20.'": Expected W:(abcd...)
absl-py==0.11.0
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.12
anaconda-project==0.8.3
appdirs @ file:///home/conda/feedstock_root/build_artifacts/appdirs_160310839579
9/work
argh==0.26.2
asgiref==3.3.1
asn1crypto==1.3.0
astroid==2.3.2
astropy==4.0
astunparse==1.6.3
atomicwrites==1.3.0
attrs==19.3.0
Automat==20.2.0
autopep8==1.4.4
Babel==2.8.0
backcall==0.1.0
backports.functools-lru-cache==1.6.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
Bashutils==0.0.4
bcrypt==3.1.7
beautifulsoup4==4.8.2
bitarray==1.2.1
bkcharts==0.2
blaze==0.11.3
bleach==3.1.0
bokeh==1.4.0
boto==2.49.0
Bottleneck==1.3.2
cachetools==4.2.0
certifi==2020.12.5
cffi==1.14.0
chardet==3.0.4
Click==7.0
cloudpickle==1.3.0
clyent==1.2.2
cmake==3.18.4.post1
colorama==0.4.3
comtypes==1.1.7
conda==4.9.2
conda-build==3.18.11
conda-package-handling==1.6.0
conda-verify==3.4.2
constantly==15.1.0
contextlib2==0.6.0.post1
cryptography==2.8
cycler==0.10.0
Cython==0.29.15
cytoolz==0.10.1
dask==2.11.0
datashape==0.5.4
decorator==4.4.1
deepface==0.0.48
defusedxml==0.6.0
diff-match-patch==20181111
dill==0.3.3
distributed==2.11.0
Django==3.1.5
docutils==0.16
entrypoints==0.3
et-xmlfile==1.0.1
face-recognition==1.3.0
face-recognition-models==0.3.0
fastcache==1.1.0
filelock==3.0.12
flake8==3.7.9
Flask==1.1.2
Flask-Cors==3.0.8
flatbuffers==1.12
fsspec==0.6.2
future==0.18.2
gast==0.3.3
gdown==3.12.2
gevent==1.4.0
glob2==0.7
google-auth==1.24.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
greenlet==0.4.15
grpcio==1.32.0
h5py==2.10.0
HeapDict==1.0.1
html5lib==1.0.1
hyperlink @ file:///home/conda/feedstock_root/build_artifacts/hyperlink_16100921
64190/work
hypothesis==5.5.4
idna==2.8
imageio==2.6.1
imagesize==1.2.0
importlib-metadata==1.5.0
incremental==17.5.0
intervaltree==3.0.2
ipykernel==5.4.2
ipython==7.12.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.16.0
Jinja2==2.11.1
joblib==0.14.1
json5==0.9.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyterlab==1.2.6
jupyterlab-launcher==0.13.1
jupyterlab-server==1.0.6
Keras==2.4.3
Keras-Preprocessing==1.1.2
keyring==21.1.0
kiwisolver==1.1.0
layers==0.1.5
lazy-object-proxy==1.4.2
libarchive-c==2.8
llvmlite==0.31.0
locket==0.2.0
lxml==4.5.0
Markdown==3.3.3
MarkupSafe==1.1.1
matplotlib==3.1.3
mccabe==0.6.1
menuinst==1.4.16
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
mock==4.0.1
more-itertools==8.2.0
mpmath==1.1.0
msgpack==0.6.1
mtcnn==0.1.0
multipledispatch==0.6.0
navigator-updater==0.2.1
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.4
nltk==3.4.5
nose==1.3.7
notebook==6.0.3
numba==0.48.0
numexpr==2.7.1
numpy @ file:///D:/bld/numpy_1610324712085/work
numpydoc==0.9.2
oauthlib==3.1.0
odo==0.5.1
olefile==0.46
opencv-contrib-python==4.4.0.46
opencv-python==4.4.0.46
openpyxl==3.0.3
opt-einsum==3.3.0
packaging==20.1
pandas==1.0.1
pandocfilters==1.4.2
paramiko==2.7.1
parso==0.6.1
partd==1.1.0
path==13.1.0
pathlib2==2.3.5
pathtools==0.1.2
patsy==0.5.1
pep8==1.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
pkginfo==1.5.0.1
pluggy==0.13.1
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==3.0.3
protobuf==3.14.0
psutil==5.6.7
py==1.8.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.5
pydocstyle==4.0.1
pyflakes==2.1.1
Pygments==2.5.2
PyHamcrest==2.0.2
pylint==2.4.3
PyNaCl==1.3.0
pyodbc===4.0.0-unsupported
pyOpenSSL==19.1.0
pyparsing==2.4.6
PyQt5==5.12.3
PyQt5-sip==4.19.18
PyQtChart==5.12
PyQtWebEngine==5.12.1
pyreadline==2.1
pyrsistent==0.15.7
PySocks==1.7.1
pytest==5.3.5
pytest-arraydiff==0.3
pytest-astropy==0.8.0
pytest-astropy-header==0.1.2
pytest-doctestplus==0.5.0
pytest-openfiles==0.4.0
pytest-remotedata==0.3.2
python-dateutil==2.8.1
python-jsonrpc-server==0.3.4
python-language-server==0.31.7
pytz==2019.3
PyWavelets==1.1.1
pywin32==227
pywin32-ctypes==0.2.0
pywinpty==0.5.7
PyYAML==5.3
pyzmq==18.1.1
QDarkStyle==2.8
QtAwesome==0.6.1
qtconsole==4.6.0
QtPy==1.9.0
requests==2.22.0
requests-oauthlib==1.3.0
rope==0.16.0
rsa==4.6
Rtree==0.9.3
ruamel-yaml==0.15.87
scikit-image==0.16.2
scikit-learn==0.22.1
scipy==1.4.1
seaborn==0.10.0
Send2Trash==1.5.0
service-identity==18.1.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.15.0
snowballstemmer==2.0.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.9.5
Sphinx==2.4.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.2.0
spyder==4.0.1
spyder-kernels==1.8.1
SQLAlchemy==1.3.13
sqlparse==0.4.1
statsmodels==0.11.0
sympy==1.5.1
tables==3.6.1
tblib==1.6.0
tensorboard==2.4.0
tensorboard-plugin-wit==1.7.0
tensorflow==2.4.0
tensorflow-estimator==2.4.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
toolz==0.10.0
tornado==6.0.3
tqdm==4.42.1
traitlets==4.3.3
Twisted @ file:///D:/bld/twisted_1602649295260/work
typed-ast==1.4.0
typing-extensions==3.7.4.3
ujson==1.35
unicodecsv==0.14.1
urllib3==1.25.8
utilis==0.1.3
watchdog==0.10.2
wcwidth==0.1.8
webencodings==0.5.1
Werkzeug==1.0.0
widgetsnbextension==3.5.1
win-inet-pton==1.1.0
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.12.1
xlrd==1.2.0
XlsxWriter==1.2.7
xlwings==0.17.1
xlwt==1.3.0
xmltodict==0.12.0
yapf==0.28.0
zict==1.0.0
zipp==2.2.0
zope.interface @ file:///D:/bld/zope.interface_1610147035174/work
