### ISSUE TITLE
how to use sql to manipulate Excel from Python via xlwings(without an add-in)?

### ISSUE THREAD

**Issue by yuzhujiutian** [ZoomerAnalytics/xlwings#963]
[docs -> add-in](https://docs.xlwings.org/en/stable/addin.html#add-in)
Note that you don’t need an add-in if you just want to manipulate Excel from Python via xlwings.

Sorry, i found the information in the past few days, but I didn't understand how to use sql to manipulate Excel from Python via xlwings.(without an add-in)

Can you give an example?

Thanks

```OS environment
$ python -V
Python 3.6.5

$ pip list | findstr "xlwings"
xlwings                  0.12.1

$ python
>>> import platform
>>> platform.uname()
uname_result(system='Windows', node='brc', release='7', version='6.1.7601', machine='AMD64', processor='Intel64 Family 6 Model 61 Stepping 4, GenuineIntel')

```

**Comment by yuzhujiutian** [comment]
yes, i know it and i can use it.

but i want to use sql.py(D:\winusr\python\python36\python-3.6.5-amd64\Lib\site-packages\xlwings\ext\sql.py) in python via xlwings (without an add-in)

how can i write python code?

**Comment by fzumstein** [comment]
there you go: 

```
import xlwings as xw
from xlwings.ext.sql import sql

wb = xw.Book()

wb.sheets[0]['A1'].value = [['one', 'two'], [1, 10], [2, 20]]
wb.sheets[0]['D1'].value = [['three', 'four'], [1, 10], [2, 20]]


t1 = wb.sheets[0]['A1'].expand().value
t2 = wb.sheets[0]['D1'].expand().value

rv = sql("""select * from a inner join b on a.one = b.three where one = 1""", t1, t2)

print(rv)
```
