### ISSUE TITLE
MacOS Mojave: Excel won't open IndexError: list index out of range

### ISSUE THREAD

**Issue by kthirtyacre** [ZoomerAnalytics/xlwings#967]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Mojave
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings(0.13.0), Excel Version 16.19 (Office 365 subscription), Python 3.7
#### Describe your issue (incl. Traceback!)
Executing the python script via crontab, the Excel application opens up and the script fails with the Traceback below. The existing file that I'm trying to update does not open, just the "open new" page.
This problem is isolated to running the script via crontab. **_To be clear I have no issues with my script while executing manually in the terminal (python3 file.py), or by running in Visual Studio Code through the terminal._**

The issue seems to be related to the Mojave "upgrade", as I did not have this issue on Sierra. I've changed my security and permissions as indicated by many posts, and added terminal to have full disk access. In addition I've tried updating xcode as suggested (xcode-select --install), but it didn't seem to help.
The traceback suggests maybe it can't find the file or active instance.

Excel File Details:
- No VBA is used, it is a script to delete the existing data and paste in new data from a SQL query.
Crontab Details:
15 09 * * 1-5 /usr/local/bin/python3 "/Users/.../pixel_audit.py"

Apologies if this isn't specifically related to xlwings and it's more of an OS problem, but it does seem to be related to how the code is handling the files.

Thanks!

```python
Traceback (most recent call last):
  File "/Users/.../pixel_audit.py", line 224, in <module>
    main()
  File "/Users/.../pixel_audit.py", line 138, in main
    target = xw.Book(pix_audit)
  File "/usr/local/lib/python3.7/site-packages/xlwings/main.py", line 487, in __init__
    app = App(add_book=False)
  File "/usr/local/lib/python3.7/site-packages/xlwings/main.py", line 212, in __init__
    self.impl = xlplatform.App(spec=spec, add_book=add_book)
  File "/usr/local/lib/python3.7/site-packages/xlwings/_xlmac.py", line 65, in __init__
    self.activate()  # Makes it behave like on Windows
  File "/usr/local/lib/python3.7/site-packages/xlwings/_xlmac.py", line 98, in activate
    pid_frontmost = int(pid_info_frontmost.split('=')[1])
IndexError: list index out of range
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
pix_audit = '/Users/.../pixel_audit.xlsx'
target = xw.Book(pix_audit)
query_output = xw.Book(pix_audit).sheets[1]
query_output.range('A2:S250').value = ''
query_output.range('A2').value = output.values
master = xw.Book(pix_audit).sheets[0]

target.save()
target.close()


```

**Comment by kthirtyacre** [comment]
Thanks for the quick response.
I unchecked the show workbook, and aside from being much less annoying it didn't seem to make a difference.
I also tried installing versions 0.12.0 and 0.12.1, but both gave me the same error. There doesn't seem to be a version 0.12.2. 

One thing worth noting is that crontab has been deprecated in favor of launchd, so that may have something to do with it.

I wrote a script to simply open a specific workbook to determine if it was something else causing it, but got the same error. Running in vscode terminal, I'm seeing a reference to line 100 in activate. I suspect it has something to do with System Events.app or appscript not having access to the disk. I've added a few things to allow full disk access including AppleScript Utility.app, none of which seem to make a difference (screenshot)
```python
  File "/usr/local/lib/python3.7/site-packages/xlwings/main.py", line 487, in __init__
    app = App(add_book=False)
  File "/usr/local/lib/python3.7/site-packages/xlwings/main.py", line 212, in __init__
    self.impl = xlplatform.App(spec=spec, add_book=add_book)
  File "/usr/local/lib/python3.7/site-packages/xlwings/_xlmac.py", line 65, in __init__
    self.activate()  # Makes it behave like on Windows
  File "/usr/local/lib/python3.7/site-packages/xlwings/_xlmac.py", line 100, in activate
    appscript.app('System Events').processes[its.unix_id == self.pid].frontmost.set(True)
  File "/usr/local/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 496, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e
appscript.reference.CommandError: Command failed:
                OSERROR: -1743
                MESSAGE: OS error
                COMMAND: app('/System/Library/CoreServices/System Events.app').processes[its.unix_id == 97949].frontmost.set(True)
```

![image](https://user-images.githubusercontent.com/20135105/47519360-4e6ce280-d842-11e8-9eb5-ec5d0e779fb1.png)

**Comment by fzumstein** [comment]
I am closing this as I consider it solved. Please reopen if you have further issues.

**Comment by bishonen** [comment]
Felix, seeing the same issue in PyCharm myself. I can run xw.Book() which adds the terminal to automation with Excel inside, but how do I do the same for PyCharm as can be seen on your screenshot?

Thanks!

**Comment by mahmoudabosewar** [comment]
fzumstein

**Comment by Alishachen900** [comment]
I did that, but it said: no such file or directory…
My Pycharm app is PyCharm CE, is this a right pycharm app?
