### ISSUE TITLE
xlwings  Ribbon.GetPressedUdfServer returned a value not expected type

### ISSUE THREAD

**Issue by xxxspy** [ZoomerAnalytics/xlwings#970]
#### Describe your issue

When open Excel, Error shows:

![tim 20181027150655](https://user-images.githubusercontent.com/8189217/47600834-fc6ebd00-d9f9-11e8-843d-4cb0dde0c156.png)

**Comment by fzumstein** [comment]
Try to delete your `.xlwings\xlwings.conf` file and restart Excel to see if
that fixes it (you'll need to re enter the values in the ribbon then if you
changed something).

**Comment by Lobachevsky** [comment]
I had the same problem.  I "fixed" it by changing the code in `GetPressedUdfServer` to always return a boolean value, though the error message is gone there may still be a problem elsewhere.  `GetPressedUdfDebug` may have a similar problem.
