### ISSUE TITLE
Is it possible to preload python libraries/functions and not have to reload the whole file at each call?

### ISSUE THREAD

**Issue by olivierhbh** [ZoomerAnalytics/xlwings#971]
#### OS (e.g. Windows 10 or macOS Sierra)
Win7 Pro
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.11.4
#### Describe your issue (incl. Traceback!)
Is it possible to preload python libraries/functions and not have to reload the whole file at each call?

**Comment by fzumstein** [comment]
You can set the `Use UDF Server` setting to true, see: http://docs.xlwings.org/en/stable/addin.html#global-settings or you can use UDFs or Subs, see here: http://docs.xlwings.org/en/stable/udfs.html and http://docs.xlwings.org/en/stable/udfs.html#macros

**Comment by olivierhbh** [comment]
I wasn't really aware of that UDF Server setting... that's it, thanks a lot.

**Comment by olivierhbh** [comment]
Maybe another question related to that, is there a way to load a variable  (let's say an array of objects) in memory for later use?

**Comment by fzumstein** [comment]
You could work with a global:

```
import xlwings as xw

g = None

@xw.func
def hello(name):
    global g
    if g is None:
        g = 1
    else:
        g += 1
    return "hello {0}".format(str(g))
```

or maybe you're looking for something like this: https://github.com/ZoomerAnalytics/xlwings/issues/763

**Comment by olivierhbh** [comment]
Didn't even think about serializing, been a while... Thanks Felix, very useful info.
