### ISSUE TITLE
UDF Server Run-time error '1000'

### ISSUE THREAD

**Issue by Ashish424** [ZoomerAnalytics/xlwings#976]
#### I wanted to use udfs in excel but consistently experience the following error-
Run-time error '1000':
Could not activate Python COM server,hr = -2147467259

![cp](https://user-images.githubusercontent.com/6473382/47842609-31f11d00-dde3-11e8-9736-a8c09d41a04b.PNG)

However,running the debug server myself as described in the documentation works well.Any way to solve this problem?

**Comment by fzumstein** [comment]
try to put in the full path to your pythonw.exe in the interpreter field in the ribbon and see if that works.

**Comment by Ashish424** [comment]
Done that,I even tried python.exe instead of pythonw.exe ,the console windows open and closes instantly and the same error appears.

**Comment by fzumstein** [comment]
This seems the same issue as https://github.com/ZoomerAnalytics/xlwings/issues/766. based on that, maybe try a reboot or an office repair.

**Comment by fzumstein** [comment]
@Ashish424 were you able to solve that issue?

**Comment by Ashish424** [comment]
@fzumstein,I had to reinstall windows for some other reason and in the process reinstalled office which has seemed to fix the problem :)

**Comment by Leonguyen-biz** [comment]
please support
![image](https://user-images.githubusercontent.com/59854582/72775281-56335680-3c40-11ea-86b6-1fe60f8e3123.png)

**Comment by fzumstein** [comment]
Hi @Leonguyen-biz, please don't add stuff to closed issues but open a new one, thanks.
