### ISSUE TITLE
32 bit version on conda-forge

### ISSUE THREAD

**Issue by jmelo11** [ZoomerAnalytics/xlwings#981]
Hi all, is it posible have the last version compiled for 32 bit?

Thanks!!!

**Comment by fzumstein** [comment]
What do you mean? The xlwings package works with 32 and 64 bit of Python - the dlls is the only component that depends on the bitness of Excel (not Python) and accordingly both versions are contained in the package.

**Comment by jmelo11** [comment]
Sorry, i mean in the conda-forge site!

**Comment by fzumstein** [comment]
ah I see, something must have gone wrong with the build

**Comment by fzumstein** [comment]
opened an issue for that: https://github.com/conda-forge/xlwings-feedstock/issues/15

**Comment by fzumstein** [comment]
apprently, conda-forge has stopped to support 32-bit builds for windows, so I would recommend that you uninstall your conda package and use pip to install xlwings again.

**Comment by helpme1** [comment]
I just installed xlwings v0.14 using conda. No issue at all.
