### ISSUE TITLE
Import UDF Modules from different directory

### ISSUE THREAD

**Issue by phischmi** [ZoomerAnalytics/xlwings#983]
Is it possible to use one file for commonly used UDFs and place it in an directory different from the actual workbooks directory?
How can i point the Add-in to this path, as C://etc. obviously doesn't work.

**Comment by fzumstein** [comment]
Yes, via a combination of `PYTHONPATH` and `UDF_MODULES`, see: http://docs.xlwings.org/en/stable/addin.html#global-settings

**Comment by phischmi** [comment]
Oh... Thanks!!
