### ISSUE TITLE
xlwings Array Formulas

### ISSUE THREAD

**Issue by voanhq** [ZoomerAnalytics/xlwings#986]
#### Versions of xlwings, Excel and Python (e.g. 0.14.1, Microsoft Office Professional Plus 2016, Python 3.6)
Hello everyone,
I'm trying out the array formula code in the xlwings documentation but the function returns only 1 value at the top left. 
Any help would be appreciated

![aa](https://user-images.githubusercontent.com/43615742/48313570-3a223700-e5f1-11e8-8619-0f1e95bddeda.png)

![bb](https://user-images.githubusercontent.com/43615742/48313607-aac95380-e5f1-11e8-95d0-43cc35888ac7.png)

```python

@xw.func
def add_one(data):
    return [[cell + 1 for cell in row] for row in data]
```

**Comment by fzumstein** [comment]
you need to select the whole output range for traditional array formulas on Excel before you hit shift-ctrl-enter, see the exact steps as described here: http://docs.xlwings.org/en/stable/udfs.html#array-formulas-get-efficient

**Comment by voanhq** [comment]
Thank you very much. Apologies for not reading the doc carefully enough.
