### ISSUE TITLE
xlwings won't run on HighSierra with Excel 2019

### ISSUE THREAD

**Issue by sebnapi** [ZoomerAnalytics/xlwings#987]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS High Sierra
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Anaconda 3, Python 3.7
Excel 16.18 (2019)
```
>>> xlwings.__version__
'0.11.8'
```
#### Describe your issue (incl. Traceback!)

After running "xlwings runpython install", I don't get the message anymore, but just a "dong"-sound when clicken the button in the sheet, no log files appear. 
`~/Library/Application Scripts/com.microsoft.Excel/xlwings.applescript` is available.
I changed ".bash_profile" to ".profile" because it differs on my machine, but there seems to be other changes made by Excel (?!):

```
diff ~/Library/Application\ Scripts/com.microsoft.Excel/xlwings.applescript /anaconda3/pkgs/xlwings-0.11.8-py37_0/lib/python3.7/site-packages/xlwings/xlwings.applescript
6c6
<       set ShellCommand to PythonInterpreter & " -B -u -W ignore -c \"import sys, os;sys.path.extend(os.path.normcase(os.path.expandvars('" & PYTHONPATH & "')).split(';'));" & �
---
>       set ShellCommand to PythonInterpreter & " -B -u -W ignore -c \"import sys, os;sys.path.extend(os.path.normcase(os.path.expandvars('" & PYTHONPATH & "')).split(';'));" & ¬
9,10c9,10
<               do shell script "source ~/.profile"
<               return do shell script "source ~/.profile;" & ShellCommand
---
>               do shell script "source ~/.bash_profile"
>               return do shell script "source ~/.bash_profile;" & ShellCommand
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

Fibonacci example or Monte-Carlo example

**Comment by sebnapi** [comment]
Even if I remove the line-break symbol, it's only donging.

**Comment by fzumstein** [comment]
what action causes the donging?

**Comment by sebnapi** [comment]
Clicking the "run"/"lite" button in the mentioned sheets in an inpatient
way.

Am Di., 13. Nov. 2018, 11:18 hat Felix Zumstein <notifications@github.com>
geschrieben:

**Comment by fzumstein** [comment]
double click the applescript file to open it in the script editor and click the hammer symbol, does it compile correctly?

**Comment by sebnapi** [comment]
I don't have the corrupted file now, as I already said, when I'm removing the line-break symbol at all, it compiles but it doesn't show me any results in the sheets.

If I change it back to `.split(';'));" & ¬ ...`, open Excel hit the butttons few times, open it in applescript everything seems fine (the symbol is there) but if I diff the files:
```
diff ~/Library/Application\ Scripts/com.microsoft.Excel/xlwings.applescript /anaconda3/pkgs/xlwings-0
.11.8-py37_0/lib/python3.7/site-packages/xlwings/xlwings.applescript
6c6
<       set ShellCommand to PythonInterpreter & " -B -u -W ignore -c \"import sys, os;sys.path.extend(os.path.normcase(os.path.expandvars('" & PYTHONPATH & "')).split(';'));" & �
---
>       set ShellCommand to PythonInterpreter & " -B -u -W ignore -c \"import sys, os;sys.path.extend(os.path.normcase(os.path.expandvars('" & PYTHONPATH & "')).split(';'));" & ¬
9,10c9,10
```

**Comment by fzumstein** [comment]
I get the same diff but it works for me, so I don't think there's anything wrong with the applescript file. Set a VBA breakpoint [here](https://demo.xltrail.com/#/workbook/github.com%2FZoomerAnalytics%2Fxlwings.git%2Fxlwings%2Faddin%2Fxlwings.xlam/module/Main/?branch=master&scroll=%23vba-Main%20.line-num1.linenum-163) and see what the value for ParameterString is.

**Comment by sebnapi** [comment]
Great tip, it would have been my next question, how to debug the VBA code, as I'm not used to it.
At the breakpoint which you refer to, PYTHONPATH seems wrong: 
 `PYTHONPATH : "/Users/..../Projects/..../fib_xlwings_exp;/anaconda3/bin/python" : String`

_fib_xlwings_exp_ is the folder where I extracted your example. The parameter string is:
`ParameterString : "/Users/../Projects/../fib_xlwings_exp;/anaconda3/bin/python;,python,import fibonacci; fibonacci.xl_fibonacci(),/Users/../Projects/../fib_xlwings_exp/fibonacc"`

**Comment by fzumstein** [comment]
i think you truncated the string on the right hand side
