### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by sikosis** [ZoomerAnalytics/xlwings#988]
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Sierra 10.13.6

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Office 2016 16.16.3

#### Describe your issue (incl. Traceback!)

Using pip to install, fails. (Python 3.6.4)

    In file included from appscript_3x/ext/ae.c:15:
    In file included from appscript_3x/ext/ae.h:26:

```    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:34:10: fatal error: 'CarbonSound/CarbonSound.h' file not found
    #include <CarbonSound/CarbonSound.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/km/84c_kcms69n3ftcvlw5t5xtc0000gn/T/pip-install-m7_tmhvr/appscript/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/km/84c_kcms69n3ftcvlw5t5xtc0000gn/T/pip-record-2g7w2bln/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/km/84c_kcms69n3ftcvlw5t5xtc0000gn/T/pip-install-m7_tmhvr/appscript/
```

**Comment by fzumstein** [comment]
For a painless installation on Mac we recommend `conda` or otherwise you need to make sure to have the Xcode command line tools installed.

**Comment by 5fcgdaeb** [comment]
I am also running into this issue and I do have the latext XCode command line tools installed. I am running MacOS Mojave 10.14.2.

The error that I get is:

> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:34:10: fatal error: 'CarbonSound/CarbonSound.h' file not found
>     #include <CarbonSound/CarbonSound.h>
>              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
>     1 error generated.
>     error: command '/usr/bin/clang' failed with exit status 1


The `CarbonFramework` seems to be deprecated with MacOS Mojave and that might be causing the issue (https://developer.apple.com/documentation/macos_release_notes/macos_mojave_10_14_release_notes).

Do you have any other workarounds apart from using `conda`?

**Comment by fzumstein** [comment]
I can't replicate this, but we should be able to solve this by uploading a binary wheel to pypi.

**Comment by 5fcgdaeb** [comment]
That would be great, thanks!

Which CC are you using to compile the library? Let me see if I can help with the replication.

**Comment by fzumstein** [comment]
@5fcgdaeb are you running `python setup.py install` or `pip install appscript`?

**Comment by 5fcgdaeb** [comment]
`pip install xlwings==0.15.1` actually.

**Comment by fzumstein** [comment]
ok i could replicate it now with the python.org 3.7 distribution. I ll try to create the wheels soonish

**Comment by fzumstein** [comment]
@5fcgdaeb @sikosis   I have built wheels for appscript. Can you please download the attached zip file, then (1) unzip it and (2) do `pip install /path/to/appscript-1.0.1-cp37-cp37m-macosx_10_7_x86_64.whl` (make sure you pick the correct file according to your python version!)

Let me know if it works, then I can upload those to pypi and point the setup.py file to it in the next release.

[wheels.zip](https://github.com/ZoomerAnalytics/xlwings/files/2799458/wheels.zip)

**Comment by fzumstein** [comment]
sounds great, thanks!

**Comment by fzumstein** [comment]
has, the maintainer of appscript has generously uploaded my wheels to pypi, so you can just do pip install and I trust this issue is resolved now.

**Comment by 5fcgdaeb** [comment]
Really sorry for the late response @fzumstein! I have just tried the simple `pip install xlwings==0.15.1` and it works! Thanks so much for making this happen. Also, thanks to the maintainer of appscript.
