### ISSUE TITLE
"You can't change part of an array" when trying to edit async table formula

### ISSUE THREAD

**Issue by Colin-b** [ZoomerAnalytics/xlwings#994]
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 7

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings 0.15.0 / Office 365 / Python 3.6.5

#### Describe your issue (incl. Traceback!)

Calling a UDF (with ret='table') with async_mode='threading' works fine but to call it once again I need to do so using the function wizard, otherwise I am now rejected with: "You can't change part of an array".

I assume this is related to the new performance enhancement with array formula?

Is there a way to still be able to edit formula within a cell / in the cell content bar?

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
@xw.func(async_mode='threading')
@xw.ret(expand='table')
def async_table_test():
    return [['test'] * 5] * 10

```

**Comment by Colin-b** [comment]
Indeed it works fine that way. Apologies, still have a lot to learn about Excel ;-)

**Comment by fzumstein** [comment]
I imroved the docs: https://github.com/ZoomerAnalytics/xlwings/commit/1a4db89b48452d6f75685d16d803a1536a33b53c
