### ISSUE TITLE
No module named arm - OSX

### ISSUE THREAD

**Issue by tngn** [ZoomerAnalytics/xlwings#996]
#### Describe your issue (incl. Traceback!)

```python
# Your traceback here
ImportError                               Traceback (most recent call last)
<ipython-input-303-c05117874218> in <module>()

/Library/Python/2.7/site-packages/xlwings/__init__.py in <module>()
     42     from . import _xlwindows as xlplatform
     43 else:
---> 44     from . import _xlmac as xlplatform
     45 
     46 time_types = xlplatform.time_types

/Library/Python/2.7/site-packages/xlwings/_xlmac.py in <module>()
      8 
      9 import psutil
---> 10 import aem
     11 import appscript
     12 from appscript import k as kw, mactypes, its

ImportError: No module named aem
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here
----> 1 import xlwings as xw
      2 wb = xw.Book(r'sample.xlsm') # use raw str to avoid backslash
      3 sht = wb.sheets['sample']
      4 sht.range('M5').value # this has the formula:
      # =IF(AND($F$150<>$F$149,$F$150>0),"Infinite",MAX($L$144:$L$150))
      # but I want the results, not the formula itself
```

Installation results log:
...
Successfully built xlwings psutil appscript
Installing collected packages: psutil, appscript, xlwings
Successfully installed appscript-1.0.1 psutil-5.4.8 xlwings-0.15.0

511 ~ 08:53:35$ sudo -H pip install aem
Collecting aem
  Could not find a version that satisfies the requirement aem (from versions: )
No matching distribution found for aem

**Comment by fzumstein** [comment]
closing this. feel free to reopen if this is not resolved.

**Comment by fzumstein** [comment]
@tngn please try to install appscript from the wheels I have just uploaded to https://github.com/ZoomerAnalytics/xlwings/issues/988 if the problem persists.
